import { useState, useEffect } from "react";
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip as RTooltip, ResponsiveContainer, PieChart, Pie, Cell } from "recharts";

const fmt = n => Math.round(n||0).toLocaleString("fr-FR");
const fmt2 = n => (n||0).toLocaleString("fr-FR",{minimumFractionDigits:2,maximumFractionDigits:2});
const DK = {bg:"#08080B",card:"#141419",card2:"#1C1C24",bd:"#26262F",txt:"#F5F5F7",sub:"#8A8A94",grn:"#22C55E",red:"#EF4444",blue:"#3b82f6",amber:"#f59e0b"};
const CL = ["#3b82f6","#22c55e","#8b5cf6","#f59e0b","#ec4899","#06b6d4"];
const CATC = {Liquidités:"#3b82f6",Investissements:"#22c55e",Crypto:"#8b5cf6",Immobilier:"#f59e0b",Autres:"#ec4899"};

const CO = {
  france:{l:"🇫🇷 France",cur:"€",tmi:[[11294,0],[28797,11],[82341,30],[177106,41],[1e12,45]],parts:true,
    inv:{n:"PEA",tip:"Investir en bourse avec avantage fiscal après 5 ans.",bk:"Bourse Direct, Boursorama"},
    ass:{n:"Assurance-vie",tip:"Enveloppe souple, avantage fiscal après 8 ans.",bk:"Linxea Avenir 2"},
    ret:{n:"PER",tip:"Versements déductibles des impôts, bloqué jusqu'à la retraite.",bk:"Linxea Spirit PER"},
    liv:{n:"Livret A",rate:2.4,tip:"Épargne réglementée 2,4 %, 0 impôt, plafond 22 950 €."},liv2:{n:"LDDS"},
    tax:{optim:{n:"PEA",r:17.2},std:{n:"Compte-titres",r:30}},def:{immo:40000,mar:15000,etu:15000},sav:"Livret A + LDDS"},
  tunisie:{l:"🇹🇳 Tunisie",cur:"DT",tmi:[[5000,0],[20000,26],[30000,28],[50000,32],[1e12,35]],parts:false,
    inv:{n:"CEA (Bourse de Tunis)",tip:"Compte Épargne en Actions, déduction fiscale BVMT.",bk:"Tunisie Valeurs, MAC SA, BIAT Capital"},
    ass:{n:"Assurance-vie",tip:"Contrats en dinars, avantage fiscal.",bk:"BIAT, GAT, Maghrebia"},
    ret:{n:"Contrat retraite",tip:"Épargne retraite complémentaire déductible.",bk:"GAT, Maghrebia Vie"},
    liv:{n:"Compte Épargne",rate:5,tip:"Compte épargne bancaire tunisien ~5%/an, capital garanti."},liv2:null,
    tax:{optim:{n:"CEA",r:10},std:{n:"Compte-titres",r:20}},def:{immo:50000,mar:30000,etu:15000},sav:"Compte Épargne"},
  malte:{l:"🇲🇹 Malte",cur:"€",tmi:[[9100,0],[14500,15],[19500,25],[60000,25],[1e12,35]],parts:false,
    inv:{n:"Compte-titres (broker)",tip:"ETF via courtier, fiscalité avantageuse long terme.",bk:"Interactive Brokers, DEGIRO"},
    ass:{n:"Assurance-vie",tip:"Contrats d'investissement, transmission facilitée.",bk:"MAPFRE MSV Life"},
    ret:{n:"Pension privée (3e pilier)",tip:"Crédit d'impôt jusqu'à 750€/an.",bk:"APS, HSBC Malta"},
    liv:{n:"Compte épargne",rate:2,tip:"Épargne bancaire ~2%/an, capital garanti."},liv2:null,
    tax:{optim:{n:"Détention longue",r:0},std:{n:"Compte imposé",r:15}},def:{immo:45000,mar:14000,etu:12000},sav:"Compte épargne"},
  canada:{l:"🇨🇦 Canada",cur:"$",tmi:[[55000,20],[110000,30],[165000,38],[235000,45],[1e12,50]],parts:false,
    inv:{n:"CELI (investissement)",tip:"Gains 100% exonérés à vie !",bk:"Wealthsimple, Questrade"},
    ass:{n:"Compte non-enregistré",tip:"50% des gains imposables.",bk:"Wealthsimple, Questrade"},
    ret:{n:"REER",tip:"Versements déductibles des impôts.",bk:"Wealthsimple, Questrade"},
    liv:{n:"CELI / HISA",rate:4,tip:"Compte d'épargne à intérêt élevé ~4%/an."},liv2:null,
    tax:{optim:{n:"CELI",r:0},std:{n:"Non-enregistré",r:25}},def:{immo:60000,mar:25000,etu:30000},sav:"CELI liquidités"},
  allemagne:{l:"🇩🇪 Allemagne",cur:"€",tmi:[[11604,0],[17000,14],[66761,24],[277825,42],[1e12,45]],parts:false,
    inv:{n:"ETF-Depot (Sparplan)",tip:"Plan d'investissement ETF, abattement 1000€/an.",bk:"Trade Republic, Scalable Capital"},
    ass:{n:"Depot secondaire",tip:"Compte-titres pour actions individuelles.",bk:"Trade Republic, comdirect"},
    ret:{n:"Rürup / Riester",tip:"Épargne retraite déductible.",bk:"Allianz, Cosmos Direkt"},
    liv:{n:"Tagesgeld",rate:3,tip:"Compte épargne à vue ~3%/an."},liv2:null,
    tax:{optim:{n:"ETF (Teilfreistellung)",r:18.5},std:{n:"Compte standard",r:26.4}},def:{immo:40000,mar:14000,etu:13000},sav:"Tagesgeld"},
};
const CITY={capitale:{l:"🏙️ Capitale",m:1.5},grande:{l:"🏢 Grande ville",m:1},petite:{l:"🏘️ Petite ville",m:0.7}};
const GOAL_T=[{id:"immo",emoji:"🏠",nom:"Achat immobilier"},{id:"mariage",emoji:"💍",nom:"Mariage"},{id:"fire",emoji:"🏖️",nom:"Retraite anticipée"},{id:"etudes",emoji:"🎓",nom:"Études enfants"},{id:"voyage",emoji:"✈️",nom:"Voyage / projet"},{id:"capital",emoji:"💰",nom:"Capital cible"},{id:"vehicule",emoji:"🚗",nom:"Véhicule"}];
const SCEN={pessimiste:{sG:"1",inf:"3",rA:"4",rV:"2",rL:"1.5",l:"😟 Pessimiste"},base:{sG:"2",inf:"2",rA:"7",rV:"4",rL:"2.4",l:"📊 Base"},optimiste:{sG:"3",inf:"1.5",rA:"10",rV:"6",rL:"3",l:"🚀 Optimiste"}};
const IDEAL={Dynamique:[{n:"Actions",p:65,c:"#3b82f6"},{n:"Assurance",p:15,c:"#22c55e"},{n:"Livrets",p:15,c:"#f59e0b"},{n:"Crypto",p:5,c:"#8b5cf6"}],"Équilibré":[{n:"Actions",p:50,c:"#3b82f6"},{n:"Assurance",p:25,c:"#22c55e"},{n:"Livrets",p:20,c:"#f59e0b"},{n:"Crypto",p:5,c:"#8b5cf6"}],Prudent:[{n:"Actions",p:30,c:"#3b82f6"},{n:"Assurance",p:30,c:"#22c55e"},{n:"Livrets",p:35,c:"#f59e0b"},{n:"Or",p:5,c:"#f59e0b"}]};
const PARTS_TIP="Les parts fiscales (France uniquement) divisent votre revenu imposable pour calculer l'impôt. Seul = 1 part. Couple = 2 parts. Chaque enfant = 0,5 part (1 part dès le 3e enfant). Plus vous avez de parts, moins vous payez d'impôts.";
const smartDef=(id,pays,ville,enf)=>{const c=CO[pays]||CO.france;const m=CITY[ville]?.m||1;const e=parseInt(enf)||1;switch(id){case"immo":return Math.round(c.def.immo*m);case"mariage":return Math.round(c.def.mar*m);case"etudes":return Math.round(c.def.etu*m*e);case"fire":return 500000;case"capital":return 100000;case"voyage":return 5000;case"vehicule":return 15000;default:return 10000;}};

// Banques pour questionnaire
const BANKS_LIST=[
  {id:"boursorama",nom:"Boursorama",type:"En ligne",emoji:"🏦"},
  {id:"fortuneo",nom:"Fortuneo",type:"En ligne",emoji:"⭐"},
  {id:"hello",nom:"Hello bank! (BNP)",type:"En ligne",emoji:"👋"},
  {id:"ing",nom:"ING",type:"En ligne",emoji:"🧡"},
  {id:"bourse_direct",nom:"Bourse Direct",type:"Courtier",emoji:"💰"},
  {id:"ca",nom:"Crédit Agricole",type:"Traditionnel",emoji:"🌾"},
  {id:"bnp",nom:"BNP Paribas",type:"Traditionnel",emoji:"🏛️"},
  {id:"sg",nom:"Société Générale",type:"Traditionnel",emoji:"🔴"},
  {id:"lcl",nom:"LCL",type:"Traditionnel",emoji:"🏦"},
  {id:"ce",nom:"Caisse d'Épargne",type:"Traditionnel",emoji:"🐻"},
  {id:"bp",nom:"Banque Populaire",type:"Traditionnel",emoji:"🏦"},
  {id:"cic",nom:"CIC",type:"Traditionnel",emoji:"🏦"},
  {id:"laposte",nom:"La Banque Postale",type:"Traditionnel",emoji:"📮"},
  {id:"revolut",nom:"Revolut",type:"Neobank 📱",emoji:"🚀"},
  {id:"n26",nom:"N26",type:"Neobank 📱",emoji:"⚫"},
  {id:"nickel",nom:"Nickel",type:"Neobank 📱",emoji:"🟢"},
  {id:"sumeria",nom:"Lydia / Sumeria",type:"Neobank 📱",emoji:"💜"},
  {id:"wise",nom:"Wise",type:"Neobank 📱",emoji:"💚"},
];

// Détails des actions (pourquoi, plafond, banques recommandées)
const ACTION_DETAILS={
  la:{icon:"🏦",priorite:"URGENT",couleur:"#EF4444",
    titre:"Ouvrir un Livret A",
    pourquoi:"Le Livret A est la base absolue de toute épargne. C'est votre filet de sécurité : zéro risque de perte, zéro impôt sur les intérêts, et votre argent est disponible immédiatement (pas bloqué). Sans ce matelas, la moindre dépense imprévue (panne de voiture, problème de santé, perte d'emploi) peut vous forcer à vendre vos investissements au pire moment.",
    plafond:"22 950 € de versements maximum",taux:"2,4 %/an (net d'impôts, garanti par l'État)",
    banques:[
      {nom:"Votre banque actuelle",emoji:"🏦",why:"C'est gratuit et ça prend 2 minutes. Appelez votre conseiller ou faites-le en ligne depuis votre espace client.",forBanques:[]},
      {nom:"Boursorama",emoji:"💻",why:"100% en ligne, ouverture en 5 minutes. Si vous êtes déjà client : c'est 2 clics depuis votre espace client.",forBanques:["boursorama"]},
      {nom:"Fortuneo",emoji:"⭐",why:"Élue meilleure banque en ligne plusieurs années consécutives. Zéro frais, interface claire.",forBanques:["fortuneo"]},
      {nom:"La Banque Postale",emoji:"📮",why:"Présente dans tous les bureaux de poste de France. Idéal si vous préférez parler à quelqu'un.",forBanques:[]},
    ]},
  ldds:{icon:"🌱",priorite:"HAUTE",couleur:"#f59e0b",
    titre:"Ouvrir un LDDS",
    pourquoi:"Le LDDS (Livret de Développement Durable et Solidaire) est un second Livret A : même taux (2,4 %), même avantage fiscal (zéro impôt), mais avec un plafond distinct. Il vous permet de placer jusqu'à 12 000 € supplémentaires en toute sécurité, en complément de votre Livret A.",
    plafond:"12 000 € de versements maximum",taux:"2,4 %/an (net d'impôts, identique au Livret A)",
    banques:[
      {nom:"Votre banque actuelle",emoji:"🏦",why:"Demandez-le directement dans votre banque. C'est gratuit et quasi instantané.",forBanques:[]},
      {nom:"Boursorama",emoji:"💻",why:"Si déjà client : ouverture en 2 clics. Tout centralisé.",forBanques:["boursorama"]},
      {nom:"Crédit Mutuel",emoji:"🏛️",why:"Très bonne interface numérique, service client reconnu.",forBanques:[]},
    ]},
  pea:{icon:"📈",priorite:"URGENT",couleur:"#EF4444",
    titre:"Ouvrir un PEA",
    pourquoi:"Le PEA (Plan d'Épargne en Actions) est L'enveloppe prioritaire pour investir en bourse. Voici pourquoi : après 5 ans d'ouverture, vos gains ne sont taxés qu'à 17,2% (prélèvements sociaux) au lieu de 30% (flat tax normale). Sur 20 ans d'investissement à 7%/an, cette différence représente des dizaines de milliers d'euros économisés. Ouvrez-le MAINTENANT même avec 10€ : ce qui compte, c'est de lancer le compteur des 5 ans LE PLUS TÔT POSSIBLE.",
    plafond:"150 000 € de versements maximum (les gains peuvent dépasser ce plafond librement)",taux:"~7 %/an historique long terme (rendement moyen des marchés boursiers mondiaux)",
    banques:[
      {nom:"Bourse Direct",emoji:"💰",why:"Frais les plus bas du marché : 0,99€ par ordre jusqu'à 500€. Idéal pour le DCA mensuel car chaque euro compte.",forBanques:["bourse_direct"]},
      {nom:"Boursorama",emoji:"🏦",why:"Si vous êtes déjà client Boursorama : tout est centralisé dans la même application. Légèrement plus cher (1,99€/ordre) mais très pratique.",forBanques:["boursorama"]},
      {nom:"Fortuneo",emoji:"⭐",why:"Interface intuitive, particulièrement recommandé pour les débutants. 1,95€/ordre.",forBanques:["fortuneo"]},
    ]},
  av:{icon:"🛡️",priorite:"MOYENNE",couleur:"#3b82f6",
    titre:"Ouvrir une Assurance-vie",
    pourquoi:"L'assurance-vie est le complément parfait du PEA. Ses avantages : (1) Aucun plafond de versement, contrairement au PEA. (2) Après 8 ans, vous bénéficiez d'un abattement fiscal de 4 600€/an sur les gains (9 200€ en couple). (3) Jusqu'à 152 500€ transmis à chaque bénéficiaire sans droits de succession en cas de décès. (4) Accès aux fonds euros à capital garanti pour sécuriser une partie de votre épargne.",
    plafond:"Aucun plafond de versement (contrairement au PEA limité à 150 000€)",taux:"2 à 7 %/an selon votre allocation entre fonds euros (sécurisé) et ETF (dynamique)",
    banques:[
      {nom:"Linxea Avenir 2",emoji:"🏆",why:"Le meilleur contrat du marché selon les experts : frais à seulement 0,6%/an, large choix d'ETF en unités de compte, fonds euros performant (3%+).",forBanques:[]},
      {nom:"Boursorama Vie",emoji:"🏦",why:"Si vous êtes déjà client Boursorama : simple, bien intégré dans la même application.",forBanques:["boursorama"]},
      {nom:"Placement-direct Vie",emoji:"⭐",why:"Excellent rapport qualité/prix, frais comparables à Linxea. Bonne alternative.",forBanques:[]},
    ]},
  per:{icon:"🏛️",priorite:"MOYENNE",couleur:"#3b82f6",
    titre:"Ouvrir un PER",
    pourquoi:"Le PER (Plan d'Épargne Retraite) vous permet de déduire vos versements de votre revenu imposable MAINTENANT. Concrètement : si vous versez 3 000€ et que votre TMI est de 30%, vous économisez 900€ d'impôts cette année. L'argent est bloqué jusqu'à la retraite (sauf achat de résidence principale), mais l'avantage fiscal est immédiat et très puissant pour les hauts revenus.",
    plafond:"10% de vos revenus N-1 (maximum ~35 000€/an)",taux:"3 à 6 %/an selon votre allocation",
    banques:[
      {nom:"Linxea Spirit PER",emoji:"🏆",why:"Le meilleur PER individuel du marché : frais à 0,5%/an, large choix dont ETF MSCI World, interface claire.",forBanques:[]},
      {nom:"Boursorama Matla",emoji:"🏦",why:"Si vous êtes déjà client Boursorama : simple et bien intégré. 0,5%/an de frais.",forBanques:["boursorama"]},
      {nom:"Placement-direct Spirit PER",emoji:"⭐",why:"Même contrat que Linxea, excellente alternative avec les mêmes avantages.",forBanques:[]},
    ]},
  dca:{icon:"🔄",priorite:"HAUTE",couleur:"#f59e0b",
    titre:"Mettre en place un DCA automatique",
    pourquoi:"Le DCA (Dollar Cost Averaging = investissement régulier programmé) est LA stratégie qui bat 95% des investisseurs particuliers sur le long terme. Le principe : vous investissez un montant fixe chaque mois automatiquement, sans vous poser de questions. Quand la bourse baisse, votre montant fixe achète plus de parts (c'est les soldes !). Quand elle monte, vos parts existantes prennent de la valeur. Résultat : vous lissez votre prix d'achat dans le temps et vous éliminez le stress du 'timing'.",
    plafond:null,taux:null,banques:null},
  prec:{icon:"🛡️",priorite:"URGENT",couleur:"#EF4444",
    titre:"Compléter votre épargne de précaution",
    pourquoi:"Avant d'investir en bourse, vous devez ABSOLUMENT avoir 3 à 6 mois de charges en réserve sur des comptes sécurisés (Livret A + LDDS). Sans ce matelas, une dépense imprévue peut vous forcer à vendre vos investissements boursiers au pire moment (pendant une baisse), transformant une perte temporaire en perte permanente.",
    plafond:"Cible : 3 à 6 mois de charges sur Livret A + LDDS",taux:"2,4 %/an (Livret A + LDDS, zéro impôt)",banques:null},
};

// Banques pour prêt immobilier (taux juillet 2026)
const PRET_BANQUES=[
  {nom:"Courtier (Meilleurtaux, Pretto, CAFPI)",emoji:"🔍",taux:"Meilleur taux du marché",why:"Un courtier compare TOUTES les banques et négocie pour vous. C'est gratuit pour vous (la banque rémunère le courtier) et c'est souvent la meilleure option pour obtenir le taux le plus bas.",recommande:true,type:"Courtier"},
  {nom:"Bourso Bank",emoji:"🏦",taux:"Parmi les plus bas (~3%)",why:"En juillet 2026, Bourso Bank propose les taux les plus compétitifs du marché. Idéal si vous êtes déjà client.",recommande:false,type:"En ligne"},
  {nom:"Hello bank! (BNP)",emoji:"👋",taux:"~3,1 à 3,4%",why:"Filiale de BNP Paribas, processus 100% digital, taux attractifs.",recommande:false,type:"En ligne"},
  {nom:"Crédit Agricole",emoji:"🌾",taux:"~3,2 à 3,7%",why:"Excellent accompagnement physique, possibilité de négociation en agence, présent partout en France.",recommande:false,type:"Physique"},
  {nom:"Caisse d'Épargne",emoji:"🐻",taux:"~3,2 à 3,7%",why:"Spécialiste du crédit immobilier, très bon accompagnement, forte implantation régionale.",recommande:false,type:"Physique"},
];

// === COMPOSANTS UI QUESTIONNAIRE (thème clair) ===
function Tip({text}){const[o,setO]=useState(false);return(<span className="relative inline-block ml-1"><button onClick={()=>setO(!o)} className="w-5 h-5 rounded-full bg-slate-200 text-slate-600 text-xs font-bold inline-flex items-center justify-center">?</button>{o&&<div className="absolute z-50 bottom-7 left-1/2 -translate-x-1/2 w-72 bg-slate-800 text-white text-sm rounded-xl p-3 shadow-xl" style={{maxWidth:"85vw"}}>{text}</div>}</span>);}
function Card({children,className=""}){return<div className={"bg-white rounded-2xl shadow-sm border border-slate-200 p-5 "+className}>{children}</div>;}
function Sel({label,value,onChange,options,tooltip,id}){return(<div className="mb-4"><label htmlFor={id} className="block text-sm font-semibold text-slate-700 mb-1">{label}{tooltip&&<Tip text={tooltip}/>}</label><select id={id} value={value} onChange={e=>onChange(e.target.value)} className="w-full border border-slate-300 rounded-xl px-4 py-3 text-slate-800 bg-white outline-none text-base">{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></div>);}
function Inp({label,value,onChange,type="number",placeholder,tooltip,suffix,id}){return(<div className="mb-4"><label htmlFor={id} className="block text-sm font-semibold text-slate-700 mb-1">{label}{tooltip&&<Tip text={tooltip}/>}</label><div className="relative"><input id={id} type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="w-full border border-slate-300 rounded-xl px-4 py-3 text-slate-800 bg-white outline-none text-base"/>{suffix&&<span className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400 text-sm">{suffix}</span>}</div></div>);}
function Btn({onClick,children,secondary}){return secondary?<button onClick={onClick} className="border border-slate-300 text-slate-600 font-semibold px-6 py-3 rounded-xl hover:bg-slate-50 text-sm">{children}</button>:<button onClick={onClick} className="bg-gradient-to-r from-blue-600 to-indigo-600 text-white font-semibold px-6 py-3 rounded-xl shadow text-sm">{children}</button>;}
function Prog({c,t}){const p=t>0?Math.round(c/t*100):0;return(<div className="w-full mb-6"><div className="flex justify-between text-sm text-slate-500 mb-1"><span>Étape {c}/{t}</span><span>{p}%</span></div><div className="w-full h-2 bg-slate-200 rounded-full overflow-hidden"><div className="h-full bg-gradient-to-r from-blue-500 to-indigo-500 rounded-full transition-all duration-500" style={{width:`${p}%`}}/></div></div>);}
function BCards({items}){return(<div className="grid gap-2 mt-2">{items.map((b,i)=>(<div key={i} className="border-2 rounded-xl p-3 border-slate-200 bg-slate-50"><div className="flex items-center gap-2"><span className="text-xl">{b.e}</span><span className="font-bold text-slate-800 text-sm">{b.n}</span>{i===0&&<span className="text-xs bg-yellow-400 text-yellow-900 px-2 py-0.5 rounded-full font-bold ml-auto">Top</span>}</div>{b.f&&<p className="text-xs text-slate-600 mt-1">{b.f}</p>}</div>))}</div>);}

// === COMPOSANTS UI DASHBOARD (thème sombre Finary) ===
function DCard({children,style={},className=""}){return<div className={className} style={{background:DK.card,border:`1px solid ${DK.bd}`,borderRadius:16,padding:18,...style}}>{children}</div>;}
function DInp({label,value,onChange,type="number",placeholder,suffix,id}){return(<div className="mb-3"><label htmlFor={id} className="block text-xs font-semibold mb-1" style={{color:DK.sub}}>{label}</label><div className="relative"><input id={id} type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} style={{background:DK.card2,border:`1px solid ${DK.bd}`,color:DK.txt}} className="w-full rounded-xl px-3 py-2.5 outline-none text-sm"/>{suffix&&<span className="absolute right-3 top-1/2 -translate-y-1/2 text-xs" style={{color:DK.sub}}>{suffix}</span>}</div></div>);}
function DSel({label,value,onChange,options,id}){return(<div className="mb-3"><label htmlFor={id} className="block text-xs font-semibold mb-1" style={{color:DK.sub}}>{label}</label><select id={id} value={value} onChange={e=>onChange(e.target.value)} style={{background:DK.card2,border:`1px solid ${DK.bd}`,color:DK.txt}} className="w-full rounded-xl px-3 py-2.5 outline-none text-sm">{options.map(o=><option key={o.value} value={o.value} style={{background:DK.card2}}>{o.label}</option>)}</select></div>);}
function Gauge({score,size=90}){const color=score>=70?DK.grn:score>=40?DK.amber:DK.red;const r=size/2-5;const circ=2*Math.PI*r;return(<div className="relative" style={{width:size,height:size}}><svg viewBox={`0 0 ${size} ${size}`} className="-rotate-90"><circle cx={size/2} cy={size/2} r={r} fill="none" stroke={DK.bd} strokeWidth="7"/><circle cx={size/2} cy={size/2} r={r} fill="none" stroke={color} strokeWidth="7" strokeDasharray={circ} strokeDashoffset={circ*(1-score/100)} strokeLinecap="round"/></svg><span className="absolute inset-0 flex items-center justify-center font-bold text-lg" style={{color:DK.txt}}>{score}</span></div>);}

const SAVE_KEY="nheb_v8";
function loadState(){try{const s=localStorage.getItem(SAVE_KEY);return s?JSON.parse(s):null;}catch{return null;}}
function saveState(d){try{localStorage.setItem(SAVE_KEY,JSON.stringify(d));}catch{}}

export default function App(){
const saved=loadState();const I=(k,d)=>saved?.[k]??d;
const[page,setPage]=useState(I("page","q"));const[step,setStep]=useState(I("step",0));const[dashTab,setDashTab]=useState("patrimoine");const[toolTab,setToolTab]=useState("acheter");const[done,setDone]=useState(I("done",false));
const[age,setAge]=useState(I("age",""));const[statut,setStatut]=useState(I("statut",""));const[situationFam,setSituationFam]=useState(I("situationFam",""));const[nbEnfants,setNbEnfants]=useState(I("nbEnfants",""));const[logement,setLogement]=useState(I("logement",""));const[pays,setPays]=useState(I("pays",""));const[villeType,setVilleType]=useState(I("villeType",""));
const[banquesActuelles,setBanquesActuelles]=useState(I("banquesActuelles",[]));
const[modeCouple,setModeCouple]=useState(I("modeCouple",false));const[p2Rev,setP2Rev]=useState(I("p2Rev",""));const[p2Ch,setP2Ch]=useState(I("p2Ch",""));const[p2Ep,setP2Ep]=useState(I("p2Ep",""));
const[typeRevenu,setTypeRevenu]=useState(I("typeRevenu","net_mensuel"));const[brutAnnuel,setBrutAnnuel]=useState(I("brutAnnuel",""));const[netMensuel,setNetMensuel]=useState(I("netMensuel",""));const[primes,setPrimes]=useState(I("primes",""));const[autresRev,setAutresRev]=useState(I("autresRev",""));
const[loyer,setLoyer]=useState(I("loyer",""));const[alimentation,setAlimentation]=useState(I("alimentation",""));const[transports,setTransports]=useState(I("transports",""));const[abonnements,setAbonnements]=useState(I("abonnements",""));const[assurancesCh,setAssurancesCh]=useState(I("assurancesCh",""));const[loisirs,setLoisirs]=useState(I("loisirs",""));const[creditsConso,setCreditsConso]=useState(I("creditsConso",""));const[autresCharges,setAutresCharges]=useState(I("autresCharges",""));
const[epargnePrecaution,setEpargnePrecaution]=useState(I("epargnePrecaution",""));const[montantEpargne,setMontantEpargne]=useState(I("montantEpargne",""));const[aLivretA,setALivretA]=useState(I("aLivretA",""));const[aLDDS,setALDDS]=useState(I("aLDDS",""));
const[aPEA,setAPEA]=useState(I("aPEA",""));const[aPER,setAPER]=useState(I("aPER",""));const[aAV,setAAV]=useState(I("aAV",""));
const[peaMontant,setPeaMontant]=useState(I("peaMontant",""));const[peaDepuis,setPeaDepuis]=useState(I("peaDepuis",""));const[perMontant,setPerMontant]=useState(I("perMontant",""));const[avMontant,setAvMontant]=useState(I("avMontant",""));
const[aCrypto,setACrypto]=useState(I("aCrypto",""));const[cryptoMontant,setCryptoMontant]=useState(I("cryptoMontant",""));const[immoValeur,setImmoValeur]=useState(I("immoValeur",""));const[autresActifs,setAutresActifs]=useState(I("autresActifs",""));
const[toleranceRisque,setToleranceRisque]=useState(I("toleranceRisque",""));const[horizon,setHorizon]=useState(I("horizon",""));const[reaction,setReaction]=useState(I("reaction",""));
const[userGoals,setUserGoals]=useState(I("userGoals",[]));const[entries,setEntries]=useState(I("entries",[]));const[actionsDone,setActionsDone]=useState(I("actionsDone",{}));const[soldeCourant,setSoldeCourant]=useState(I("soldeCourant",""));
const[positions,setPositions]=useState(I("positions",[]));const[showPF,setShowPF]=useState(false);const[newP,setNewP]=useState({nom:"",type:"ETF",enveloppe:"PEA",qte:"",pru:"",prix:""});const[editPosIdx,setEditPosIdx]=useState(null);const[editPos,setEditPos]=useState(null);
const[expandedActions,setExpandedActions]=useState({});
const[bpSalG,setBpSalG]=useState(I("bpSalG","2"));const[bpInfl,setBpInfl]=useState(I("bpInfl","2"));const[bpRetAct,setBpRetAct]=useState(I("bpRetAct","7"));const[bpRetAV,setBpRetAV]=useState(I("bpRetAV","4"));const[bpRetLiv,setBpRetLiv]=useState(I("bpRetLiv","2.4"));
const[bpEvents,setBpEvents]=useState(I("bpEvents",[]));const[showEF,setShowEF]=useState(false);const[newE,setNewE]=useState({date:new Date().toISOString().slice(0,7),pea:"",av:"",per:"",livrets:"",crypto:"",soldeCc:"",immo:"",autres:"",versement:"",retrait:"",notes:""});const[showEvF,setShowEvF]=useState(false);const[newEv,setNewEv]=useState({nom:"",annee:"",cout:""});const[showDCA,setShowDCA]=useState(false);
const[credits,setCredits]=useState(I("credits",[]));const[showCF,setShowCF]=useState(false);const[newCr,setNewCr]=useState({nom:"",restant:"",taux:"",mensualite:""});
const[bienPrix,setBienPrix]=useState("");const[apport,setApport]=useState("");const[tauxCr,setTauxCr]=useState("3.5");const[dureeCr,setDureeCr]=useState("25");const[loyerAct,setLoyerAct]=useState("");const[chargesCo,setChargesCo]=useState("");const[taxeF,setTaxeF]=useState("");

useEffect(()=>{saveState({page,step,done,age,statut,situationFam,nbEnfants,logement,pays,villeType,banquesActuelles,modeCouple,p2Rev,p2Ch,p2Ep,typeRevenu,brutAnnuel,netMensuel,primes,autresRev,loyer,alimentation,transports,abonnements,assurancesCh,loisirs,creditsConso,autresCharges,epargnePrecaution,montantEpargne,aLivretA,aLDDS,aPEA,aPER,aAV,peaMontant,peaDepuis,perMontant,avMontant,aCrypto,cryptoMontant,immoValeur,autresActifs,toleranceRisque,horizon,reaction,userGoals,entries,actionsDone,soldeCourant,positions,bpSalG,bpInfl,bpRetAct,bpRetAV,bpRetLiv,bpEvents,credits});});

const C=CO[pays]||CO.france;const cur=C.cur;const fc=n=>fmt(n)+" "+cur;

// Obtenir les banques recommandées en tenant compte des banques actuelles
const getBankRecos=(actionId)=>{const det=ACTION_DETAILS[actionId];if(!det?.banques)return[];const all=det.banques;const prio=all.filter(b=>b.forBanques.length===0||b.forBanques.some(id=>banquesActuelles.includes(id)));const others=all.filter(b=>!prio.includes(b));return [...prio,...others].slice(0,3);};

const getNet=()=>{if(typeRevenu==="net_mensuel")return(parseFloat(netMensuel)||0)+(parseFloat(primes)||0)/12+(parseFloat(autresRev)||0);const b=parseFloat(brutAnnuel)||0;const t=statut==="fonctionnaire"?0.83:statut==="independant"?0.55:0.75;return b*t/12+(parseFloat(primes)||0)/12+(parseFloat(autresRev)||0);};
const totalCh=()=>[loyer,alimentation,transports,abonnements,assurancesCh,loisirs,creditsConso,autresCharges].reduce((s,v)=>s+(parseFloat(v)||0),0);
const rev=getNet();const ch=totalCh();const dispo=rev-ch;
const coupleRev=modeCouple?rev+(parseFloat(p2Rev)||0):rev;const coupleCh=modeCouple?ch+(parseFloat(p2Ch)||0):ch;const coupleDispo=coupleRev-coupleCh;
const epNum=parseFloat(montantEpargne)||0;const moisEp=ch>0?epNum/ch:0;
const peaV=parseFloat(peaMontant)||0,avV=parseFloat(avMontant)||0,perV=parseFloat(perMontant)||0,cryptoV=parseFloat(cryptoMontant)||0,immoV=parseFloat(immoValeur)||0,autresV=parseFloat(autresActifs)||0;
const lastE=entries[entries.length-1];
const snap=lastE?{pea:lastE.pea,av:lastE.av,per:lastE.per,livrets:lastE.livrets,crypto:lastE.crypto||0,cash:lastE.soldeCc||0,immo:lastE.immo||0,autres:lastE.autres||0}:{pea:peaV,av:avV,per:perV,livrets:epNum+(modeCouple?(parseFloat(p2Ep)||0):0),crypto:cryptoV,cash:parseFloat(soldeCourant)||0,immo:immoV,autres:autresV};
const patFin=snap.pea+snap.av+snap.per+snap.livrets+snap.crypto;
const netWorth=patFin+snap.cash+snap.immo+snap.autres;
const totalVersements=entries.reduce((s,e)=>s+(e.versement||0),0);

const posCalc=positions.map(p=>{const q=parseFloat(p.qte)||0,pru=parseFloat(p.pru)||0,px=parseFloat(p.prix)||0;const invest=q*pru,valeur=q*px,pv=valeur-invest,perf=invest>0?(pv/invest*100):0;return{...p,invest,valeur,pv,perf};});
const posTotal=posCalc.reduce((s,p)=>s+p.valeur,0);
const posInvest=posCalc.reduce((s,p)=>s+p.invest,0);

const getTMI=()=>{const br=C.tmi;let annual,p=1;if(C.parts){annual=(modeCouple?coupleRev:rev)*12;if(situationFam==="couple"||modeCouple)p=2;if(situationFam==="famille")p=2+Math.min(parseInt(nbEnfants)||0,2)*0.5+Math.max(0,(parseInt(nbEnfants)||0)-2);}else annual=(modeCouple?coupleRev:rev)*12;const qi=(annual*0.9)/p;for(const[seuil,taux]of br)if(qi<=seuil)return taux;return br[br.length-1][1];};
const getProfil=()=>{let s=0;s+=toleranceRisque==="agressif"?3:toleranceRisque==="modere"?2:1;s+=horizon==="long"?3:horizon==="moyen"?2:1;s+=reaction==="acheter"?3:reaction==="rien"?2:1;if(s>=7)return{label:"Dynamique",cl:"text-emerald-600",pct:90};if(s>=5)return{label:"Équilibré",cl:"text-blue-600",pct:70};return{label:"Prudent",cl:"text-amber-600",pct:50};};
const getMI=()=>{const d=modeCouple?coupleDispo:dispo;if(d<=0)return 0;if(moisEp<3)return Math.floor(d*0.1);if(moisEp<6)return Math.floor(d*0.2);return Math.floor(d*0.35);};
const profil=getProfil();const mi=getMI();const tmi=getTMI();const idealAlloc=IDEAL[profil.label]||IDEAL["Équilibré"];
const savingsRate=coupleRev>0?Math.round((mi/coupleRev)*100):0;
const fireNumber=(modeCouple?coupleCh:ch)*12*25;
const fireProgress=fireNumber>0?Math.min(100,Math.round(patFin/fireNumber*100)):0;
const passiveIncome=Math.round((snap.pea*0.02+snap.av*0.025+snap.livrets*(C.liv.rate/100)+snap.immo*0.03)/12);

const getDCASplit=()=>{if(mi<=0)return[];const etfs=[{n:"ETF MSCI World",isin:"IE00B4L5Y983",ter:"0,20 %",p:profil.pct>=80?70:profil.pct>=60?60:45,why:"Base du portefeuille : 1 500 entreprises, 23 pays développés"},{n:"ETF Emerging Markets",isin:"IE00BKM4GZ66",ter:"0,18 %",p:profil.pct>=80?15:10,why:"Pays émergents : Chine, Inde, Brésil"},{n:"ETF Europe",isin:"—",ter:"0,15 %",p:15,why:"Diversification européenne"}];if(profil.pct<80)etfs.push({n:"ETF Obligations",isin:"—",ter:"0,15 %",p:profil.pct>=60?10:25,why:"Stabilité et sécurité"});if(mi<100)return[{...etfs[0],montant:mi,p:100,why:"Budget < 100€/mois : concentrez tout ici pour éviter les frais sur plusieurs ordres"}];return etfs.map(e=>({...e,montant:Math.round(mi*e.p/100)}));};
const getDiversScore=()=>{let s=0;const d=[];const add=(n,pts,ok)=>{if(ok)s+=pts;d.push({n,s:pts,ok});};add(C.liv.n,20,aLivretA==="oui");add(C.inv.n,25,aPEA==="oui");add(C.ass.n,15,aAV==="oui");if(tmi>=30)add(C.ret.n,10,aPER==="oui");add("Matelas 3 mois+",10,moisEp>=3);add("DCA actif",10,mi>0);add("Patrimoine > 10k",10,patFin>10000);return{score:Math.min(100,s),details:d};};
const getTaxComparison=()=>[5,10,15,20].map(y=>{const n=y*12,r=0.07/12;const fv=mi*((Math.pow(1+r,n)-1)/r);const g=fv-mi*n;return{y,gains:Math.round(g),taxOptim:Math.round(g*C.tax.optim.r/100),taxStd:Math.round(g*C.tax.std.r/100),saved:Math.round(g*(C.tax.std.r-C.tax.optim.r)/100)};});
const getRebalance=()=>{if(patFin<=0)return[];const pd=[{name:"Actions",v:snap.pea},{name:"Assurance",v:snap.av+snap.per},{name:"Livrets",v:snap.livrets},{name:"Crypto",v:snap.crypto}].filter(x=>x.v>0);if(pd.length===0)return[];const sig=[];const ap=pd.map(x=>({name:x.name,pct:Math.round(x.v/patFin*100),val:x.v}));idealAlloc.forEach(ia=>{const a=ap.find(x=>x.name===ia.n);const aP=a?a.pct:0,aV=a?a.val:0,iV=Math.round(patFin*ia.p/100),diff=aP-ia.p;if(diff>10){const tg=idealAlloc.filter(t=>{const ta=ap.find(x=>x.name===t.n);return(ta?ta.pct:0)<t.p-5;});sig.push({sev:"warning",icon:"🔶",msg:`${ia.n} surpondéré : ${aP} % (cible ${ia.p} %)`,action:`Redirigez ~${fc(aV-iV)} vers ${tg.map(t=>t.n).join(", ")||"les autres enveloppes"}`,det:"Orientez vos prochains versements DCA sans forcément vendre."});}else if(diff<-10)sig.push({sev:"info",icon:"🔵",msg:`${ia.n} sous-pondéré : ${aP} % (cible ${ia.p} %)`,action:`Augmentez ${ia.n} de ~${fc(iV-aV)}`,det:"Priorisez cette poche dans vos prochains versements."});});if(sig.length===0)sig.push({sev:"success",icon:"✅",msg:"Allocation bien calibrée",action:"Continuez votre DCA habituel",det:"Écart inférieur à 10 % : aucune action nécessaire."});return sig;};

const genBP=()=>{const d=[];let r=(modeCouple?coupleRev:rev)*12,c=(modeCouple?coupleCh:ch)*12;let pea=snap.pea,av=snap.av,liv=snap.livrets;const invest=mi*12;const sg=parseFloat(bpSalG)/100,inf=parseFloat(bpInfl)/100,ra=parseFloat(bpRetAct)/100,rv=parseFloat(bpRetAV)/100,rl=parseFloat(bpRetLiv)/100;const ageN=parseInt(age)||30;const cy=new Date().getFullYear();const pp=profil.pct>=80?0.65:profil.pct>=60?0.5:0.3,ap=profil.pct>=80?0.15:0.25,lp=1-pp-ap;
for(let y=1;y<=20;y++){const evM=bpEvents.filter(e=>parseInt(e.annee)===y);const evG=userGoals.filter(g=>(parseInt(g.annee)||cy+5)-cy===y);let ec=evM.reduce((s,e)=>s+(parseFloat(e.cout)||0),0)+evG.reduce((s,g)=>s+(parseFloat(g.cible)||0),0);let ed=[...evM.map(e=>e.nom),...evG.map(g=>g.emoji+" "+g.nom)].filter(Boolean).join(", ");pea*=(1+ra);av*=(1+rv);liv*=(1+rl);const yI=invest*Math.pow(1+sg,y-1);pea+=yI*pp;av+=yI*ap;liv+=yI*lp;if(ec>0){let rem=ec;const tk=(s,a)=>{const t=Math.min(Math.max(0,s),a);return[s-t,a-t];};[liv,rem]=tk(liv,rem);[av,rem]=tk(av,rem);[pea,rem]=tk(pea,rem);}r*=(1+sg);c*=(1+inf);const total=Math.round(Math.max(0,pea)+Math.max(0,av)+perV+Math.max(0,liv));const reel=Math.round(total/Math.pow(1+inf,y));d.push({y,age:ageN+y,pea:Math.round(Math.max(0,pea)),av:Math.round(Math.max(0,av)),liv:Math.round(Math.max(0,liv)),total,reel,ev:ed});}return d;};
const getBPAlerts=data=>{const a=[];const cy=new Date().getFullYear();userGoals.forEach(g=>{const tY=(parseInt(g.annee)||cy+5)-cy;const cible=parseFloat(g.cible)||0;if(tY<1||tY>20)return;const row=data[tY-1];if(!row)return;if(row.total<cible)a.push({type:"danger",emoji:g.emoji,nom:g.nom,msg:`Année ${tY} : ${fc(row.total)} estimé vs ${fc(cible)} requis. Manque ${fc(cible-row.total)}.`,conseil:"Augmentez l'épargne mensuelle, repoussez ou réduisez le montant."});else a.push({type:"success",emoji:g.emoji,nom:g.nom,msg:`✅ "${g.nom}" atteignable ! Patrimoine estimé : ${fc(row.total)} (cible : ${fc(cible)}).`,conseil:null});});return a;};

const getRecos=()=>{const r=[];const es=[{nom:C.liv.n,has:aLivretA==="oui",rdt:C.liv.rate+" %",risque:"Aucun",desc:C.liv.tip}];if(C.liv2)es.push({nom:C.liv2.n,has:aLDDS==="oui",rdt:C.liv.rate+" %",risque:"Aucun",desc:"Complément épargne réglementée."});es.push({nom:C.inv.n,has:aPEA==="oui",rdt:"~7 %/an",risque:"Modéré",desc:C.inv.tip});es.push({nom:C.ass.n,has:aAV==="oui",rdt:"2 à 6 %",risque:"Variable",desc:C.ass.tip});if(tmi>=30)es.push({nom:C.ret.n,has:aPER==="oui",rdt:"3 à 6 %",risque:"Variable",desc:C.ret.tip});r.push({tier:"🟢 Essentiels",items:es});const t2=[{nom:"Crypto (BTC + ETH)",has:snap.crypto>0,rdt:"Variable",risque:"Très élevé",desc:`Max ${profil.pct>=80?"5":"3"} % du patrimoine.`}];if(patFin>5000)t2.push({nom:"SCPI",has:false,rdt:"4 à 6 %",risque:"Modéré",desc:"Immobilier papier, revenus locatifs réguliers."});if(patFin>10000)t2.push({nom:"Or (ETF)",has:false,rdt:"3 à 5 %",risque:"Modéré",desc:"Protection anti-inflation et anti-crise. Max 10 %."});r.push({tier:"🔵 Diversification",items:t2});const t3=[];if(patFin>50000)t3.push({nom:"CTO (actions internationales)",has:false,rdt:"~7 %",risque:"Élevé",desc:"Quand votre PEA est plein (150 000€)."});if(patFin>30000)t3.push({nom:"Crowdfunding immobilier",has:false,rdt:"8 à 12 %",risque:"Élevé",desc:"Prêts à promoteurs. Capital non garanti."});if(patFin>100000)t3.push({nom:"Private Equity",has:false,rdt:"10 à 15 %",risque:"Très élevé",desc:"Entreprises non cotées. Bloqué 10 ans. 100k€+ requis."});if(t3.length>0)r.push({tier:"🟣 Avancé",items:t3});return r;};

const analyzeGoal=g=>{const cy=new Date().getFullYear();const yl=Math.max(0,(parseInt(g.annee)||cy+5)-cy);const cible=parseFloat(g.cible)||0;if(cible<=0)return{prog:0,mn:0,yl,status:"on_track"};const prog=Math.min(100,Math.round(patFin/cible*100));if(patFin>=cible)return{prog:100,mn:0,yl,status:"atteint"};if(yl===0)return{prog,mn:0,yl,status:"echoue"};const r=0.06/12,n=yl*12,fv=patFin*Math.pow(1+r,n),rem=Math.max(0,cible-fv);const mn=rem>0?Math.round(rem/((Math.pow(1+r,n)-1)/r)):0;return{prog,mn,yl,status:mn<=mi?"on_track":mn<=mi*1.5?"tight":"unrealistic"};};

const getActions=()=>{const a=[];if(aLivretA!=="oui")a.push({id:"la",txt:"Ouvrir un Livret A",p:"critique"});if(C.liv2&&aLDDS!=="oui")a.push({id:"ldds",txt:"Ouvrir un LDDS",p:"haute"});if(aPEA!=="oui")a.push({id:"pea",txt:`Ouvrir un ${C.inv.n}`,p:"critique"});if(moisEp<6)a.push({id:"prec",txt:`Épargne de précaution → ${fc(ch*6)} (objectif 6 mois)`,p:"critique"});if(aAV!=="oui")a.push({id:"av",txt:`Ouvrir une ${C.ass.n}`,p:"moyenne"});if(tmi>=30&&aPER!=="oui")a.push({id:"per",txt:`Ouvrir un ${C.ret.n}`,p:"moyenne"});if(mi>0&&aPEA==="oui")a.push({id:"dca",txt:`Mettre en place un DCA de ${fc(mi)}/mois`,p:"haute"});return a;};
const getAlerts=()=>{const a=[];const dormant=Math.max(0,snap.cash-ch*1.1);if(dormant>500)a.push({t:"warning",icon:"💤",titre:`${fc(dormant)} dormants sur compte courant`,txt:`Vous avez ${fc(dormant)} qui ne travaillent pas. Placez-les sur votre ${moisEp<6?C.liv.n:C.inv.n}.`});if(pays==="france"&&peaDepuis==="plus5")a.push({t:"info",icon:"🔓",titre:"PEA mature : retraits possibles à 17,2 %",txt:"Votre PEA a plus de 5 ans. Vous pouvez retirer avec seulement 17,2% de prélèvements sociaux (au lieu de 30%). Utile si un objectif est atteint."});if(pays==="france"&&peaDepuis==="3a5")a.push({t:"warning",icon:"⏳",titre:"PEA bientôt mature : NE RETIREZ PAS",txt:"Votre PEA approche des 5 ans. Tout retrait maintenant clôture le PEA et vous fait perdre l'avantage fiscal. Attendez !"});if(moisEp<3&&epargnePrecaution!=="non")a.push({t:"danger",icon:"🚨",titre:"Épargne de précaution insuffisante",txt:`${moisEp.toFixed(1)} mois de charges seulement. Alimentez d'abord votre Livret A avant d'investir en bourse.`});posCalc.forEach(p=>{if(p.perf<=-20)a.push({t:"info",icon:"📉",titre:`${p.nom} en forte baisse (${p.perf.toFixed(0)} %)`,txt:"Rappel : ne vendez pas sous la panique. Si vous croyez toujours à cet actif sur le long terme, c'est l'occasion de renforcer (DCA)."});if(p.perf>=50)a.push({t:"success",icon:"📈",titre:`${p.nom} : belle plus-value (+${p.perf.toFixed(0)} %)`,txt:"Pensez à rééquilibrer si cette ligne pèse trop lourd dans votre portefeuille."});});userGoals.forEach(g=>{if(analyzeGoal(g).status==="atteint")a.push({t:"success",icon:"🎉",titre:`Objectif "${g.nom}" atteint !`,txt:"Sécurisez vos gains : transférez vers un support moins risqué si vous comptez utiliser cet argent bientôt."});});return a;};

const toggleGoal=t=>{const ex=userGoals.find(g=>g.id===t.id);if(ex)setUserGoals(userGoals.filter(g=>g.id!==t.id));else setUserGoals([...userGoals,{...t,cible:smartDef(t.id,pays,villeType,nbEnfants),annee:new Date().getFullYear()+(t.id==="fire"?20:t.id==="immo"?7:5),wantLoan:"",loanAmount:"",loanDuration:"20"}]);};
const updGoal=(id,f,v)=>setUserGoals(userGoals.map(g=>g.id===id?{...g,[f]:v}:g));
const toggleBanque=id=>{setBanquesActuelles(prev=>prev.includes(id)?prev.filter(x=>x!==id):[...prev,id]);};

const getSteps=()=>{const s=["intro","profil","banques","revenus","charges","epargne","enveloppes","actifs"];if(pays==="france"&&aPEA==="oui")s.push("d_pea");s.push("risque","objectifs","resultats");return s;};
const steps=getSteps();const cs=steps[step]||"intro";const next=()=>step<steps.length-1&&setStep(step+1);const prev=()=>step>0&&setStep(step-1);

const goToDash=()=>{if(entries.length===0)setEntries([{date:new Date().toISOString().slice(0,7),pea:peaV,av:avV,per:perV,livrets:epNum+(modeCouple?(parseFloat(p2Ep)||0):0),crypto:cryptoV,soldeCc:parseFloat(soldeCourant)||0,immo:immoV,autres:autresV,versement:0,retrait:0,notes:"Bilan initial"}]);setDone(true);setPage("d");};
const addEntry=()=>{const e={date:newE.date,pea:parseFloat(newE.pea)||0,av:parseFloat(newE.av)||0,per:parseFloat(newE.per)||0,livrets:parseFloat(newE.livrets)||0,crypto:parseFloat(newE.crypto)||0,soldeCc:parseFloat(newE.soldeCc)||0,immo:parseFloat(newE.immo)||0,autres:parseFloat(newE.autres)||0,versement:parseFloat(newE.versement)||0,retrait:parseFloat(newE.retrait)||0,notes:newE.notes};setEntries(p=>[...p,e].sort((a,b)=>a.date.localeCompare(b.date)));setShowEF(false);setNewE({date:new Date().toISOString().slice(0,7),pea:"",av:"",per:"",livrets:"",crypto:"",soldeCc:"",immo:"",autres:"",versement:"",retrait:"",notes:""});};
const addPos=()=>{if(!newP.nom)return;setPositions(p=>[...p,newP]);setNewP({nom:"",type:"ETF",enveloppe:"PEA",qte:"",pru:"",prix:""});setShowPF(false);};
const saveEditPos=()=>{if(editPosIdx===null)return;setPositions(prev=>prev.map((p,i)=>i===editPosIdx?editPos:p));setEditPosIdx(null);setEditPos(null);};
const applyScenario=k=>{const s=SCEN[k];setBpSalG(s.sG);setBpInfl(s.inf);setBpRetAct(s.rA);setBpRetAV(s.rV);setBpRetLiv(s.rL);};

const chartData=entries.map(e=>({m:e.date.slice(5)+"/"+e.date.slice(2,4),Total:e.pea+e.av+e.per+e.livrets+(e.crypto||0)+(e.soldeCc||0)+(e.immo||0)+(e.autres||0)}));
const catData=[{name:"Liquidités",v:snap.cash+snap.livrets},{name:"Investissements",v:snap.pea+snap.av+snap.per},{name:"Crypto",v:snap.crypto},{name:"Immobilier",v:snap.immo},{name:"Autres",v:snap.autres}].filter(d=>d.v>0);
const perf=(()=>{if(entries.length<2)return null;const f=entries[0],l=entries[entries.length-1];const fv=f.pea+f.av+f.per+f.livrets+(f.crypto||0)+(f.soldeCc||0)+(f.immo||0)+(f.autres||0);const lv=l.pea+l.av+l.per+l.livrets+(l.crypto||0)+(l.soldeCc||0)+(l.immo||0)+(l.autres||0);const diff=lv-fv;return{diff,pct:fv>0?(diff/fv*100):0,gains:diff-totalVersements};})();

// ===== QUESTIONNAIRE =====
const rIntro=()=>(<div className="text-center"><div className="text-5xl mb-3">💸</div><h1 className="text-3xl font-black mb-1">Nheb Barcha Flous</h1><p className="text-slate-400 text-sm mb-4 italic">نحب برشا فلوس</p><p className="text-slate-600 mb-6">Votre <strong>conseiller financier personnel</strong> adapté à votre pays et votre banque.</p>{saved&&done&&<p className="text-sm text-emerald-600 mb-4">💾 Données précédentes restaurées !</p>}<Btn onClick={next}>Commencer →</Btn><p className="text-xs text-slate-400 mt-4">⚠️ Outil de réflexion, pas du conseil financier réglementé.</p></div>);

const rProfil=()=>(<div><h2 className="text-xl font-bold mb-4">👤 Votre situation</h2><Inp id="age" label="Âge" value={age} onChange={setAge} placeholder="28" suffix="ans"/><Sel id="pays" label="Pays de résidence" value={pays} onChange={setPays} tooltip="Détermine la fiscalité, les produits recommandés et la monnaie affichée." options={[{value:"",label:"Choisir"},...Object.entries(CO).map(([k,v])=>({value:k,label:v.l}))]}/><Sel id="vt" label="Type de ville" value={villeType} onChange={setVilleType} options={[{value:"",label:"Choisir"},...Object.entries(CITY).map(([k,v])=>({value:k,label:v.l}))]}/><Sel id="st" label="Statut professionnel" value={statut} onChange={setStatut} options={[{value:"",label:"Choisir"},{value:"salarie",label:"💼 Salarié(e)"},{value:"independant",label:"🏠 Indépendant(e)"},{value:"fonctionnaire",label:"🏛️ Fonctionnaire"},{value:"etudiant",label:"🎓 Étudiant(e)"},{value:"retraite",label:"🌅 Retraité(e)"}]}/><Sel id="fam" label="Situation familiale" value={situationFam} onChange={setSituationFam} options={[{value:"",label:"Choisir"},{value:"seul",label:"Seul(e)"},{value:"couple",label:"En couple"},{value:"famille",label:"Avec enfant(s)"}]}/>{situationFam==="famille"&&<Inp id="enf" label="Nombre d'enfants à charge" value={nbEnfants} onChange={setNbEnfants} placeholder="2" tooltip={PARTS_TIP}/>}{(situationFam==="couple"||situationFam==="famille")&&<div className="bg-violet-50 border border-violet-200 rounded-xl p-4 mb-4"><div className="flex items-center justify-between mb-2"><p className="font-bold text-sm text-violet-800">👫 Mode couple (finances partagées)</p><button onClick={()=>setModeCouple(!modeCouple)} className={`px-3 py-1 rounded-full text-xs font-bold ${modeCouple?"bg-violet-600 text-white":"bg-violet-200 text-violet-700"}`}>{modeCouple?"Activé ✓":"Activer"}</button></div>{modeCouple&&<><Inp id="p2r" label="Revenus net conjoint(e)" value={p2Rev} onChange={setP2Rev} placeholder="2 000" suffix={cur+"/m"}/><Inp id="p2c" label="Charges conjoint(e)" value={p2Ch} onChange={setP2Ch} placeholder="500" suffix={cur+"/m"}/><Inp id="p2e" label="Épargne conjoint(e)" value={p2Ep} onChange={setP2Ep} placeholder="3 000" suffix={cur}/></>}</div>}<Sel id="log" label="Logement" value={logement} onChange={setLogement} options={[{value:"",label:"Choisir"},{value:"locataire",label:"🏠 Locataire"},{value:"proprietaire",label:"🏡 Propriétaire (crédit en cours)"},{value:"proprio_fini",label:"🏡 Propriétaire (crédit terminé)"},{value:"heberge",label:"Hébergé(e) gratuitement"}]}/></div>);

const rBanques=()=>(<div><h2 className="text-xl font-bold mb-2">🏦 Vos banques actuelles</h2><p className="text-slate-500 text-sm mb-4">Sélectionnez toutes les banques où vous avez un compte. Cela permet de personnaliser les recommandations (ex : si vous êtes déjà chez Boursorama, on vous dira d'ouvrir votre PEA là-bas plutôt que de changer de banque).</p>
{["En ligne","Traditionnel","Neobank 📱","Courtier"].map(type=>{const items=BANKS_LIST.filter(b=>b.type===type);return(<div key={type} className="mb-4"><p className="text-xs font-bold text-slate-500 uppercase mb-2">{type}</p><div className="grid grid-cols-2 gap-2">{items.map(b=>{const sel=banquesActuelles.includes(b.id);return(<button key={b.id} onClick={()=>toggleBanque(b.id)} className={`p-3 rounded-xl border-2 text-left flex items-center gap-2 transition ${sel?"border-blue-500 bg-blue-50":"border-slate-200 hover:border-blue-300"}`}><span className="text-lg">{b.emoji}</span><span className={`text-sm font-semibold ${sel?"text-blue-700":"text-slate-700"}`}>{b.nom}</span>{sel&&<span className="ml-auto text-blue-500">✓</span>}</button>);})}</div></div>);})}
{banquesActuelles.length===0&&<p className="text-sm text-slate-400 italic text-center py-2">Aucune sélectionnée — passez à l'étape suivante si vous n'en avez pas encore.</p>}
{banquesActuelles.length>0&&<div className="bg-emerald-50 border border-emerald-200 rounded-xl p-3 text-sm text-emerald-800">✅ Banques sélectionnées : <strong>{banquesActuelles.map(id=>BANKS_LIST.find(b=>b.id===id)?.nom).join(", ")}</strong>. On adaptera les recommandations.</div>}
</div>);

const rRevenus=()=>(<div><h2 className="text-xl font-bold mb-4">💰 Revenus</h2><Sel id="tr" label="Format de saisie" value={typeRevenu} onChange={setTypeRevenu} options={[{value:"net_mensuel",label:"💶 Net mensuel (après impôts)"},{value:"brut_annuel",label:"📋 Brut annuel (avant charges)"}]}/>{typeRevenu==="brut_annuel"?<Inp id="brut" label="Salaire brut annuel" value={brutAnnuel} onChange={setBrutAnnuel} placeholder="35 000" suffix={cur+"/an"}/>:<Inp id="net" label="Salaire net mensuel" value={netMensuel} onChange={setNetMensuel} placeholder="2 200" suffix={cur+"/mois"}/>}<Inp id="pr" label="Primes annuelles (13e mois, bonus…)" value={primes} onChange={setPrimes} placeholder="3 000" suffix={cur+"/an"}/><Inp id="ar" label="Autres revenus mensuels" value={autresRev} onChange={setAutresRev} placeholder="200" suffix={cur+"/mois"} tooltip="Revenus freelance, allocations, pensions, loyers perçus…"/>{rev>0&&<div className="bg-emerald-50 border border-emerald-200 rounded-xl p-4 mt-2"><p className="text-emerald-800 font-semibold text-lg">{modeCouple?`Revenus couple : ${fc(coupleRev)}`:`Total revenus : ${fc(rev)}`}/mois</p>{tmi>0&&<p className="text-emerald-700 text-sm mt-1">Tranche Marginale d'Imposition (TMI) estimée ({C.l}) : <strong>{tmi} %</strong> <Tip text="La TMI est le taux d'impôt appliqué sur votre dernière tranche de revenus. C'est le taux qui détermine l'avantage fiscal de votre PER : si TMI = 30%, chaque 1000€ versé dans le PER vous économise 300€ d'impôts."/></p>}</div>}</div>);

const rCharges=()=>(<div><h2 className="text-xl font-bold mb-4">🧾 Charges mensuelles</h2><Inp id="loy" label="🏠 Loyer ou mensualité de crédit immobilier" value={loyer} onChange={setLoyer} placeholder="800" suffix={cur}/><Inp id="ali" label="🛒 Alimentation et courses" value={alimentation} onChange={setAlimentation} placeholder="350" suffix={cur}/><Inp id="tra" label="🚗 Transports (essence, Navigo, assurance auto…)" value={transports} onChange={setTransports} placeholder="80" suffix={cur}/><Inp id="abo" label="📱 Abonnements (téléphone, streaming, internet…)" value={abonnements} onChange={setAbonnements} placeholder="60" suffix={cur}/><Inp id="ass" label="🛡️ Assurances et mutuelle" value={assurancesCh} onChange={setAssurancesCh} placeholder="50" suffix={cur}/><Inp id="loi" label="🎭 Loisirs et sorties" value={loisirs} onChange={setLoisirs} placeholder="150" suffix={cur}/><Inp id="cre" label="💳 Remboursements de crédits à la consommation" value={creditsConso} onChange={setCreditsConso} placeholder="0" suffix={cur}/><Inp id="aut" label="📦 Autres charges régulières" value={autresCharges} onChange={setAutresCharges} placeholder="50" suffix={cur}/><Inp id="scc" label="💳 Solde actuel de votre compte courant" value={soldeCourant} onChange={setSoldeCourant} placeholder="2 500" suffix={cur} tooltip="Permet de détecter l'argent qui dort sur votre compte courant et ne rapporte rien."/>{ch>0&&<div className={`rounded-xl p-4 mt-2 border ${(modeCouple?coupleDispo:dispo)>0?"bg-emerald-50 border-emerald-200":"bg-red-50 border-red-200"}`}><p className="font-bold text-xl" style={{color:(modeCouple?coupleDispo:dispo)>0?"#059669":"#dc2626"}}>{(modeCouple?coupleDispo:dispo)>0?`✅ Capacité d'épargne : ${fc(modeCouple?coupleDispo:dispo)}/mois`:`⚠️ Déficit mensuel : ${fc(Math.abs(modeCouple?coupleDispo:dispo))}`}</p></div>}</div>);

const rEpargne=()=>(<div><h2 className="text-xl font-bold mb-4">🛡️ Épargne de précaution</h2><p className="text-sm text-slate-500 mb-4">Avant d'investir en bourse, vous devez avoir un matelas de sécurité. C'est non négociable.</p><Sel id="ep" label="Avez-vous une épargne de précaution ?" value={epargnePrecaution} onChange={setEpargnePrecaution} tooltip="De l'argent facilement accessible (pas en bourse) pour faire face aux imprévus : panne, santé, chômage…" options={[{value:"",label:"Choisir"},{value:"oui",label:"✅ Oui, j'en ai une"},{value:"non",label:"❌ Non, pas encore"},{value:"partiel",label:"🔶 Un peu, mais pas assez"}]}/>{(epargnePrecaution==="oui"||epargnePrecaution==="partiel")&&<Inp id="me" label="Montant total sur vos livrets et comptes épargne" value={montantEpargne} onChange={setMontantEpargne} placeholder="5 000" suffix={cur} tooltip="Tout ce que vous avez sur Livret A, LDDS, ou comptes épargne. Pas ce qui est en bourse."/>}<Sel id="la" label={`Avez-vous un ${C.liv.n} ?`} value={aLivretA} onChange={setALivretA} tooltip={C.liv.tip} options={[{value:"",label:"Choisir"},{value:"oui",label:"✅ Oui"},{value:"non",label:"❌ Non"}]}/>{C.liv2&&<Sel id="ld" label={`Avez-vous un ${C.liv2.n} ?`} value={aLDDS} onChange={setALDDS} tooltip="Livret de Développement Durable et Solidaire : même taux que le Livret A (2,4%), plafond distinct de 12 000€, zéro impôt. C'est un deuxième Livret A." options={[{value:"",label:"Choisir"},{value:"oui",label:"✅ Oui"},{value:"non",label:"❌ Non"}]}/>}{moisEp>0&&<div className={`rounded-xl p-4 border mt-2 ${moisEp>=6?"bg-emerald-50 border-emerald-200":moisEp>=3?"bg-blue-50 border-blue-200":"bg-amber-50 border-amber-200"}`}><p className={`text-sm font-medium ${moisEp>=6?"text-emerald-800":moisEp>=3?"text-blue-800":"text-amber-800"}`}>{moisEp>=6?`✅ Excellent ! ${moisEp.toFixed(1)} mois de charges en réserve. Vous êtes prêt(e) à investir.`:moisEp>=3?`👍 ${moisEp.toFixed(1)} mois de charges. Vous pouvez commencer à investir doucement.`:`⚠️ Seulement ${moisEp.toFixed(1)} mois de charges. Renforcez d'abord votre épargne de précaution.`}</p></div>}</div>);

const rEnveloppes=()=>(<div><h2 className="text-xl font-bold mb-4">📦 Vos placements ({C.l})</h2><Sel id="pea" label={`Avez-vous un ${C.inv.n} ?`} value={aPEA} onChange={setAPEA} tooltip={C.inv.tip} options={[{value:"",label:"Choisir"},{value:"oui",label:"✅ Oui"},{value:"non",label:"❌ Non"},{value:"sais_pas",label:"🤷 Je ne sais pas ce que c'est"}]}/>{(aPEA==="non"||aPEA==="sais_pas")&&<div className="mb-4"><div className="bg-blue-50 border border-blue-200 rounded-xl p-4 mb-3 text-sm text-blue-800">💡 {aPEA==="sais_pas"?"Le PEA est un compte qui vous permet d'investir en bourse (via des ETF) avec un gros avantage fiscal après 5 ans : au lieu de payer 30% d'impôts sur vos gains, vous ne payez que 17,2%. Sur le long terme, ça représente des milliers d'euros économisés.":"Ouvrez-en un maintenant même avec 10€. Ce qui compte c'est de lancer le compteur des 5 ans !"}</div><BCards items={getBankRecos("pea").map(b=>({e:b.emoji,n:b.nom,f:b.why}))}/></div>}<Sel id="av" label={`Avez-vous une ${C.ass.n} ?`} value={aAV} onChange={setAAV} tooltip={C.ass.tip} options={[{value:"",label:"Choisir"},{value:"oui",label:"✅ Oui"},{value:"non",label:"❌ Non"}]}/>{aAV==="oui"&&<Inp id="avm" label={`Montant dans votre ${C.ass.n}`} value={avMontant} onChange={setAvMontant} placeholder="10 000" suffix={cur}/>}<Sel id="per" label={`Avez-vous un ${C.ret.n} ?`} value={aPER} onChange={setAPER} tooltip={C.ret.tip} options={[{value:"",label:"Choisir"},{value:"oui",label:"✅ Oui"},{value:"non",label:"❌ Non"}]}/>{aPER==="oui"&&<Inp id="perm" label={`Montant dans votre ${C.ret.n}`} value={perMontant} onChange={setPerMontant} placeholder="5 000" suffix={cur}/>}{aPER==="non"&&tmi>=30&&<div className="bg-violet-50 border border-violet-200 rounded-xl p-4 mb-4 text-sm text-violet-800"><strong>💡 Recommandé pour vous :</strong> Votre TMI est de {tmi}%. Chaque 1 000{cur} versé dans un {C.ret.n} vous économise {tmi*10}{cur} d'impôts immédiatement.</div>}</div>);

const rActifs=()=>(<div><h2 className="text-xl font-bold mb-4">💎 Vos autres actifs</h2><Sel id="cr" label="Avez-vous de la crypto-monnaie ?" value={aCrypto} onChange={setACrypto} tooltip="Bitcoin, Ethereum, et autres crypto-monnaies." options={[{value:"",label:"Choisir"},{value:"oui",label:"✅ Oui"},{value:"non",label:"❌ Non"}]}/>{aCrypto==="oui"&&<Inp id="crm" label="Valeur totale de vos crypto-monnaies" value={cryptoMontant} onChange={setCryptoMontant} placeholder="2 000" suffix={cur} tooltip="La valeur actuelle en euros/devise de toutes vos cryptos."/>}{(logement==="proprietaire"||logement==="proprio_fini")&&<Inp id="imm" label="🏡 Valeur estimée de votre bien immobilier" value={immoValeur} onChange={setImmoValeur} placeholder="250 000" suffix={cur} tooltip="La valeur actuelle de revente estimée de votre résidence principale ou bien locatif."/>}<Inp id="aa" label="📦 Autres actifs (or physique, objets de valeur, parts d'entreprise…)" value={autresActifs} onChange={setAutresActifs} placeholder="0" suffix={cur}/><div className="bg-blue-50 border border-blue-200 rounded-xl p-3 text-sm text-blue-800 mt-2">💡 Dans le dashboard, vous pourrez détailler chaque ETF, action ou crypto individuellement dans l'onglet <strong>Portefeuille</strong>.</div></div>);

const rDPEA=()=>(<div><h2 className="text-xl font-bold mb-4">📊 Détails de votre {C.inv.n}</h2><Inp id="pm" label="Montant total dans votre PEA" value={peaMontant} onChange={setPeaMontant} placeholder="3 000" suffix={cur}/><Sel id="pd" label="Depuis combien de temps est-il ouvert ?" value={peaDepuis} onChange={setPeaDepuis} tooltip="Très important ! Après 5 ans, votre taux d'imposition sur les gains passe de 30% à 17,2%. NE faites aucun retrait avant 5 ans." options={[{value:"",label:"Choisir"},{value:"moins1",label:"Moins d'1 an"},{value:"1a3",label:"1 à 3 ans"},{value:"3a5",label:"3 à 5 ans ⚠️ Bientôt mature"},{value:"plus5",label:"Plus de 5 ans ✅ Mature !"}]}/></div>);

const rRisque=()=>(<div><h2 className="text-xl font-bold mb-4">🎯 Votre profil de risque</h2><p className="text-slate-500 text-sm mb-4">Ces 3 questions définissent votre profil d'investisseur et la répartition recommandée de votre portefeuille.</p><Sel id="tol" label="Quelle est votre attitude face au risque ?" value={toleranceRisque} onChange={setToleranceRisque} options={[{value:"",label:"Choisir"},{value:"prudent",label:"🛡️ Prudent — je préfère peu de risque même si ça rapporte moins"},{value:"modere",label:"⚖️ Modéré — un peu de risque pour un meilleur rendement"},{value:"agressif",label:"🚀 Dynamique — rendement maximum, j'accepte les hauts et bas"}]}/><Sel id="hor" label="Dans combien de temps aurez-vous besoin de cet argent ?" value={horizon} onChange={setHorizon} tooltip="Plus l'horizon est long, plus vous pouvez prendre de risque : les marchés ont le temps de se remettre des baisses temporaires." options={[{value:"",label:"Choisir"},{value:"court",label:"📅 Moins de 5 ans"},{value:"moyen",label:"📆 5 à 10 ans"},{value:"long",label:"🗓️ Plus de 10 ans"}]}/><Sel id="rea" label="Si vos investissements perdaient 20% en un mois, que feriez-vous ?" value={reaction} onChange={setReaction} options={[{value:"",label:"Choisir"},{value:"vendre",label:"😰 Je vends tout pour limiter les pertes"},{value:"rien",label:"😐 Je ne touche à rien et j'attends"},{value:"acheter",label:"🤑 J'en profite pour acheter plus (c'est les soldes !)"}]}/></div>);

const rObjectifs=()=>(<div><h2 className="text-xl font-bold mb-2">🎯 Vos objectifs financiers</h2><p className="text-slate-500 text-sm mb-4">Sélectionnez vos projets. Les montants sont pré-remplis selon votre pays et ville.</p>
<div className="grid grid-cols-2 gap-2 mb-4">{GOAL_T.map(t=>{const sel=userGoals.find(g=>g.id===t.id);return(<button key={t.id} onClick={()=>toggleGoal(t)} className={`p-3 rounded-xl border-2 text-left ${sel?"border-blue-500 bg-blue-50":"border-slate-200"}`}><span className="text-2xl">{t.emoji}</span><p className="font-semibold text-xs mt-1">{t.nom}</p>{!sel&&pays&&<p className="text-xs text-slate-400">~{fc(smartDef(t.id,pays,villeType,nbEnfants))}</p>}</button>);})}</div>
{userGoals.map(g=>(<div key={g.id} className="bg-slate-50 rounded-xl p-4 mb-3 border"><p className="font-semibold mb-2">{g.emoji} {g.nom}</p>
<div className="grid grid-cols-2 gap-3"><Inp id={g.id+"c"} label="Montant cible" value={g.cible} onChange={v=>updGoal(g.id,"cible",v)} suffix={cur}/><Inp id={g.id+"a"} label="Année cible" value={g.annee} onChange={v=>updGoal(g.id,"annee",v)}/></div>
{g.id==="immo"&&<><Sel id={g.id+"loan"} label="Souhaitez-vous contracter un prêt immobilier ?" value={g.wantLoan||""} onChange={v=>updGoal(g.id,"wantLoan",v)} options={[{value:"",label:"Choisir"},{value:"oui",label:"✅ Oui, je prévois un prêt"},{value:"non",label:"❌ Non, achat comptant"}]}/>{g.wantLoan==="oui"&&<div className="grid grid-cols-2 gap-3"><Inp id={g.id+"lamt"} label="Montant à emprunter" value={g.loanAmount||""} onChange={v=>updGoal(g.id,"loanAmount",v)} suffix={cur}/><Inp id={g.id+"ldur"} label="Durée du prêt" value={g.loanDuration||"20"} onChange={v=>updGoal(g.id,"loanDuration",v)} suffix="ans"/></div>}</>}
{(()=>{const an=analyzeGoal(g);return(<div className={`mt-2 rounded-lg p-3 text-sm ${an.status==="on_track"||an.status==="atteint"?"bg-emerald-100 text-emerald-800":an.status==="tight"?"bg-amber-100 text-amber-800":"bg-red-100 text-red-800"}`}>{an.status==="atteint"?"🎉 Déjà atteint !":an.status==="on_track"?`✅ Réalisable ! Épargnez ${fc(an.mn)}/mois (vous pouvez en épargner ${fc(mi)}).`:an.status==="tight"?`⚠️ Serré : ${fc(an.mn)}/mois requis. Augmentez ou repoussez.`:`❌ Irréalisable en l'état : ${fc(an.mn)}/mois requis mais seulement ${fc(mi)} disponibles.`}</div>);})()}
</div>))}</div>);

const rResultats=()=>(<div><div className="text-center mb-5"><div className="text-5xl mb-2">🎉</div><h2 className="text-2xl font-bold">Votre plan personnalisé</h2></div><Card className="mb-4"><div className="grid grid-cols-2 gap-2 text-sm"><div className="bg-slate-50 rounded-lg p-3"><p className="text-slate-500">Patrimoine net</p><p className="font-bold text-lg">{fc(netWorth)}</p></div><div className="bg-slate-50 rounded-lg p-3"><p className="text-slate-500">Profil</p><p className={`font-bold text-lg ${profil.cl}`}>{profil.label}</p></div><div className="bg-slate-50 rounded-lg p-3"><p className="text-slate-500">À investir/mois</p><p className="font-bold text-lg text-emerald-600">{fc(mi)}</p></div><div className="bg-slate-50 rounded-lg p-3"><p className="text-slate-500">TMI ({C.l})</p><p className="font-bold text-lg">{tmi} %</p></div></div></Card><div className="text-center mt-6"><Btn onClick={goToDash}>📊 Ouvrir mon patrimoine →</Btn></div></div>);

const renderStep=()=>({intro:rIntro,profil:rProfil,banques:rBanques,revenus:rRevenus,charges:rCharges,epargne:rEpargne,enveloppes:rEnveloppes,actifs:rActifs,d_pea:rDPEA,risque:rRisque,objectifs:rObjectifs,resultats:rResultats}[cs]?.()||null);

// ===== DASHBOARD =====
const axis={fontSize:11,fill:DK.sub};
const KPI=({label,val,sub,col})=>(<DCard><p className="text-xs" style={{color:DK.sub}}>{label}</p><p className="text-lg font-bold mt-0.5" style={{color:col||DK.txt}}>{val}</p>{sub&&<p className="text-xs mt-0.5" style={{color:DK.sub}}>{sub}</p>}</DCard>);

const dPatrimoine=()=>(<div>
<DCard className="mb-4" style={{background:"linear-gradient(135deg,#141419,#1C1C24)"}}><p className="text-sm" style={{color:DK.sub}}>Patrimoine net total</p><p className="text-4xl font-black mt-1" style={{color:DK.txt}}>{fc(netWorth)}</p>{perf&&<div className="flex items-center gap-2 mt-2 flex-wrap"><span className="text-sm font-bold px-2 py-0.5 rounded-lg" style={{background:perf.diff>=0?"rgba(34,197,94,0.15)":"rgba(239,68,68,0.15)",color:perf.diff>=0?DK.grn:DK.red}}>{perf.diff>=0?"▲":"▼"} {fc(Math.abs(perf.diff))} ({perf.pct>=0?"+":""}{perf.pct.toFixed(1)} %)</span>{totalVersements>0&&<span className="text-xs" style={{color:DK.sub}}>dont {fc(perf.gains)} de plus-value réelle</span>}</div>}</DCard>
<div className="grid grid-cols-2 gap-3 mb-4"><KPI label="Taux d'épargne" val={savingsRate+" %"} sub={savingsRate>=20?"Excellent — vous construisez rapidement":savingsRate>=10?"Correct — continuez":savingsRate>0?"À améliorer":"Non calculé"} col={savingsRate>=20?DK.grn:savingsRate>=10?DK.blue:DK.amber}/><KPI label="Revenus passifs estimés" val={fc(passiveIncome)+"/mois"} sub="Dividendes, intérêts, loyers estimés"/></div>
{catData.length>0&&<DCard className="mb-4"><h3 className="font-bold mb-3" style={{color:DK.txt}}>Répartition de votre patrimoine</h3><div className="flex items-center gap-4 flex-wrap"><ResponsiveContainer width={150} height={150}><PieChart><Pie data={catData} dataKey="v" nameKey="name" cx="50%" cy="50%" outerRadius={62} innerRadius={40} paddingAngle={2} stroke="none">{catData.map((d,i)=><Cell key={i} fill={CATC[d.name]||CL[i]}/>)}</Pie></PieChart></ResponsiveContainer><div className="flex-1 space-y-2 min-w-[140px]">{catData.map((d,i)=>(<div key={i}><div className="flex justify-between text-sm"><span className="flex items-center gap-2" style={{color:DK.txt}}><span className="w-2.5 h-2.5 rounded-full" style={{background:CATC[d.name]||CL[i]}}/>{d.name}</span><span style={{color:DK.sub}}>{Math.round(d.v/netWorth*100)} %</span></div><p className="text-xs ml-4" style={{color:DK.sub}}>{fc(d.v)}</p></div>))}</div></div></DCard>}
{chartData.length>1&&<DCard className="mb-4"><h3 className="font-bold mb-3" style={{color:DK.txt}}>Évolution dans le temps</h3><ResponsiveContainer width="100%" height={200}><AreaChart data={chartData}><defs><linearGradient id="g1" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={DK.grn} stopOpacity={0.4}/><stop offset="100%" stopColor={DK.grn} stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke={DK.bd}/><XAxis dataKey="m" tick={axis}/><YAxis tick={axis} tickFormatter={v=>v>=1000?`${(v/1000).toFixed(0)}k`:v}/><RTooltip contentStyle={{background:DK.card2,border:`1px solid ${DK.bd}`,borderRadius:8,color:DK.txt}} formatter={v=>fc(v)}/><Area type="monotone" dataKey="Total" stroke={DK.grn} strokeWidth={2} fill="url(#g1)"/></AreaChart></ResponsiveContainer></DCard>}
<DCard><div className="flex justify-between items-center mb-3"><h3 className="font-bold" style={{color:DK.txt}}>Mes comptes</h3><button onClick={()=>setShowEF(!showEF)} className="text-xs font-semibold px-3 py-1.5 rounded-lg" style={{background:DK.grn,color:"#08080B"}}>{showEF?"✕ Fermer":"+ Mise à jour mensuelle"}</button></div>
{showEF&&<div className="rounded-xl p-3 mb-3" style={{background:DK.card2,border:`1px solid ${DK.bd}`}}><div className="grid grid-cols-2 gap-2"><DInp id="ed" label="Mois" value={newE.date} onChange={v=>setNewE({...newE,date:v})} type="month"/><DInp id="ecc" label="💳 Compte courant" value={newE.soldeCc} onChange={v=>setNewE({...newE,soldeCc:v})} suffix={cur}/><DInp id="ep2" label={`📊 ${C.inv.n}`} value={newE.pea} onChange={v=>setNewE({...newE,pea:v})} suffix={cur}/><DInp id="ea" label={`🛡️ ${C.ass.n}`} value={newE.av} onChange={v=>setNewE({...newE,av:v})} suffix={cur}/><DInp id="epr" label={`🏛️ ${C.ret.n}`} value={newE.per} onChange={v=>setNewE({...newE,per:v})} suffix={cur}/><DInp id="el" label="🏦 Livrets" value={newE.livrets} onChange={v=>setNewE({...newE,livrets:v})} suffix={cur}/><DInp id="ecr" label="₿ Crypto" value={newE.crypto} onChange={v=>setNewE({...newE,crypto:v})} suffix={cur}/><DInp id="eim" label="🏡 Immobilier" value={newE.immo} onChange={v=>setNewE({...newE,immo:v})} suffix={cur}/><DInp id="eau" label="📦 Autres" value={newE.autres} onChange={v=>setNewE({...newE,autres:v})} suffix={cur}/><DInp id="ev2" label="💰 Versements ce mois" value={newE.versement} onChange={v=>setNewE({...newE,versement:v})} suffix={cur}/></div><DInp id="en" label="📝 Notes (événement, dépense exceptionnelle…)" value={newE.notes} onChange={v=>setNewE({...newE,notes:v})} type="text" placeholder="Prime reçue, achat voiture…"/><div className="text-right"><button onClick={addEntry} className="text-sm font-semibold px-4 py-2 rounded-lg" style={{background:DK.grn,color:"#08080B"}}>💾 Enregistrer</button></div></div>}
<div className="space-y-2">{[{n:"💳 Compte courant",v:snap.cash},{n:"🏦 Livrets",v:snap.livrets},{n:`📊 ${C.inv.n}`,v:snap.pea},{n:`🛡️ ${C.ass.n}`,v:snap.av},{n:`🏛️ ${C.ret.n}`,v:snap.per},{n:"₿ Crypto",v:snap.crypto},{n:"🏡 Immobilier",v:snap.immo},{n:"📦 Autres",v:snap.autres}].filter(x=>x.v>0).map((x,i)=>(<div key={i} className="flex justify-between items-center py-2" style={{borderBottom:`1px solid ${DK.bd}`}}><span className="text-sm" style={{color:DK.txt}}>{x.n}</span><span className="text-sm font-bold" style={{color:DK.txt}}>{fc(x.v)}</span></div>))}</div></DCard>
</div>);

const dPortefeuille=()=>(<div>
<DCard className="mb-4" style={{background:"linear-gradient(135deg,#141419,#1C1C24)"}}><p className="text-sm" style={{color:DK.sub}}>Valeur du portefeuille titres</p><p className="text-3xl font-black mt-1" style={{color:DK.txt}}>{fc(posTotal)}</p>{posInvest>0&&<div className="flex items-center gap-2 mt-2 flex-wrap"><span className="text-sm font-bold px-2 py-0.5 rounded-lg" style={{background:(posTotal-posInvest)>=0?"rgba(34,197,94,0.15)":"rgba(239,68,68,0.15)",color:(posTotal-posInvest)>=0?DK.grn:DK.red}}>{(posTotal-posInvest)>=0?"▲":"▼"} {fc(Math.abs(posTotal-posInvest))} ({posInvest>0?((posTotal-posInvest)/posInvest*100).toFixed(1):0} %)</span><span className="text-xs" style={{color:DK.sub}}>investi : {fc(posInvest)}</span></div>}</DCard>
<DCard><div className="flex justify-between items-center mb-3"><div><h3 className="font-bold" style={{color:DK.txt}}>Mes positions</h3><p className="text-xs mt-0.5" style={{color:DK.sub}}>Cliquez sur ✏️ pour modifier le prix actuel ou la quantité</p></div><button onClick={()=>{setShowPF(!showPF);setEditPosIdx(null);}} className="text-xs font-semibold px-3 py-1.5 rounded-lg" style={{background:DK.grn,color:"#08080B"}}>{showPF?"✕":"+ Ajouter"}</button></div>
{showPF&&<div className="rounded-xl p-3 mb-3" style={{background:DK.card2,border:`1px solid ${DK.bd}`}}>
<DInp id="pn" label="Nom / Ticker (ex : Amundi MSCI World, Apple, Bitcoin…)" value={newP.nom} onChange={v=>setNewP({...newP,nom:v})} type="text" placeholder="Amundi MSCI World"/>
<div className="grid grid-cols-2 gap-2"><DSel id="pt" label="Type d'actif" value={newP.type} onChange={v=>setNewP({...newP,type:v})} options={[{value:"ETF",label:"ETF (fonds indiciel)"},{value:"Action",label:"Action individuelle"},{value:"Crypto",label:"Crypto-monnaie"},{value:"Obligation",label:"Obligation"},{value:"Autre",label:"Autre"}]}/><DSel id="pe" label="Enveloppe (où il est logé)" value={newP.enveloppe} onChange={v=>setNewP({...newP,enveloppe:v})} options={[{value:"PEA",label:C.inv.n},{value:"AV",label:C.ass.n},{value:"CTO",label:"Compte-titres (CTO)"},{value:"Crypto",label:"Wallet / Exchange crypto"}]}/></div>
<div className="grid grid-cols-3 gap-2"><DInp id="pq" label="Quantité (nb de parts)" value={newP.qte} onChange={v=>setNewP({...newP,qte:v})} placeholder="10"/><DInp id="ppru" label={`PRU (Prix de Revient Unitaire)`} value={newP.pru} onChange={v=>setNewP({...newP,pru:v})} placeholder="85" suffix={cur} /><DInp id="ppx" label="Prix actuel" value={newP.prix} onChange={v=>setNewP({...newP,prix:v})} placeholder="95" suffix={cur}/></div>
<p className="text-xs mb-2" style={{color:DK.sub}}>Le PRU est votre prix d'achat moyen. La plus-value = (Prix actuel - PRU) × Quantité.</p>
<div className="text-right"><button onClick={addPos} className="text-sm font-semibold px-4 py-2 rounded-lg" style={{background:DK.grn,color:"#08080B"}}>💾 Ajouter la position</button></div></div>}
{posCalc.length===0?<p className="text-sm py-4 text-center" style={{color:DK.sub}}>Aucune position. Ajoutez vos ETF, actions ou cryptos pour suivre leur performance.</p>:
<div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr style={{color:DK.sub}}><th className="text-left py-2">Actif</th><th className="text-center">Qté</th><th className="text-center">PRU</th><th className="text-center">Prix actuel</th><th className="text-center">Valeur</th><th className="text-center">+/- value</th><th className="text-center">Actions</th></tr></thead>
<tbody>{posCalc.map((p,i)=>editPosIdx===i?(
<tr key={i} style={{borderTop:`1px solid ${DK.bd}`,background:"rgba(59,130,246,0.08)"}}><td colSpan={7} className="py-2 px-1">
<div className="grid grid-cols-3 gap-2 mb-2"><DInp id={`eq${i}`} label="Quantité" value={editPos.qte} onChange={v=>setEditPos({...editPos,qte:v})}/><DInp id={`epru${i}`} label="PRU" value={editPos.pru} onChange={v=>setEditPos({...editPos,pru:v})} suffix={cur}/><DInp id={`epx${i}`} label="Prix actuel" value={editPos.prix} onChange={v=>setEditPos({...editPos,prix:v})} suffix={cur}/></div>
<div className="flex gap-2"><button onClick={saveEditPos} className="text-xs font-bold px-3 py-1.5 rounded-lg" style={{background:DK.grn,color:"#08080B"}}>✓ Sauvegarder</button><button onClick={()=>{setEditPosIdx(null);setEditPos(null);}} className="text-xs px-3 py-1.5 rounded-lg" style={{background:DK.card2,color:DK.sub}}>✕ Annuler</button></div>
</td></tr>):(
<tr key={i} style={{borderTop:`1px solid ${DK.bd}`,color:DK.txt}}>
<td className="py-2"><p className="font-bold">{p.nom}</p><p style={{color:DK.sub}}>{p.type} · {p.enveloppe}</p></td>
<td className="text-center">{p.qte}</td>
<td className="text-center">{fmt2(parseFloat(p.pru)||0)}</td>
<td className="text-center">{fmt2(parseFloat(p.prix)||0)}</td>
<td className="text-center font-bold">{fc(p.valeur)}</td>
<td className="text-center" style={{color:p.pv>=0?DK.grn:DK.red}}>{p.pv>=0?"+":""}{fmt(p.pv)}<br/><span style={{color:p.perf>=0?DK.grn:DK.red}}>{p.perf>=0?"+":""}{p.perf.toFixed(1)}%</span></td>
<td className="text-center"><button onClick={()=>{setEditPosIdx(i);setEditPos({...positions[i]});setShowPF(false);}} className="mr-1 px-2 py-1 rounded text-xs" style={{background:"rgba(59,130,246,0.15)",color:DK.blue}}>✏️</button><button onClick={()=>setPositions(ps=>ps.filter((_,j)=>j!==i))} className="px-2 py-1 rounded text-xs" style={{background:"rgba(239,68,68,0.15)",color:DK.red}}>✕</button></td>
</tr>))}</tbody></table></div>}
{posCalc.length>0&&<div className="mt-3 rounded-xl p-3" style={{background:"rgba(59,130,246,0.08)"}}><p className="text-xs" style={{color:DK.blue}}>💡 Pour mettre à jour les prix : cliquez sur ✏️ à droite de chaque ligne. Les prix ne se mettent pas à jour automatiquement (pas de connexion à des APIs de marché). Consultez Google Finance ou votre courtier pour les cours actuels.</p></div>}
</DCard>
</div>);

const dObj=()=>{const actions=getActions();const alerts=getAlerts();const immoGoal=userGoals.find(g=>g.id==="immo"&&g.wantLoan==="oui");return(<div>
<DCard className="mb-4" style={{background:"linear-gradient(135deg,#141419,#1C1C24)"}}><p className="text-sm" style={{color:DK.sub}}>Indépendance financière (règle des 4 %)</p><p className="text-2xl font-black" style={{color:DK.txt}}>{fc(fireNumber)}</p><p className="text-xs mb-2" style={{color:DK.sub}}>= 25 × vos charges annuelles. À ce niveau de patrimoine, vous pouvez vivre de vos investissements sans travailler.</p><div className="w-full h-2.5 rounded-full overflow-hidden" style={{background:DK.card2}}><div className="h-full rounded-full" style={{width:`${fireProgress}%`,background:DK.grn}}/></div><p className="text-xs mt-1" style={{color:DK.grn}}>{fireProgress} % atteint — patrimoine actuel : {fc(patFin)}</p></DCard>
<DCard className="mb-4"><h3 className="font-bold mb-3" style={{color:DK.txt}}>🎯 Mes objectifs</h3>{userGoals.length===0?<p className="text-sm" style={{color:DK.sub}}>Aucun objectif défini.</p>:userGoals.map(g=>{const an=analyzeGoal(g);const col=an.status==="on_track"||an.status==="atteint"?DK.grn:an.status==="tight"?DK.amber:DK.red;return(<div key={g.id} className="mb-4"><div className="flex justify-between text-sm mb-1"><span style={{color:DK.txt}}>{g.emoji} {g.nom}</span><span style={{color:DK.sub}}>{fc(patFin)} / {fc(parseFloat(g.cible)||0)}</span></div><div className="w-full h-2.5 rounded-full overflow-hidden" style={{background:DK.card2}}><div className="h-full rounded-full" style={{width:`${Math.min(100,an.prog)}%`,background:col}}/></div><p className="text-xs mt-1" style={{color:col}}>{an.status==="atteint"?"🎉 Atteint !":an.status==="on_track"?`✅ En bonne voie — ${fc(an.mn)}/mois requis (${an.yl} ans restants)`:an.status==="tight"?`⚠️ Serré — ${fc(an.mn)}/mois requis`:`❌ Irréalisable — ${fc(an.mn)}/mois requis`}</p></div>);})}</DCard>

{immoGoal&&<DCard className="mb-4" style={{border:`1px solid ${DK.amber}`}}><h3 className="font-bold mb-1" style={{color:DK.amber}}>🏠 Conseiller prêt immobilier</h3><p className="text-xs mb-3" style={{color:DK.sub}}>Vous prévoyez un prêt de {fc(parseFloat(immoGoal.loanAmount)||0)} sur {immoGoal.loanDuration||20} ans. Voici les meilleures options :</p>{(()=>{const lmt=parseFloat(immoGoal.loanAmount)||0;const dur=parseFloat(immoGoal.loanDuration)||20;const banks=banquesActuelles.includes("boursorama")?PRET_BANQUES:[...PRET_BANQUES.slice(0,1),...PRET_BANQUES.filter(b=>b.nom.toLowerCase().includes("bourso")===false)].slice(0,5);return banks.map((b,i)=>{const tx=(i===0?0.031:i===1?0.030:i===2?0.034:0.037);const mens=lmt>0&&tx>0?Math.round(lmt*(tx/12*Math.pow(1+tx/12,dur*12))/(Math.pow(1+tx/12,dur*12)-1)):0;return(<div key={i} className="rounded-xl p-3 mb-2" style={{background:DK.card2,border:`1px solid ${b.recommande?"rgba(245,158,11,0.4)":DK.bd}`}}><div className="flex items-center gap-2 mb-1"><span className="text-lg">{b.emoji}</span><span className="font-bold text-sm" style={{color:DK.txt}}>{b.nom}</span>{b.recommande&&<span className="text-xs font-bold px-2 py-0.5 rounded-full ml-auto" style={{background:"rgba(245,158,11,0.15)",color:DK.amber}}>⭐ Recommandé</span>}{banquesActuelles.includes("boursorama")&&b.nom.includes("Bourso")&&<span className="text-xs px-2 py-0.5 rounded-full ml-auto" style={{background:"rgba(34,197,94,0.15)",color:DK.grn}}>Déjà client ✓</span>}</div><p className="text-xs mb-1" style={{color:DK.txt}}>Taux estimé : <strong style={{color:DK.grn}}>{b.taux}</strong>{mens>0&&` — Mensualité estimée : ~${fc(mens)}/mois`}</p><p className="text-xs" style={{color:DK.sub}}>{b.why}</p></div>);})})()} <p className="text-xs mt-2 italic" style={{color:DK.sub}}>⚠️ Les taux sont indicatifs (juillet 2026, Banque de France : ~3,11% en moyenne). Votre taux réel dépend de votre profil. Consultez un courtier pour une simulation gratuite.</p></DCard>}

<DCard className="mb-4"><div className="flex items-center gap-2 mb-3"><h3 className="font-bold" style={{color:DK.txt}}>✅ Actions à faire</h3><span className="text-xs px-2 py-0.5 rounded-full" style={{background:"rgba(239,68,68,0.15)",color:DK.red}}>Rouge = Urgent</span><span className="text-xs px-2 py-0.5 rounded-full" style={{background:"rgba(245,158,11,0.15)",color:DK.amber}}>Orange = Haute priorité</span></div>
{actions.length===0?<p className="text-sm" style={{color:DK.grn}}>🎉 Tout est en place ! Continuez votre DCA mensuel.</p>:actions.map(a=>{const det=ACTION_DETAILS[a.id];const col=a.p==="critique"?DK.red:a.p==="haute"?DK.amber:DK.blue;const expanded=expandedActions[a.id];const recos=getBankRecos(a.id);return(<div key={a.id} className="mb-3 rounded-xl overflow-hidden" style={{border:`1px solid ${col}33`}}>
<div className="flex items-start gap-3 p-3" style={{background:col+"11"}}>
<button onClick={()=>setActionsDone(p=>({...p,[a.id]:!p[a.id]}))} className="mt-0.5 w-6 h-6 rounded border-2 flex-shrink-0 flex items-center justify-center" style={{borderColor:actionsDone[a.id]?DK.grn:col,background:actionsDone[a.id]?DK.grn:"transparent",color:"#08080B"}}>{actionsDone[a.id]&&"✓"}</button>
<div className="flex-1" style={actionsDone[a.id]?{opacity:0.4}:{}}>
<div className="flex items-center gap-2 flex-wrap"><span className="text-sm font-bold" style={{color:DK.txt}}>{det?.icon} {det?.titre||a.txt}</span><span className="text-xs font-bold px-2 py-0.5 rounded-full" style={{background:col+"22",color:col}}>{det?.priorite||a.p}</span></div>
<button onClick={()=>setExpandedActions(p=>({...p,[a.id]:!p[a.id]}))} className="text-xs mt-1" style={{color:col}}>{expanded?"▲ Masquer les détails":"▼ Voir pourquoi c'est important + où le faire"}</button></div></div>
{expanded&&!actionsDone[a.id]&&<div className="p-3" style={{background:DK.card2}}>
<div className="rounded-lg p-3 mb-3" style={{background:"rgba(0,0,0,0.3)"}}>
<p className="text-sm font-bold mb-1" style={{color:DK.txt}}>❓ Pourquoi c'est important ?</p>
<p className="text-sm" style={{color:DK.sub}}>{det?.pourquoi}</p>
{det?.plafond&&<p className="text-xs mt-2 font-semibold" style={{color:DK.amber}}>📊 Plafond : {det.plafond}</p>}
{det?.taux&&<p className="text-xs mt-1 font-semibold" style={{color:DK.grn}}>📈 Rendement : {det.taux}</p>}
</div>
{recos.length>0&&<div><p className="text-xs font-bold mb-2" style={{color:DK.txt}}>🏦 Où le faire ? Top {recos.length} recommandations{banquesActuelles.length>0?" (adaptées à vos banques actuelles)":""}:</p>{recos.map((b,i)=><div key={i} className="rounded-lg p-3 mb-2" style={{background:DK.card,border:`1px solid ${i===0?col+"55":DK.bd}`}}><div className="flex items-center gap-2 mb-1"><span>{b.emoji}</span><span className="font-bold text-sm" style={{color:DK.txt}}>{b.nom}</span>{i===0&&<span className="text-xs font-bold px-2 py-0.5 rounded-full ml-auto" style={{background:col+"22",color:col}}>⭐ Top choix</span>}{banquesActuelles.some(id=>b.forBanques.includes(id))&&<span className="text-xs px-2 py-0.5 rounded-full" style={{background:"rgba(34,197,94,0.15)",color:DK.grn}}>Déjà client ✓</span>}</div><p className="text-xs" style={{color:DK.sub}}>{b.why}</p></div>)}</div>}
</div>}
</div>);})}
</DCard>
{alerts.length>0&&<DCard>{alerts.map((a,i)=>{const c=a.t==="success"?DK.grn:a.t==="warning"?DK.amber:a.t==="danger"?DK.red:DK.blue;return(<div key={i} className="rounded-xl p-3 mb-2" style={{background:DK.card2,borderLeft:`3px solid ${c}`}}><p className="font-bold text-sm" style={{color:DK.txt}}>{a.icon} {a.titre}</p><p className="text-sm" style={{color:DK.sub}}>{a.txt}</p></div>);})}</DCard>}
</div>);};

const dInvest=()=>{const recos=getRecos();const{score,details}=getDiversScore();const dca=getDCASplit();const tax=getTaxComparison();const reb=getRebalance();const dormant=Math.max(0,snap.cash-ch*1.1);return(<div>
{dormant>500&&<DCard className="mb-4" style={{border:`1px solid ${DK.amber}`}}><h3 className="font-bold" style={{color:DK.amber}}>💤 Argent dormant détecté : {fc(dormant)}</h3><p className="text-sm" style={{color:DK.sub}}>Vous avez {fc(dormant)} sur votre compte courant qui ne rapportent rien. Placez-les sur votre {moisEp<6?C.liv.n:C.inv.n} dès aujourd'hui.</p></DCard>}
<DCard className="mb-4"><h3 className="font-bold mb-3" style={{color:DK.txt}}>📊 Score de diversification</h3><p className="text-xs mb-3" style={{color:DK.sub}}>Ce score mesure si vous avez les bonnes enveloppes en place. 100 = portefeuille parfaitement structuré.</p><div className="flex items-start gap-4"><Gauge score={score} size={90}/><div className="flex-1"><p className="font-bold" style={{color:DK.txt}}>{score>=70?"Bien diversifié ✅":score>=40?"Peut mieux faire 🔶":"À améliorer ❌"}</p><div className="grid grid-cols-2 gap-1 mt-2">{details.map((d,i)=>(<div key={i} className="text-xs px-2 py-1 rounded flex items-center gap-1" style={{background:d.ok?"rgba(34,197,94,0.12)":"rgba(239,68,68,0.1)",color:d.ok?DK.grn:DK.red}}>{d.ok?"✅":"❌"} {d.n}</div>))}</div></div></div></DCard>
{mi>0&&<DCard className="mb-4"><div className="flex items-center gap-2 mb-2"><h3 className="font-bold" style={{color:DK.txt}}>🔄 Répartiteur DCA</h3><button onClick={()=>setShowDCA(!showDCA)} className="text-xs px-2 py-1 rounded-lg" style={{background:DK.card2,color:DK.sub}}>{showDCA?"Masquer":"C'est quoi le DCA ?"}</button></div>{showDCA&&<div className="rounded-xl p-3 mb-3 text-sm" style={{background:"rgba(59,130,246,0.1)",color:DK.blue}}><strong>DCA = Dollar Cost Averaging (investissement régulier programmé)</strong><br/>Vous investissez le même montant chaque mois automatiquement. 📉 Quand la bourse baisse : vous achetez plus de parts (c'est les soldes !). 📈 Quand elle monte : vos parts existantes prennent de la valeur. Résultat : vous lissez votre prix d'achat et éliminez le stress du "timing". Cette stratégie bat 95% des investisseurs particuliers sur le long terme.</div>}<p className="text-sm mb-3" style={{color:DK.sub}}>Comment répartir vos <strong style={{color:DK.txt}}>{fc(mi)}/mois</strong> (via {C.inv.bk}) :</p>{dca.map((e,i)=>(<div key={i} className="flex justify-between items-start rounded-xl p-3 mb-2" style={{background:DK.card2}}><div><p className="font-bold text-sm" style={{color:DK.txt}}>{e.n}</p><p className="text-xs font-mono" style={{color:DK.sub}}>{e.isin}</p><p className="text-xs mt-1" style={{color:DK.sub}}>📝 {e.why} — Frais : {e.ter}/an</p></div><div className="text-right ml-3"><p className="text-xl font-bold" style={{color:DK.grn}}>{fc(e.montant)}</p><p className="text-xs" style={{color:DK.sub}}>{e.p} %</p></div></div>))}</DCard>}
{mi>0&&<DCard className="mb-4"><h3 className="font-bold mb-1" style={{color:DK.txt}}>💰 Économie fiscale : {C.tax.optim.n} vs {C.tax.std.n}</h3><p className="text-xs mb-3" style={{color:DK.sub}}>En investissant {fc(mi)}/mois à 7%/an, voici combien l'enveloppe fiscalement optimisée vous fait économiser :</p><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr style={{color:DK.sub}}><th className="text-left py-2">Horizon</th><th>Gains</th><th style={{color:DK.grn}}>{C.tax.optim.n} ({C.tax.optim.r}%)</th><th style={{color:DK.red}}>Standard ({C.tax.std.r}%)</th><th style={{color:DK.blue}}>Économie</th></tr></thead><tbody>{getTaxComparison().map((r,i)=>(<tr key={i} style={{borderTop:`1px solid ${DK.bd}`,color:DK.txt}}><td className="py-2">{r.y} ans</td><td className="text-center">{fmt(r.gains)}</td><td className="text-center" style={{color:DK.grn}}>{fmt(r.taxOptim)}</td><td className="text-center" style={{color:DK.red}}>{fmt(r.taxStd)}</td><td className="text-center font-bold" style={{color:DK.blue}}>{fmt(r.saved)}</td></tr>))}</tbody></table></div></DCard>}
<DCard className="mb-4"><h3 className="font-bold mb-3" style={{color:DK.txt}}>⚖️ Signaux de rééquilibrage</h3><p className="text-xs mb-3" style={{color:DK.sub}}>Comparaison de votre allocation actuelle vs la cible recommandée pour un profil {profil.label} :</p>{getRebalance().map((s,i)=>{const c=s.sev==="success"?DK.grn:s.sev==="warning"?DK.amber:DK.blue;return(<div key={i} className="rounded-xl p-3 mb-2" style={{background:DK.card2,borderLeft:`3px solid ${c}`}}><p className="font-bold text-sm" style={{color:DK.txt}}>{s.icon} {s.msg}</p><p className="text-sm mt-1" style={{color:DK.txt}}>👉 {s.action}</p><p className="text-xs mt-1" style={{color:DK.sub}}>{s.det}</p></div>);})}</DCard>
{recos.map((tier,ti)=>(<DCard key={ti} className="mb-4"><h3 className="font-bold mb-2" style={{color:DK.txt}}>{tier.tier}</h3>{tier.items.map((item,ii)=>(<div key={ii} className="rounded-xl p-3 mb-2" style={{background:DK.card2,border:`1px solid ${item.has?DK.grn:DK.bd}`}}><div className="flex items-center gap-2"><span className="font-bold text-sm" style={{color:DK.txt}}>{item.nom}</span><span className="text-xs ml-auto" style={{color:item.has?DK.grn:DK.sub}}>{item.has?"✅ Actif":"À ouvrir"}</span></div><p className="text-sm" style={{color:DK.sub}}>{item.desc}</p><p className="text-xs mt-1" style={{color:DK.sub}}>📈 Rendement estimé : {item.rdt} · Niveau de risque : {item.risque}</p></div>))}</DCard>))}
</div>);};

const dBP=()=>{const data=genBP();const bpA=getBPAlerts(data);return(<div>
<DCard className="mb-4"><h3 className="font-bold mb-3" style={{color:DK.txt}}>⚙️ Hypothèses de croissance</h3><p className="text-xs mb-3" style={{color:DK.sub}}>Personne ne peut prédire l'avenir. Choisissez un scénario ou ajustez manuellement. Ces hypothèses permettent de simuler votre trajectoire patrimoniale.</p><div className="grid grid-cols-3 gap-2 mb-3">{Object.entries(SCEN).map(([k,s])=>(<button key={k} onClick={()=>applyScenario(k)} className="p-2.5 rounded-xl text-center text-sm font-bold" style={{background:bpRetAct===s.rA?"rgba(59,130,246,0.15)":DK.card2,border:`1px solid ${bpRetAct===s.rA?DK.blue:DK.bd}`,color:DK.txt}}>{s.l}</button>))}</div><div className="grid grid-cols-3 gap-2"><DInp id="sg" label="Croissance salaire/an" value={bpSalG} onChange={setBpSalG} suffix="%" /><DInp id="inf" label="Inflation/an" value={bpInfl} onChange={setBpInfl} suffix="%"/><DInp id="ra" label="Rendement actions/an" value={bpRetAct} onChange={setBpRetAct} suffix="%"/></div></DCard>
{bpA.length>0&&<DCard className="mb-4"><h3 className="font-bold mb-3" style={{color:DK.txt}}>⚠️ Analyse de faisabilité de vos objectifs</h3>{bpA.map((a,i)=>{const c=a.type==="danger"?DK.red:DK.grn;return(<div key={i} className="rounded-xl p-3 mb-2" style={{background:DK.card2,borderLeft:`3px solid ${c}`}}><p className="font-bold text-sm" style={{color:DK.txt}}>{a.emoji} {a.nom}</p><p className="text-sm" style={{color:DK.sub}}>{a.msg}</p>{a.conseil&&<p className="text-sm italic mt-1" style={{color:DK.sub}}>💡 {a.conseil}</p>}</div>);})}</DCard>}
<DCard className="mb-4"><div className="flex justify-between mb-3"><h3 className="font-bold" style={{color:DK.txt}}>📅 Événements de vie</h3><button onClick={()=>setShowEvF(!showEvF)} className="text-xs px-3 py-1 rounded-lg" style={{background:DK.card2,color:DK.sub}}>{showEvF?"✕":"+ Ajouter"}</button></div>{showEvF&&<div className="rounded-xl p-3 mb-3" style={{background:DK.card2}}><div className="grid grid-cols-3 gap-2"><DInp id="evn" label="Événement" value={newEv.nom} onChange={v=>setNewEv({...newEv,nom:v})} type="text"/><DInp id="evy" label="Dans X années" value={newEv.annee} onChange={v=>setNewEv({...newEv,annee:v})}/><DInp id="evc" label="Coût" value={newEv.cout} onChange={v=>setNewEv({...newEv,cout:v})} suffix={cur}/></div><div className="text-right"><button onClick={()=>{if(newEv.nom){setBpEvents(p=>[...p,newEv]);setNewEv({nom:"",annee:"",cout:""});setShowEvF(false);}}} className="text-sm font-semibold px-4 py-2 rounded-lg" style={{background:DK.blue,color:"#fff"}}>OK</button></div></div>}{bpEvents.map((e,i)=>(<div key={i} className="flex justify-between text-sm py-2" style={{borderBottom:`1px solid ${DK.bd}`,color:DK.txt}}><span>Année {e.annee} : {e.nom}</span><span style={{color:DK.red}}>{fc(parseFloat(e.cout)||0)} <button onClick={()=>setBpEvents(p=>p.filter((_,j)=>j!==i))} style={{color:DK.sub}}>✕</button></span></div>))}</DCard>
<DCard className="mb-4"><h3 className="font-bold mb-3" style={{color:DK.txt}}>📊 Trajectoire patrimoniale sur 20 ans</h3><ResponsiveContainer width="100%" height={230}><AreaChart data={data}><CartesianGrid strokeDasharray="3 3" stroke={DK.bd}/><XAxis dataKey="age" tick={axis} label={{value:"Âge",position:"insideBottomRight",fontSize:11,fill:DK.sub}}/><YAxis tick={axis} tickFormatter={v=>v>=1e6?`${(v/1e6).toFixed(1)}M`:v>=1000?`${(v/1000).toFixed(0)}k`:v}/><RTooltip contentStyle={{background:DK.card2,border:`1px solid ${DK.bd}`,borderRadius:8,color:DK.txt}} formatter={v=>fc(v)}/><Legend wrapperStyle={{fontSize:11,color:DK.sub}}/><Area type="monotone" dataKey="pea" stackId="1" fill="#3b82f6" stroke="#3b82f6" name={C.inv.n}/><Area type="monotone" dataKey="av" stackId="1" fill="#22c55e" stroke="#22c55e" name="Assurance"/><Area type="monotone" dataKey="liv" stackId="1" fill="#f59e0b" stroke="#f59e0b" name="Livrets"/></AreaChart></ResponsiveContainer></DCard>
<DCard><h3 className="font-bold mb-3" style={{color:DK.txt}}>📋 Détail année par année</h3><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr style={{color:DK.sub}}><th className="text-left py-2">An</th><th>Âge</th><th>Total nominal</th><th>Valeur réelle (inflation déduite)</th></tr></thead><tbody>{data.map((r,i)=>(<tr key={i} style={{borderTop:`1px solid ${DK.bd}`,color:DK.txt,background:r.ev?"rgba(245,158,11,0.08)":"transparent"}}><td className="py-1.5">{r.y}</td><td className="text-center">{r.age}</td><td className="text-center font-bold">{fmt(r.total)}</td><td className="text-center" style={{color:DK.sub}}>{fmt(r.reel)}</td></tr>))}</tbody></table></div><p className="text-xs italic mt-2" style={{color:DK.sub}}>⚠️ Projection indicative. Les rendements réels peuvent varier significativement.</p></DCard>
</div>);};

const dTools=()=>(<div><div className="flex gap-1 mb-4 rounded-xl p-1" style={{background:DK.card2}}>{[["acheter","🏠 Acheter/Louer"],["credits","💳 Crédits"],["couple","👫 Couple"]].map(([k,l])=>(<button key={k} onClick={()=>setToolTab(k)} className="flex-1 py-2 text-xs font-semibold rounded-lg" style={{background:toolTab===k?DK.card:"transparent",color:toolTab===k?DK.txt:DK.sub}}>{l}</button>))}</div>
{toolTab==="acheter"&&<div><DCard className="mb-4"><h3 className="font-bold mb-3" style={{color:DK.txt}}>🏠 Simulateur Acheter vs Louer</h3><p className="text-xs mb-3" style={{color:DK.sub}}>Comparez le coût total d'un achat avec votre situation de locataire sur le long terme.</p><div className="grid grid-cols-2 gap-2"><DInp id="bp" label="Prix du bien" value={bienPrix} onChange={setBienPrix} placeholder="250 000" suffix={cur}/><DInp id="app" label="Apport personnel" value={apport} onChange={setApport} placeholder="50 000" suffix={cur}/><DInp id="tc" label="Taux crédit estimé" value={tauxCr} onChange={setTauxCr} suffix="%"/><DInp id="dc" label="Durée du crédit" value={dureeCr} onChange={setDureeCr} suffix="ans"/><DInp id="loa" label="Votre loyer actuel" value={loyerAct} onChange={setLoyerAct} placeholder="800" suffix={cur+"/m"}/><DInp id="cop" label="Charges copropriété" value={chargesCo} onChange={setChargesCo} placeholder="150" suffix={cur+"/m"}/><DInp id="tf" label="Taxe foncière" value={taxeF} onChange={setTaxeF} placeholder="1200" suffix={cur+"/an"}/></div></DCard>{(()=>{const p=parseFloat(bienPrix)||0,a=parseFloat(apport)||0,tx=(parseFloat(tauxCr)||0)/100/12,dur=(parseFloat(dureeCr)||25)*12,lo=parseFloat(loyerAct)||0,co=parseFloat(chargesCo)||0,tf=(parseFloat(taxeF)||0)/12;if(!p||!tx)return<p className="text-sm text-center" style={{color:DK.sub}}>Remplissez les champs pour voir le résultat.</p>;const empr=p-a;const mens=empr*(tx*Math.pow(1+tx,dur))/(Math.pow(1+tx,dur)-1);const cp=Math.round(mens)+co+Math.round(tf);const diff=cp-lo;const inter=Math.round(mens*dur-empr);const pm=lo>0?Math.round((a+inter)/(lo*12)):0;return<DCard><h3 className="font-bold mb-3" style={{color:DK.txt}}>📊 Résultat</h3><div className="grid grid-cols-2 gap-2 mb-3">{[["Mensualité crédit",fc(mens),DK.blue],["Coût total proprio/m",fc(cp),DK.amber],["vs votre loyer",(diff>0?"+":"")+fc(diff),diff>0?DK.red:DK.grn],["Point mort estimé","~"+pm+" ans",DK.txt]].map((x,i)=>(<div key={i} className="rounded-xl p-3 text-center" style={{background:DK.card2}}><p className="text-xs" style={{color:DK.sub}}>{x[0]}</p><p className="text-base font-bold" style={{color:x[2]}}>{x[1]}</p></div>))}</div><div className="rounded-xl p-3" style={{background:"rgba(59,130,246,0.1)"}}><p className="text-sm" style={{color:DK.blue}}>{pm<=5?"🟢 Achat très rentable ! Le point mort est rapide.":pm<=10?"🟡 Rentable si vous restez au moins "+pm+" ans.":"🔴 Long terme requis ("+pm+" ans). Vérifiez si vous comptez rester."}</p></div></DCard>;})()} </div>}
{toolTab==="credits"&&<div><DCard className="mb-4"><h3 className="font-bold mb-3" style={{color:DK.txt}}>💳 Optimiseur de remboursement</h3><p className="text-xs mb-3" style={{color:DK.sub}}>Ajoutez vos crédits en cours. L'outil vous dira dans quel ordre les rembourser pour minimiser le coût total.</p><button onClick={()=>setShowCF(!showCF)} className="text-xs font-semibold px-4 py-2 rounded-lg mb-3" style={{background:DK.blue,color:"#fff"}}>{showCF?"✕ Fermer":"+ Ajouter un crédit"}</button>{showCF&&<div className="rounded-xl p-3 mb-3" style={{background:DK.card2}}><div className="grid grid-cols-2 gap-2"><DInp id="cn" label="Nom du crédit" value={newCr.nom} onChange={v=>setNewCr({...newCr,nom:v})} type="text" placeholder="Crédit auto"/><DInp id="crr" label="Capital restant" value={newCr.restant} onChange={v=>setNewCr({...newCr,restant:v})} suffix={cur}/><DInp id="ct" label="Taux d'intérêt" value={newCr.taux} onChange={v=>setNewCr({...newCr,taux:v})} suffix="%"/><DInp id="cm" label="Mensualité" value={newCr.mensualite} onChange={v=>setNewCr({...newCr,mensualite:v})} suffix={cur}/></div><div className="text-right"><button onClick={()=>{if(newCr.nom){setCredits(p=>[...p,newCr]);setNewCr({nom:"",restant:"",taux:"",mensualite:""});setShowCF(false);}}} className="text-sm font-semibold px-4 py-2 rounded-lg" style={{background:DK.blue,color:"#fff"}}>OK</button></div></div>}{credits.map((c,i)=>(<div key={i} className="flex justify-between py-2" style={{borderBottom:`1px solid ${DK.bd}`}}><div><p className="font-bold text-sm" style={{color:DK.txt}}>{c.nom}</p><p className="text-xs" style={{color:DK.sub}}>{fc(parseFloat(c.restant)||0)} à {c.taux} %/an — {fc(parseFloat(c.mensualite)||0)}/mois</p></div><button onClick={()=>setCredits(p=>p.filter((_,j)=>j!==i))} style={{color:DK.sub}}>✕</button></div>))}</DCard>{credits.length>0&&(()=>{const avg=credits.reduce((s,c)=>s+(parseFloat(c.taux)||0),0)/credits.length;const sorted=avg>5?[...credits].sort((a,b)=>(parseFloat(b.taux)||0)-(parseFloat(a.taux)||0)):[...credits].sort((a,b)=>(parseFloat(a.restant)||0)-(parseFloat(b.restant)||0));return<DCard><h3 className="font-bold mb-2" style={{color:DK.txt}}>🎯 Stratégie recommandée : {avg>5?"🔥 Avalanche":"❄️ Boule de Neige"}</h3><p className="text-sm mb-3" style={{color:DK.sub}}>{avg>5?"Taux moyens élevés : remboursez d'abord le crédit au taux le plus élevé. Vous économisez le plus d'intérêts.":"Taux bas : remboursez d'abord le plus petit solde. Victoire rapide = motivation. La différence de coût avec l'avalanche est minime."}</p><ol className="list-decimal ml-5 text-sm" style={{color:DK.txt}}>{sorted.map((c,i)=>(<li key={i} className="mb-2"><strong>{c.nom}</strong> — Restant : {fc(parseFloat(c.restant)||0)} à {c.taux} %</li>))}</ol></DCard>;})()}</div>}
{toolTab==="couple"&&<DCard>{!modeCouple?<div className="text-center py-6"><p style={{color:DK.sub}} className="mb-3">Le mode couple n'est pas activé dans votre profil.</p><button onClick={()=>{setPage("q");setStep(steps.indexOf("profil"));}} className="text-sm font-semibold px-4 py-2 rounded-lg" style={{background:DK.blue,color:"#fff"}}>Aller au profil →</button></div>:<div><h3 className="font-bold mb-3" style={{color:DK.txt}}>👫 Finances du couple</h3><div className="grid grid-cols-2 gap-2 mb-3">{[["Vous",fc(rev)+"/mois"],["Conjoint(e)",fc(parseFloat(p2Rev)||0)+"/mois"]].map((x,i)=>(<div key={i} className="rounded-xl p-3" style={{background:DK.card2}}><p className="text-xs" style={{color:DK.sub}}>{x[0]}</p><p className="font-bold" style={{color:DK.txt}}>{x[1]}</p></div>))}<div className="rounded-xl p-3 col-span-2" style={{background:"rgba(34,197,94,0.12)"}}><p className="text-xs" style={{color:DK.sub}}>Revenus couple</p><p className="text-base font-bold" style={{color:DK.grn}}>{fc(coupleRev)}/mois → {fc(coupleDispo)} disponibles pour épargne</p></div></div><div className="rounded-xl p-3" style={{background:DK.card2}}><p className="font-bold text-sm mb-2" style={{color:DK.txt}}>💡 Conseils spécifiques au couple</p><ul className="text-sm space-y-1.5" style={{color:DK.sub}}><li>📊 Capacité DCA commune : {fc(mi)}/mois</li><li>🏦 Chacun son {C.inv.n} : le PEA n'est pas transférable, chaque personne doit avoir le sien</li><li>🛡️ Épargne de précaution commune cible : {fc(coupleCh*6)} (6 mois de charges)</li>{tmi>=30&&<li>🏛️ {C.ret.n} recommandé pour le membre du couple le plus imposé (TMI {tmi} %)</li>}</ul></div></div>}</DCard>}
</div>);

const TABS=[["patrimoine","💰","Patrimoine"],["portefeuille","📈","Portefeuille"],["objectifs","🎯","Objectifs"],["invest","💡","Conseils"],["bp","📊","Projection"],["tools","🧰","Outils"]];

if(page==="q")return(<div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-50"><header className="bg-white border-b border-slate-200 sticky top-0 z-40"><div className="max-w-2xl mx-auto flex items-center justify-between px-4 py-2"><h1 className="text-lg font-black">💸 Nheb Barcha Flous</h1>{done&&<button onClick={()=>setPage("d")} className="text-xs px-3 py-1.5 rounded-lg font-semibold bg-blue-600 text-white">📊 Dashboard</button>}</div></header><div className="max-w-2xl mx-auto px-4 py-6">{cs!=="intro"&&cs!=="resultats"&&<Prog c={step} t={steps.length-1}/>}<Card>{renderStep()}</Card>{cs!=="intro"&&cs!=="resultats"&&<div className="flex justify-between mt-6"><Btn onClick={prev} secondary>← Retour</Btn><Btn onClick={next}>Suivant →</Btn></div>}</div></div>);

return(<div className="min-h-screen flex" style={{background:DK.bg}}>
<aside className="flex flex-col shrink-0" style={{width:170,background:DK.card,borderRight:`1px solid ${DK.bd}`,position:"sticky",top:0,height:"100vh",overflowY:"auto"}}>
<div className="px-4 py-4" style={{borderBottom:`1px solid ${DK.bd}`}}><h1 className="text-sm font-black" style={{color:DK.txt}}>💸 Nheb Barcha</h1><p className="text-xs" style={{color:DK.sub}}>{C.l}</p>{banquesActuelles.length>0&&<p className="text-xs mt-1" style={{color:DK.sub}}>🏦 {banquesActuelles.length} banque{banquesActuelles.length>1?"s":""}</p>}</div>
<nav className="flex-1 p-2 space-y-1">{TABS.map(([k,ic,l])=>(<button key={k} onClick={()=>setDashTab(k)} className="w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-semibold transition" style={{background:dashTab===k?"rgba(34,197,94,0.15)":"transparent",color:dashTab===k?DK.grn:DK.sub}}><span>{ic}</span>{l}</button>))}</nav>
<div className="p-2" style={{borderTop:`1px solid ${DK.bd}`}}><button onClick={()=>{setPage("q");setStep(steps.indexOf("resultats"));}} className="w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-semibold" style={{color:DK.sub}}><span>📋</span>Questionnaire</button></div>
</aside>
<main className="flex-1 overflow-x-hidden"><div className="max-w-3xl mx-auto px-4 py-5"><h2 className="text-2xl font-black mb-5" style={{color:DK.txt}}>{TABS.find(t=>t[0]===dashTab)?.[2]}</h2>{dashTab==="patrimoine"&&dPatrimoine()}{dashTab==="portefeuille"&&dPortefeuille()}{dashTab==="objectifs"&&dObj()}{dashTab==="invest"&&dInvest()}{dashTab==="bp"&&dBP()}{dashTab==="tools"&&dTools()}</div></main>
</div>);
}

