import { useState, useEffect } from "react";
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip as RTooltip, Legend, ResponsiveContainer, PieChart, Pie, Cell } from "recharts";

const fmt=n=>Math.round(n||0).toLocaleString("fr-FR");
const fmt2=n=>(n||0).toLocaleString("fr-FR",{minimumFractionDigits:2,maximumFractionDigits:2});
const DK={bg:"#08080B",card:"#141419",card2:"#1C1C24",bd:"#26262F",txt:"#F5F5F7",sub:"#8A8A94",grn:"#22C55E",red:"#EF4444",blue:"#3b82f6"};
const CL=["#3b82f6","#22c55e","#8b5cf6","#f59e0b","#ec4899","#06b6d4"];
const CATC={Liquidités:"#3b82f6",Investissements:"#22c55e",Crypto:"#8b5cf6",Immobilier:"#f59e0b",Autres:"#ec4899"};

const CO={
 france:{l:"🇫🇷 France",cur:"€",tmi:[[11294,0],[28797,11],[82341,30],[177106,41],[1e12,45]],parts:true,
   inv:{n:"PEA",tip:"Investir en bourse ; gains taxés à 17,2 % après 5 ans (au lieu de 30 %).",bk:"Bourse Direct, Boursorama"},
   ass:{n:"Assurance-vie",tip:"Enveloppe souple, avantage fiscal après 8 ans.",bk:"Linxea Avenir 2"},
   ret:{n:"PER",tip:"Versements déductibles des impôts, bloqué jusqu'à la retraite.",bk:"Linxea Spirit PER"},
   liv:{n:"Livret A",rate:2.4,tip:"Épargne réglementée 2,4 %, 0 impôt, plafond 22 950 €."},liv2:{n:"LDDS"},
   tax:{optim:{n:"PEA",r:17.2},std:{n:"Compte-titres",r:30}},def:{immo:40000,mar:15000,etu:15000},sav:"Livret A + LDDS"},
 tunisie:{l:"🇹🇳 Tunisie",cur:"DT",tmi:[[5000,0],[20000,26],[30000,28],[50000,32],[1e12,35]],parts:false,
   inv:{n:"Compte Épargne en Actions (CEA)",tip:"Enveloppe boursière tunisienne avec déduction fiscale (BVMT).",bk:"Tunisie Valeurs, MAC SA, BIAT Capital"},
   ass:{n:"Assurance-vie",tip:"Contrats en dinars, avantage fiscal sur les versements.",bk:"Assurances BIAT, GAT, Maghrebia"},
   ret:{n:"Contrat retraite",tip:"Épargne retraite complémentaire déductible.",bk:"GAT, Maghrebia Vie"},
   liv:{n:"Compte Épargne",rate:5,tip:"Compte épargne bancaire tunisien, ~5 %/an, capital garanti."},liv2:null,
   tax:{optim:{n:"CEA",r:10},std:{n:"Compte-titres",r:20}},def:{immo:50000,mar:30000,etu:15000},sav:"Compte Épargne"},
 malte:{l:"🇲🇹 Malte",cur:"€",tmi:[[9100,0],[14500,15],[19500,25],[60000,25],[1e12,35]],parts:false,
   inv:{n:"Compte-titres (broker)",tip:"Investir en ETF via un courtier. Malte : fiscalité avantageuse sur le long terme.",bk:"Interactive Brokers, Trading 212, DEGIRO"},
   ass:{n:"Assurance-vie",tip:"Contrats d'investissement, transmission facilitée.",bk:"MAPFRE MSV Life"},
   ret:{n:"Pension privée (3e pilier)",tip:"Crédit d'impôt jusqu'à 750 €/an sur les versements.",bk:"APS, HSBC Malta"},
   liv:{n:"Compte épargne",rate:2,tip:"Épargne bancaire, ~2 %/an, capital garanti."},liv2:null,
   tax:{optim:{n:"Détention longue",r:0},std:{n:"Compte imposé",r:15}},def:{immo:45000,mar:14000,etu:12000},sav:"Compte épargne"},
 canada:{l:"🇨🇦 Canada",cur:"$",tmi:[[55000,20],[110000,30],[165000,38],[235000,45],[1e12,50]],parts:false,
   inv:{n:"CELI (investissement)",tip:"Compte d'Épargne Libre d'Impôt : gains 100 % exonérés à vie !",bk:"Wealthsimple, Questrade, Disnat"},
   ass:{n:"Compte non-enregistré",tip:"Compte-titres classique : 50 % des gains imposables.",bk:"Wealthsimple, Questrade"},
   ret:{n:"REER",tip:"Régime retraite : versements déductibles des impôts.",bk:"Wealthsimple, Questrade"},
   liv:{n:"CELI liquidités / HISA",rate:4,tip:"Compte d'épargne à intérêt élevé, ~4 %/an."},liv2:null,
   tax:{optim:{n:"CELI",r:0},std:{n:"Compte non-enregistré",r:25}},def:{immo:60000,mar:25000,etu:30000},sav:"CELI liquidités"},
 allemagne:{l:"🇩🇪 Allemagne",cur:"€",tmi:[[11604,0],[17000,14],[66761,24],[277825,42],[1e12,45]],parts:false,
   inv:{n:"ETF-Depot (Sparplan)",tip:"Plan d'investissement ETF. Abattement 1 000 €/an (Sparerpauschbetrag).",bk:"Trade Republic, Scalable Capital, comdirect"},
   ass:{n:"Depot secondaire",tip:"Compte-titres classique pour actions individuelles.",bk:"Trade Republic, comdirect"},
   ret:{n:"Rürup / Riester",tip:"Épargne retraite déductible fiscalement.",bk:"Allianz, Cosmos Direkt"},
   liv:{n:"Tagesgeld",rate:3,tip:"Compte épargne à vue, ~3 %/an, capital garanti."},liv2:null,
   tax:{optim:{n:"ETF actions (Teilfreistellung)",r:18.5},std:{n:"Compte standard",r:26.4}},def:{immo:40000,mar:14000,etu:13000},sav:"Tagesgeld"},
};
const CITY={capitale:{l:"🏙️ Capitale",m:1.5},grande:{l:"🏢 Grande ville",m:1},petite:{l:"🏘️ Petite ville",m:0.7}};
const GOAL_T=[{id:"immo",emoji:"🏠",nom:"Achat immobilier"},{id:"mariage",emoji:"💍",nom:"Mariage"},{id:"fire",emoji:"🏖️",nom:"Retraite anticipée"},{id:"etudes",emoji:"🎓",nom:"Études enfants"},{id:"voyage",emoji:"✈️",nom:"Voyage / projet"},{id:"capital",emoji:"💰",nom:"Capital cible"},{id:"vehicule",emoji:"🚗",nom:"Véhicule"}];
const SCEN={pessimiste:{sG:"1",inf:"3",rA:"4",rV:"2",rL:"1.5",l:"😟 Pessimiste"},base:{sG:"2",inf:"2",rA:"7",rV:"4",rL:"2.4",l:"📊 Base"},optimiste:{sG:"3",inf:"1.5",rA:"10",rV:"6",rL:"3",l:"🚀 Optimiste"}};
const IDEAL={Dynamique:[{n:"Actions",p:65,c:"#3b82f6"},{n:"Assurance",p:15,c:"#22c55e"},{n:"Livrets",p:15,c:"#f59e0b"},{n:"Crypto",p:5,c:"#8b5cf6"}],"Équilibré":[{n:"Actions",p:50,c:"#3b82f6"},{n:"Assurance",p:25,c:"#22c55e"},{n:"Livrets",p:20,c:"#f59e0b"},{n:"Crypto",p:5,c:"#8b5cf6"}],Prudent:[{n:"Actions",p:30,c:"#3b82f6"},{n:"Assurance",p:30,c:"#22c55e"},{n:"Livrets",p:35,c:"#f59e0b"},{n:"Or",p:5,c:"#f59e0b"}]};
const PARTS_TIP="Parts fiscales (France) : seul = 1, couple = 2, chaque enfant = 0,5 (1 dès le 3e). Plus de parts = TMI plus basse.";
const smartDef=(id,pays,ville,enf)=>{const c=CO[pays]||CO.france;const m=CITY[ville]?.m||1;const e=parseInt(enf)||1;switch(id){case"immo":return Math.round(c.def.immo*m);case"mariage":return Math.round(c.def.mar*m);case"etudes":return Math.round(c.def.etu*m*e);case"fire":return 500000;case"capital":return 100000;case"voyage":return 5000;case"vehicule":return 15000;default:return 10000;}};

function Tip({text}){const[o,setO]=useState(false);return(<span className="relative inline-block ml-1"><button onClick={()=>setO(!o)} className="w-5 h-5 rounded-full bg-slate-200 text-slate-600 text-xs font-bold inline-flex items-center justify-center">?</button>{o&&<div className="absolute z-50 bottom-7 left-1/2 -translate-x-1/2 w-72 bg-slate-800 text-white text-sm rounded-xl p-3 shadow-xl" style={{maxWidth:"85vw"}}>{text}</div>}</span>);}
function Card({children,className=""}){return<div className={"bg-white rounded-2xl shadow-sm border border-slate-200 p-5 "+className}>{children}</div>;}
function Sel({label,value,onChange,options,tooltip,id}){return(<div className="mb-4"><label htmlFor={id} className="block text-sm font-semibold text-slate-700 mb-1">{label}{tooltip&&<Tip text={tooltip}/>}</label><select id={id} value={value} onChange={e=>onChange(e.target.value)} className="w-full border border-slate-300 rounded-xl px-4 py-3 text-slate-800 bg-white outline-none text-base">{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></div>);}
function Inp({label,value,onChange,type="number",placeholder,tooltip,suffix,id}){return(<div className="mb-4"><label htmlFor={id} className="block text-sm font-semibold text-slate-700 mb-1">{label}{tooltip&&<Tip text={tooltip}/>}</label><div className="relative"><input id={id} type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="w-full border border-slate-300 rounded-xl px-4 py-3 text-slate-800 bg-white outline-none text-base"/>{suffix&&<span className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400 text-sm">{suffix}</span>}</div></div>);}
function Btn({onClick,children,secondary}){return secondary?<button onClick={onClick} className="border border-slate-300 text-slate-600 font-semibold px-6 py-3 rounded-xl hover:bg-slate-50 text-sm">{children}</button>:<button onClick={onClick} className="bg-gradient-to-r from-blue-600 to-indigo-600 text-white font-semibold px-6 py-3 rounded-xl shadow text-sm">{children}</button>;}
function Prog({c,t}){const p=t>0?Math.round(c/t*100):0;return(<div className="w-full mb-6"><div className="flex justify-between text-sm text-slate-500 mb-1"><span>Étape {c}/{t}</span><span>{p}%</span></div><div className="w-full h-2 bg-slate-200 rounded-full overflow-hidden"><div className="h-full bg-gradient-to-r from-blue-500 to-indigo-500 rounded-full transition-all duration-500" style={{width:`${p}%`}}/></div></div>);}
function BCards({items}){return(<div className="grid gap-2 mt-2">{items.map((b,i)=>(<div key={i} className="border-2 rounded-xl p-3 border-slate-200 bg-slate-50"><div className="flex items-center gap-2"><span className="text-xl">{b.e}</span><span className="font-bold text-slate-800 text-sm">{b.n}</span>{i===0&&<span className="text-xs bg-yellow-400 text-yellow-900 px-2 py-0.5 rounded-full font-bold ml-auto">Top</span>}</div>{b.f&&<p className="text-xs text-slate-600 mt-1">{b.f}</p>}</div>))}</div>);}
function DCard({children,style={},className=""}){return<div className={className} style={{background:DK.card,border:`1px solid ${DK.bd}`,borderRadius:16,padding:18,...style}}>{children}</div>;}
function DInp({label,value,onChange,type="number",placeholder,suffix,id}){return(<div className="mb-3"><label htmlFor={id} className="block text-xs font-semibold mb-1" style={{color:DK.sub}}>{label}</label><div className="relative"><input id={id} type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} style={{background:DK.card2,border:`1px solid ${DK.bd}`,color:DK.txt}} className="w-full rounded-xl px-3 py-2.5 outline-none text-sm"/>{suffix&&<span className="absolute right-3 top-1/2 -translate-y-1/2 text-xs" style={{color:DK.sub}}>{suffix}</span>}</div></div>);}
function DSel({label,value,onChange,options,id}){return(<div className="mb-3"><label htmlFor={id} className="block text-xs font-semibold mb-1" style={{color:DK.sub}}>{label}</label><select id={id} value={value} onChange={e=>onChange(e.target.value)} style={{background:DK.card2,border:`1px solid ${DK.bd}`,color:DK.txt}} className="w-full rounded-xl px-3 py-2.5 outline-none text-sm">{options.map(o=><option key={o.value} value={o.value} style={{background:DK.card2}}>{o.label}</option>)}</select></div>);}
function Gauge({score,size=90}){const color=score>=70?DK.grn:score>=40?"#f59e0b":DK.red;const r=size/2-5;const circ=2*Math.PI*r;return(<div className="relative" style={{width:size,height:size}}><svg viewBox={`0 0 ${size} ${size}`} className="-rotate-90"><circle cx={size/2} cy={size/2} r={r} fill="none" stroke={DK.bd} strokeWidth="7"/><circle cx={size/2} cy={size/2} r={r} fill="none" stroke={color} strokeWidth="7" strokeDasharray={circ} strokeDashoffset={circ*(1-score/100)} strokeLinecap="round"/></svg><span className="absolute inset-0 flex items-center justify-center font-bold text-lg" style={{color:DK.txt}}>{score}</span></div>);}

const SAVE_KEY="nheb_v7";
function loadState(){try{const s=localStorage.getItem(SAVE_KEY);return s?JSON.parse(s):null;}catch{return null;}}
function saveState(d){try{localStorage.setItem(SAVE_KEY,JSON.stringify(d));}catch{}}

export default function App(){
const saved=loadState();const I=(k,d)=>saved?.[k]??d;
const[page,setPage]=useState(I("page","q"));const[step,setStep]=useState(I("step",0));const[dashTab,setDashTab]=useState("patrimoine");const[toolTab,setToolTab]=useState("acheter");const[done,setDone]=useState(I("done",false));
const[age,setAge]=useState(I("age",""));const[statut,setStatut]=useState(I("statut",""));const[situationFam,setSituationFam]=useState(I("situationFam",""));const[nbEnfants,setNbEnfants]=useState(I("nbEnfants",""));const[logement,setLogement]=useState(I("logement",""));const[pays,setPays]=useState(I("pays",""));const[villeType,setVilleType]=useState(I("villeType",""));
const[modeCouple,setModeCouple]=useState(I("modeCouple",false));const[p2Rev,setP2Rev]=useState(I("p2Rev",""));const[p2Ch,setP2Ch]=useState(I("p2Ch",""));const[p2Ep,setP2Ep]=useState(I("p2Ep",""));
const[typeRevenu,setTypeRevenu]=useState(I("typeRevenu","net_mensuel"));const[brutAnnuel,setBrutAnnuel]=useState(I("brutAnnuel",""));const[netMensuel,setNetMensuel]=useState(I("netMensuel",""));const[primes,setPrimes]=useState(I("primes",""));const[autresRev,setAutresRev]=useState(I("autresRev",""));
const[loyer,setLoyer]=useState(I("loyer",""));const[alimentation,setAlimentation]=useState(I("alimentation",""));const[transports,setTransports]=useState(I("transports",""));const[abonnements,setAbonnements]=useState(I("abonnements",""));const[assurancesCh,setAssurancesCh]=useState(I("assurancesCh",""));const[loisirs,setLoisirs]=useState(I("loisirs",""));const[creditsConso,setCreditsConso]=useState(I("creditsConso",""));const[autresCharges,setAutresCharges]=useState(I("autresCharges",""));
const[epargnePrecaution,setEpargnePrecaution]=useState(I("epargnePrecaution",""));const[montantEpargne,setMontantEpargne]=useState(I("montantEpargne",""));const[aLivretA,setALivretA]=useState(I("aLivretA",""));const[aLDDS,setALDDS]=useState(I("aLDDS",""));
const[aPEA,setAPEA]=useState(I("aPEA",""));const[aPER,setAPER]=useState(I("aPER",""));const[aAV,setAAV]=useState(I("aAV",""));
const[peaMontant,setPeaMontant]=useState(I("peaMontant",""));const[peaDepuis,setPeaDepuis]=useState(I("peaDepuis",""));const[perMontant,setPerMontant]=useState(I("perMontant",""));const[avMontant,setAvMontant]=useState(I("avMontant",""));
const[aCrypto,setACrypto]=useState(I("aCrypto",""));const[cryptoMontant,setCryptoMontant]=useState(I("cryptoMontant",""));const[immoValeur,setImmoValeur]=useState(I("immoValeur",""));const[autresActifs,setAutresActifs]=useState(I("autresActifs",""));
const[toleranceRisque,setToleranceRisque]=useState(I("toleranceRisque",""));const[horizon,setHorizon]=useState(I("horizon",""));const[reaction,setReaction]=useState(I("reaction",""));
const[userGoals,setUserGoals]=useState(I("userGoals",[]));const[entries,setEntries]=useState(I("entries",[]));const[actionsDone,setActionsDone]=useState(I("actionsDone",{}));const[soldeCourant,setSoldeCourant]=useState(I("soldeCourant",""));
const[positions,setPositions]=useState(I("positions",[]));const[showPF,setShowPF]=useState(false);const[newP,setNewP]=useState({nom:"",type:"ETF",enveloppe:"PEA",qte:"",pru:"",prix:""});
const[bpSalG,setBpSalG]=useState(I("bpSalG","2"));const[bpInfl,setBpInfl]=useState(I("bpInfl","2"));const[bpRetAct,setBpRetAct]=useState(I("bpRetAct","7"));const[bpRetAV,setBpRetAV]=useState(I("bpRetAV","4"));const[bpRetLiv,setBpRetLiv]=useState(I("bpRetLiv","2.4"));
const[bpEvents,setBpEvents]=useState(I("bpEvents",[]));const[showEF,setShowEF]=useState(false);const[newE,setNewE]=useState({date:new Date().toISOString().slice(0,7),pea:"",av:"",per:"",livrets:"",crypto:"",soldeCc:"",immo:"",autres:"",versement:"",retrait:"",notes:""});const[showEvF,setShowEvF]=useState(false);const[newEv,setNewEv]=useState({nom:"",annee:"",cout:""});const[showDCA,setShowDCA]=useState(false);
const[credits,setCredits]=useState(I("credits",[]));const[showCF,setShowCF]=useState(false);const[newCr,setNewCr]=useState({nom:"",restant:"",taux:"",mensualite:""});
const[bienPrix,setBienPrix]=useState("");const[apport,setApport]=useState("");const[tauxCr,setTauxCr]=useState("3.5");const[dureeCr,setDureeCr]=useState("25");const[loyerAct,setLoyerAct]=useState("");const[chargesCo,setChargesCo]=useState("");const[taxeF,setTaxeF]=useState("");

useEffect(()=>{saveState({page,step,done,age,statut,situationFam,nbEnfants,logement,pays,villeType,modeCouple,p2Rev,p2Ch,p2Ep,typeRevenu,brutAnnuel,netMensuel,primes,autresRev,loyer,alimentation,transports,abonnements,assurancesCh,loisirs,creditsConso,autresCharges,epargnePrecaution,montantEpargne,aLivretA,aLDDS,aPEA,aPER,aAV,peaMontant,peaDepuis,perMontant,avMontant,aCrypto,cryptoMontant,immoValeur,autresActifs,toleranceRisque,horizon,reaction,userGoals,entries,actionsDone,soldeCourant,positions,bpSalG,bpInfl,bpRetAct,bpRetAV,bpRetLiv,bpEvents,credits});});

const C=CO[pays]||CO.france;const cur=C.cur;const fc=n=>fmt(n)+" "+cur;
const getNet=()=>{if(typeRevenu==="net_mensuel")return(parseFloat(netMensuel)||0)+(parseFloat(primes)||0)/12+(parseFloat(autresRev)||0);const b=parseFloat(brutAnnuel)||0;const t=statut==="fonctionnaire"?0.83:statut==="independant"?0.55:0.75;return b*t/12+(parseFloat(primes)||0)/12+(parseFloat(autresRev)||0);};
const totalCh=()=>[loyer,alimentation,transports,abonnements,assurancesCh,loisirs,creditsConso,autresCharges].reduce((s,v)=>s+(parseFloat(v)||0),0);
const rev=getNet();const ch=totalCh();const dispo=rev-ch;
const coupleRev=modeCouple?rev+(parseFloat(p2Rev)||0):rev;const coupleCh=modeCouple?ch+(parseFloat(p2Ch)||0):ch;const coupleDispo=coupleRev-coupleCh;
const epNum=parseFloat(montantEpargne)||0;const moisEp=ch>0?epNum/ch:0;
const peaV=parseFloat(peaMontant)||0,avV=parseFloat(avMontant)||0,perV=parseFloat(perMontant)||0,cryptoV=parseFloat(cryptoMontant)||0,immoV=parseFloat(immoValeur)||0,autresV=parseFloat(autresActifs)||0;
const lastE=entries[entries.length-1];
const snap=lastE?{pea:lastE.pea,av:lastE.av,per:lastE.per,livrets:lastE.livrets,crypto:lastE.crypto||0,cash:lastE.soldeCc||0,immo:lastE.immo||0,autres:lastE.autres||0}:{pea:peaV,av:avV,per:perV,livrets:epNum+(modeCouple?(parseFloat(p2Ep)||0):0),crypto:cryptoV,cash:parseFloat(soldeCourant)||0,immo:immoV,autres:autresV};
const patFin=snap.pea+snap.av+snap.per+snap.livrets+snap.crypto;
const netWorth=patFin+snap.cash+snap.immo+snap.autres;
const totalVersements=entries.reduce((s,e)=>s+(e.versement||0),0);

// POSITIONS calcs
const posCalc=positions.map(p=>{const q=parseFloat(p.qte)||0,pru=parseFloat(p.pru)||0,px=parseFloat(p.prix)||0;const invest=q*pru,valeur=q*px,pv=valeur-invest,perf=invest>0?(pv/invest*100):0;return{...p,invest,valeur,pv,perf};});
const posTotal=posCalc.reduce((s,p)=>s+p.valeur,0);
const posInvest=posCalc.reduce((s,p)=>s+p.invest,0);
const posPV=posTotal-posInvest;
const posPerf=posInvest>0?(posPV/posInvest*100):0;
const posByType=Object.values(posCalc.reduce((acc,p)=>{acc[p.type]=acc[p.type]||{name:p.type,v:0};acc[p.type].v+=p.valeur;return acc;},{})).filter(x=>x.v>0);

const getTMI=()=>{const br=C.tmi;let annual,p=1;if(C.parts){annual=(modeCouple?coupleRev:rev)*12;if(situationFam==="couple"||modeCouple)p=2;if(situationFam==="famille")p=2+Math.min(parseInt(nbEnfants)||0,2)*0.5+Math.max(0,(parseInt(nbEnfants)||0)-2);}else annual=(modeCouple?coupleRev:rev)*12;const qi=(annual*0.9)/p;for(const[seuil,taux]of br)if(qi<=seuil)return taux;return br[br.length-1][1];};
const getProfil=()=>{let s=0;s+=toleranceRisque==="agressif"?3:toleranceRisque==="modere"?2:1;s+=horizon==="long"?3:horizon==="moyen"?2:1;s+=reaction==="acheter"?3:reaction==="rien"?2:1;if(s>=7)return{label:"Dynamique",cl:"text-emerald-600",pct:90};if(s>=5)return{label:"Équilibré",cl:"text-blue-600",pct:70};return{label:"Prudent",cl:"text-amber-600",pct:50};};
const getMI=()=>{const d=modeCouple?coupleDispo:dispo;if(d<=0)return 0;if(moisEp<3)return Math.floor(d*0.1);if(moisEp<6)return Math.floor(d*0.2);return Math.floor(d*0.35);};
const profil=getProfil();const mi=getMI();const tmi=getTMI();const idealAlloc=IDEAL[profil.label]||IDEAL["Équilibré"];
const savingsRate=coupleRev>0?Math.round((mi/coupleRev)*100):0;
const fireNumber=(modeCouple?coupleCh:ch)*12*25;
const fireProgress=fireNumber>0?Math.min(100,Math.round(patFin/fireNumber*100)):0;
const passiveIncome=Math.round((snap.pea*0.02+snap.av*0.025+snap.livrets*(C.liv.rate/100)+snap.immo*0.03)/12);

const getDCASplit=()=>{if(mi<=0)return[];const etfs=[{n:"ETF MSCI World",isin:"IE00B4L5Y983",ter:"0,20 %",p:profil.pct>=80?70:profil.pct>=60?60:45,why:"Base : 1 500 entreprises, 23 pays"},{n:"ETF Emerging Markets",isin:"IE00BKM4GZ66",ter:"0,18 %",p:profil.pct>=80?15:10,why:"Croissance : Chine, Inde, Brésil"},{n:"ETF Europe / local",isin:"—",ter:"0,15 %",p:15,why:"Diversification régionale"}];if(profil.pct<80)etfs.push({n:"ETF Obligations",isin:"—",ter:"0,15 %",p:profil.pct>=60?10:25,why:"Stabilité : obligations"});if(mi<100)return[{...etfs[0],montant:mi,p:100,why:"Petit budget : concentrez pour éviter les frais"}];return etfs.map(e=>({...e,montant:Math.round(mi*e.p/100)}));};
const getDiversScore=()=>{let s=0;const d=[];const add=(n,pts,ok)=>{if(ok)s+=pts;d.push({n,s:pts,ok});};add(C.liv.n,20,aLivretA==="oui");add(C.inv.n,25,aPEA==="oui");add(C.ass.n,15,aAV==="oui");if(tmi>=30)add(C.ret.n,10,aPER==="oui");add("Matelas ≥ 3 mois",10,moisEp>=3);add("DCA actif",10,mi>0);add("Patrimoine solide",10,patFin>10000);return{score:Math.min(100,s),details:d};};
const getTaxComparison=()=>[5,10,15,20].map(y=>{const n=y*12,r=0.07/12;const fv=mi*((Math.pow(1+r,n)-1)/r);const g=fv-mi*n;return{y,gains:Math.round(g),taxOptim:Math.round(g*C.tax.optim.r/100),taxStd:Math.round(g*C.tax.std.r/100),saved:Math.round(g*(C.tax.std.r-C.tax.optim.r)/100)};});
const getRebalance=()=>{if(patFin<=0)return[];const pd=[{name:"Actions",v:snap.pea},{name:"Assurance",v:snap.av+snap.per},{name:"Livrets",v:snap.livrets},{name:"Crypto",v:snap.crypto}].filter(x=>x.v>0);if(pd.length===0)return[];const sig=[];const ap=pd.map(x=>({name:x.name,pct:Math.round(x.v/patFin*100),val:x.v}));idealAlloc.forEach(ia=>{const a=ap.find(x=>x.name===ia.n);const aP=a?a.pct:0,aV=a?a.val:0,iV=Math.round(patFin*ia.p/100),diff=aP-ia.p;if(diff>10){const tg=idealAlloc.filter(t=>{const ta=ap.find(x=>x.name===t.n);return(ta?ta.pct:0)<t.p-5;});sig.push({sev:"warning",icon:"🔶",msg:`${ia.n} surpondéré : ${aP} % (cible ${ia.p} %)`,action:`Redirigez ~${fc(aV-iV)} vers ${tg.map(t=>t.n).join(", ")||"les sous-pondérés"}`,det:"Orientez vos prochains versements DCA sans forcément vendre."});}else if(diff<-10)sig.push({sev:"info",icon:"🔵",msg:`${ia.n} sous-pondéré : ${aP} % (cible ${ia.p} %)`,action:`Augmentez ${ia.n} de ~${fc(iV-aV)}`,det:"Priorisez cette poche dans vos prochains versements."});});if(sig.length===0)sig.push({sev:"success",icon:"✅",msg:"Allocation bien calibrée",action:"Continuez votre DCA habituel",det:"Écart sous 10 %."});return sig;};

const genBP=()=>{const d=[];let r=(modeCouple?coupleRev:rev)*12,c=(modeCouple?coupleCh:ch)*12;let pea=snap.pea,av=snap.av,liv=snap.livrets;const invest=mi*12;const sg=parseFloat(bpSalG)/100,inf=parseFloat(bpInfl)/100,ra=parseFloat(bpRetAct)/100,rv=parseFloat(bpRetAV)/100,rl=parseFloat(bpRetLiv)/100;const ageN=parseInt(age)||30;const cy=new Date().getFullYear();const pp=profil.pct>=80?0.65:profil.pct>=60?0.5:0.3,ap=profil.pct>=80?0.15:0.25,lp=1-pp-ap;
for(let y=1;y<=20;y++){const evM=bpEvents.filter(e=>parseInt(e.annee)===y);const evG=userGoals.filter(g=>(parseInt(g.annee)||cy+5)-cy===y);let ec=evM.reduce((s,e)=>s+(parseFloat(e.cout)||0),0)+evG.reduce((s,g)=>s+(parseFloat(g.cible)||0),0);let ed=[...evM.map(e=>e.nom),...evG.map(g=>g.emoji+" "+g.nom)].filter(Boolean).join(", ");pea*=(1+ra);av*=(1+rv);liv*=(1+rl);const yI=invest*Math.pow(1+sg,y-1);pea+=yI*pp;av+=yI*ap;liv+=yI*lp;if(ec>0){let rem=ec;const tk=(s,a)=>{const t=Math.min(Math.max(0,s),a);return[s-t,a-t];};[liv,rem]=tk(liv,rem);[av,rem]=tk(av,rem);[pea,rem]=tk(pea,rem);}r*=(1+sg);c*=(1+inf);const total=Math.round(Math.max(0,pea)+Math.max(0,av)+snap.per+Math.max(0,liv));const reel=Math.round(total/Math.pow(1+inf,y));d.push({y,age:ageN+y,pea:Math.round(Math.max(0,pea)),av:Math.round(Math.max(0,av)),liv:Math.round(Math.max(0,liv)),total,reel,ev:ed});}return d;};
const getBPAlerts=data=>{const a=[];const cy=new Date().getFullYear();userGoals.forEach(g=>{const tY=(parseInt(g.annee)||cy+5)-cy;const cible=parseFloat(g.cible)||0;if(tY<1||tY>20)return;const row=data[tY-1];if(!row)return;if(row.total<cible)a.push({type:"danger",emoji:g.emoji,nom:g.nom,msg:`Année ${tY} : ${fc(row.total)} vs ${fc(cible)}. Manque ${fc(cible-row.total)}.`,conseil:"Augmentez l'épargne, repoussez ou réduisez."});else a.push({type:"success",emoji:g.emoji,nom:g.nom,msg:`✅ "${g.nom}" atteignable ! ${fc(row.total)} (cible ${fc(cible)}).`,conseil:null});});return a;};
const getRecos=()=>{const r=[];const es=[{nom:C.liv.n,has:aLivretA==="oui",rdt:C.liv.rate+" %",risque:"Aucun",desc:C.liv.tip}];if(C.liv2)es.push({nom:C.liv2.n,has:aLDDS==="oui",rdt:C.liv.rate+" %",risque:"Aucun",desc:"Complément de l'épargne réglementée."});es.push({nom:C.inv.n,has:aPEA==="oui",rdt:"~7 %/an",risque:"Modéré",desc:C.inv.tip});es.push({nom:C.ass.n,has:aAV==="oui",rdt:"2 à 6 %",risque:"Variable",desc:C.ass.tip});if(tmi>=30)es.push({nom:C.ret.n,has:aPER==="oui",rdt:"3 à 6 %",risque:"Variable",desc:C.ret.tip});r.push({tier:"🟢 Essentiels",items:es});const t2=[{nom:"Crypto (BTC + ETH)",has:snap.crypto>0,rdt:"Variable",risque:"Très élevé",desc:`Max ${profil.pct>=80?"5":"3"} % du patrimoine. Uniquement BTC + ETH pour commencer.`}];if(patFin>5000)t2.push({nom:"SCPI / Immobilier papier",has:false,rdt:"4 à 6 %",risque:"Modéré",desc:"Revenus locatifs sans gestion."});if(patFin>10000)t2.push({nom:"Or (ETF)",has:false,rdt:"3 à 5 %",risque:"Modéré",desc:"Valeur refuge anti-crise. Max 10 %."});r.push({tier:"🔵 Diversification",items:t2});const t3=[];if(patFin>50000)t3.push({nom:"Actions internationales",has:false,rdt:"~7 %",risque:"Élevé",desc:"Élargir aux marchés US via un courtier."});if(patFin>30000)t3.push({nom:"Crowdfunding immo",has:false,rdt:"8 à 12 %",risque:"Élevé",desc:"Prêts à promoteurs. Capital non garanti."});if(patFin>100000)t3.push({nom:"Private Equity",has:false,rdt:"10 à 15 %",risque:"Très élevé",desc:"Entreprises non cotées. Bloqué 10 ans."});if(t3.length>0)r.push({tier:"🟣 Avancé",items:t3});return r;};
const analyzeGoal=g=>{const cy=new Date().getFullYear();const yl=Math.max(0,(parseInt(g.annee)||cy+5)-cy);const cible=parseFloat(g.cible)||0;if(cible<=0)return{prog:0,mn:0,yl,status:"on_track"};const prog=Math.min(100,Math.round(patFin/cible*100));if(patFin>=cible)return{prog:100,mn:0,yl,status:"atteint"};if(yl===0)return{prog,mn:0,yl,status:"echoue"};const r=0.06/12,n=yl*12,fv=patFin*Math.pow(1+r,n),rem=Math.max(0,cible-fv);const mn=rem>0?Math.round(rem/((Math.pow(1+r,n)-1)/r)):0;return{prog,mn,yl,status:mn<=mi?"on_track":mn<=mi*1.5?"tight":"unrealistic"};};
const getActions=()=>{const a=[];if(aLivretA!=="oui")a.push({id:"la",txt:`Ouvrir un ${C.liv.n}`,p:"haute"});if(C.liv2&&aLDDS!=="oui")a.push({id:"ldds",txt:`Ouvrir un ${C.liv2.n}`,p:"haute"});if(aPEA!=="oui")a.push({id:"pea",txt:`Ouvrir un ${C.inv.n}`,p:"critique"});if(moisEp<6)a.push({id:"prec",txt:`Épargne précaution → ${fc(ch*6)}`,p:"haute"});if(aAV!=="oui")a.push({id:"av",txt:`Ouvrir : ${C.ass.n}`,p:"moyenne"});if(tmi>=30&&aPER!=="oui")a.push({id:"per",txt:`Ouvrir un ${C.ret.n}`,p:"moyenne"});if(mi>0&&aPEA==="oui")a.push({id:"dca",txt:`DCA ${fc(mi)}/mois`,p:"haute"});return a;};
const getAlerts=()=>{const a=[];const dormant=Math.max(0,snap.cash-ch*1.1);if(dormant>500)a.push({t:"warning",icon:"💤",titre:`${fc(dormant)} dormants`,txt:`Placez-les sur votre ${moisEp<6?C.liv.n:C.inv.n}.`});if(pays==="france"&&peaDepuis==="plus5")a.push({t:"info",icon:"🔓",titre:"PEA mature",txt:"Retraits à 17,2 % seulement."});if(pays==="france"&&peaDepuis==="3a5")a.push({t:"info",icon:"⏳",titre:"PEA bientôt mature",txt:"Ne retirez rien avant 5 ans !"});if(moisEp<3&&epargnePrecaution!=="non")a.push({t:"danger",icon:"🚨",titre:"Épargne insuffisante",txt:`${moisEp.toFixed(1)} mois seulement.`});posCalc.forEach(p=>{if(p.perf<=-20)a.push({t:"info",icon:"📉",titre:`${p.nom} en forte baisse (${p.perf.toFixed(0)} %)`,txt:"Si vous croyez toujours à cet actif, c'est l'occasion de renforcer (DCA). Ne vendez pas sous la panique."});if(p.perf>=50)a.push({t:"success",icon:"📈",titre:`${p.nom} : +${p.perf.toFixed(0)} %`,txt:"Belle plus-value ! Pensez à rééquilibrer si cette ligne pèse trop dans votre portefeuille."});});userGoals.forEach(g=>{if(analyzeGoal(g).status==="atteint")a.push({t:"success",icon:"🎉",titre:`"${g.nom}" atteint !`,txt:"Sécurisez vos gains."});});return a;};
const toggleGoal=t=>{const ex=userGoals.find(g=>g.id===t.id);if(ex)setUserGoals(userGoals.filter(g=>g.id!==t.id));else setUserGoals([...userGoals,{...t,cible:smartDef(t.id,pays,villeType,nbEnfants),annee:new Date().getFullYear()+(t.id==="fire"?20:t.id==="immo"?7:5)}]);};
const updGoal=(id,f,v)=>setUserGoals(userGoals.map(g=>g.id===id?{...g,[f]:v}:g));
const getSteps=()=>{const s=["intro","profil","revenus","charges","epargne","enveloppes","actifs"];if(pays==="france"&&aPEA==="oui")s.push("d_pea");s.push("risque","objectifs","resultats");return s;};
const steps=getSteps();const cs=steps[step]||"intro";const next=()=>step<steps.length-1&&setStep(step+1);const prev=()=>step>0&&setStep(step-1);
const goToDash=()=>{if(entries.length===0)setEntries([{date:new Date().toISOString().slice(0,7),pea:peaV,av:avV,per:perV,livrets:epNum+(modeCouple?(parseFloat(p2Ep)||0):0),crypto:cryptoV,soldeCc:parseFloat(soldeCourant)||0,immo:immoV,autres:autresV,versement:0,retrait:0,notes:"Bilan initial"}]);setDone(true);setPage("d");};
const addEntry=()=>{const e={date:newE.date,pea:parseFloat(newE.pea)||0,av:parseFloat(newE.av)||0,per:parseFloat(newE.per)||0,livrets:parseFloat(newE.livrets)||0,crypto:parseFloat(newE.crypto)||0,soldeCc:parseFloat(newE.soldeCc)||0,immo:parseFloat(newE.immo)||0,autres:parseFloat(newE.autres)||0,versement:parseFloat(newE.versement)||0,retrait:parseFloat(newE.retrait)||0,notes:newE.notes};setEntries(p=>[...p,e].sort((a,b)=>a.date.localeCompare(b.date)));setShowEF(false);setNewE({date:new Date().toISOString().slice(0,7),pea:"",av:"",per:"",livrets:"",crypto:"",soldeCc:"",immo:"",autres:"",versement:"",retrait:"",notes:""});};
const addPos=()=>{if(!newP.nom)return;setPositions(p=>[...p,newP]);setNewP({nom:"",type:"ETF",enveloppe:"PEA",qte:"",pru:"",prix:""});setShowPF(false);};
const applyScenario=k=>{const s=SCEN[k];setBpSalG(s.sG);setBpInfl(s.inf);setBpRetAct(s.rA);setBpRetAV(s.rV);setBpRetLiv(s.rL);};

const chartData=entries.map(e=>({m:e.date.slice(5)+"/"+e.date.slice(2,4),Total:e.pea+e.av+e.per+e.livrets+(e.crypto||0)+(e.soldeCc||0)+(e.immo||0)+(e.autres||0)}));
const catData=[{name:"Liquidités",v:snap.cash+snap.livrets},{name:"Investissements",v:snap.pea+snap.av+snap.per},{name:"Crypto",v:snap.crypto},{name:"Immobilier",v:snap.immo},{name:"Autres",v:snap.autres}].filter(d=>d.v>0);
const perf=(()=>{if(entries.length<2)return null;const f=entries[0],l=entries[entries.length-1];const fv=f.pea+f.av+f.per+f.livrets+(f.crypto||0)+(f.soldeCc||0)+(f.immo||0)+(f.autres||0);const lv=l.pea+l.av+l.per+l.livrets+(l.crypto||0)+(l.soldeCc||0)+(l.immo||0)+(l.autres||0);const diff=lv-fv;const gains=diff-totalVersements;return{diff,pct:fv>0?(diff/fv*100):0,gains};})();

const rIntro=()=>(<div className="text-center"><div className="text-5xl mb-3">💸</div><h1 className="text-3xl font-black mb-1">Nheb Barcha Flous</h1><p className="text-slate-400 text-sm mb-4 italic">نحب برشا فلوس</p><p className="text-slate-600 mb-6">Votre <strong>conseiller & gestionnaire de patrimoine</strong> — adapté à votre pays.</p>{saved&&done&&<p className="text-sm text-emerald-600 mb-4">💾 Données restaurées !</p>}<Btn onClick={next}>Commencer →</Btn></div>);
const rProfil=()=>(<div><h2 className="text-xl font-bold mb-4">👤 Situation</h2><Inp id="age" label="Âge" value={age} onChange={setAge} placeholder="28" suffix="ans"/><Sel id="pays" label="Pays de résidence" value={pays} onChange={setPays} tooltip="Détermine la fiscalité, les produits disponibles et la monnaie." options={[{value:"",label:"Choisir"},...Object.entries(CO).map(([k,v])=>({value:k,label:v.l}))]}/><Sel id="vt" label="Type de ville" value={villeType} onChange={setVilleType} options={[{value:"",label:"Choisir"},...Object.entries(CITY).map(([k,v])=>({value:k,label:v.l}))]}/><Sel id="st" label="Statut" value={statut} onChange={setStatut} options={[{value:"",label:"Choisir"},{value:"salarie",label:"💼 Salarié(e)"},{value:"independant",label:"🏠 Indépendant(e)"},{value:"fonctionnaire",label:"🏛️ Fonctionnaire"},{value:"etudiant",label:"🎓 Étudiant(e)"},{value:"retraite",label:"🌅 Retraité(e)"}]}/><Sel id="fam" label="Famille" value={situationFam} onChange={setSituationFam} options={[{value:"",label:"Choisir"},{value:"seul",label:"Seul(e)"},{value:"couple",label:"En couple"},{value:"famille",label:"Avec enfant(s)"}]}/>{situationFam==="famille"&&<Inp id="enf" label="Enfants" value={nbEnfants} onChange={setNbEnfants} placeholder="2" tooltip={PARTS_TIP}/>}{(situationFam==="couple"||situationFam==="famille")&&<div className="bg-violet-50 border border-violet-200 rounded-xl p-4 mb-4"><div className="flex items-center justify-between mb-2"><p className="font-bold text-sm text-violet-800">👫 Mode couple</p><button onClick={()=>setModeCouple(!modeCouple)} className={`px-3 py-1 rounded-full text-xs font-bold ${modeCouple?"bg-violet-600 text-white":"bg-violet-200 text-violet-700"}`}>{modeCouple?"Activé ✓":"Activer"}</button></div>{modeCouple&&<><Inp id="p2r" label="Revenus conjoint(e)" value={p2Rev} onChange={setP2Rev} placeholder="2 000" suffix={cur+"/m"}/><Inp id="p2c" label="Charges conjoint(e)" value={p2Ch} onChange={setP2Ch} placeholder="500" suffix={cur+"/m"}/><Inp id="p2e" label="Épargne conjoint(e)" value={p2Ep} onChange={setP2Ep} placeholder="3 000" suffix={cur}/></>}</div>}<Sel id="log" label="Logement" value={logement} onChange={setLogement} options={[{value:"",label:"Choisir"},{value:"locataire",label:"🏠 Locataire"},{value:"proprietaire",label:"🏡 Proprio (crédit)"},{value:"proprio_fini",label:"🏡 Proprio (payé)"},{value:"heberge",label:"Hébergé(e)"}]}/></div>);
const rRevenus=()=>(<div><h2 className="text-xl font-bold mb-4">💰 Revenus</h2><Sel id="tr" label="Format" value={typeRevenu} onChange={setTypeRevenu} options={[{value:"net_mensuel",label:"💶 Net mensuel"},{value:"brut_annuel",label:"📋 Brut annuel"}]}/>{typeRevenu==="brut_annuel"?<Inp id="brut" label="Brut annuel" value={brutAnnuel} onChange={setBrutAnnuel} placeholder="35 000" suffix={cur+"/an"}/>:<Inp id="net" label="Net mensuel" value={netMensuel} onChange={setNetMensuel} placeholder="2 200" suffix={cur+"/m"}/>}<Inp id="pr" label="Primes annuelles" value={primes} onChange={setPrimes} placeholder="3 000" suffix={cur+"/an"}/><Inp id="ar" label="Autres revenus" value={autresRev} onChange={setAutresRev} placeholder="200" suffix={cur+"/m"}/>{rev>0&&<div className="bg-emerald-50 border border-emerald-200 rounded-xl p-4 mt-2"><p className="text-emerald-800 font-semibold text-lg">{modeCouple?`Couple : ${fc(coupleRev)}`:`Total : ${fc(rev)}`}/mois</p>{tmi>0&&<p className="text-emerald-700 text-sm mt-1">TMI ({C.l}) : <strong>{tmi} %</strong></p>}</div>}</div>);
const rCharges=()=>(<div><h2 className="text-xl font-bold mb-4">🧾 Charges</h2><Inp id="loy" label="🏠 Loyer" value={loyer} onChange={setLoyer} placeholder="800" suffix={cur}/><Inp id="ali" label="🛒 Alimentation" value={alimentation} onChange={setAlimentation} placeholder="350" suffix={cur}/><Inp id="tra" label="🚗 Transports" value={transports} onChange={setTransports} placeholder="80" suffix={cur}/><Inp id="abo" label="📱 Abonnements" value={abonnements} onChange={setAbonnements} placeholder="60" suffix={cur}/><Inp id="ass" label="🛡️ Assurances" value={assurancesCh} onChange={setAssurancesCh} placeholder="50" suffix={cur}/><Inp id="loi" label="🎭 Loisirs" value={loisirs} onChange={setLoisirs} placeholder="150" suffix={cur}/><Inp id="cre" label="💳 Crédits" value={creditsConso} onChange={setCreditsConso} placeholder="0" suffix={cur}/><Inp id="aut" label="📦 Autres" value={autresCharges} onChange={setAutresCharges} placeholder="50" suffix={cur}/><Inp id="scc" label="💳 Solde compte courant" value={soldeCourant} onChange={setSoldeCourant} placeholder="2 500" suffix={cur}/>{ch>0&&<div className={`rounded-xl p-4 mt-2 border ${(modeCouple?coupleDispo:dispo)>0?"bg-emerald-50 border-emerald-200":"bg-red-50 border-red-200"}`}><p className="font-bold text-xl" style={{color:(modeCouple?coupleDispo:dispo)>0?"#059669":"#dc2626"}}>{(modeCouple?coupleDispo:dispo)>0?`✅ ${fc(modeCouple?coupleDispo:dispo)}/mois`:"⚠️ Déficit"}</p></div>}</div>);
const rEpargne=()=>(<div><h2 className="text-xl font-bold mb-4">🛡️ Épargne ({C.sav})</h2><Sel id="ep" label="Épargne de précaution ?" value={epargnePrecaution} onChange={setEpargnePrecaution} options={[{value:"",label:"Choisir"},{value:"oui",label:"✅ Oui"},{value:"non",label:"❌ Non"},{value:"partiel",label:"🔶 Un peu"}]}/>{(epargnePrecaution==="oui"||epargnePrecaution==="partiel")&&<Inp id="me" label="Montant total sur vos comptes épargne" value={montantEpargne} onChange={setMontantEpargne} placeholder="5 000" suffix={cur} tooltip="Total sur tous vos livrets / comptes épargne."/>}<Sel id="la" label={`${C.liv.n} ?`} value={aLivretA} onChange={setALivretA} tooltip={C.liv.tip} options={[{value:"",label:"Choisir"},{value:"oui",label:"✅ Oui"},{value:"non",label:"❌ Non"}]}/>{C.liv2&&<Sel id="ld" label={`${C.liv2.n} ?`} value={aLDDS} onChange={setALDDS} tooltip="Complément de l'épargne réglementée, plafond 12 000 €." options={[{value:"",label:"Choisir"},{value:"oui",label:"✅ Oui"},{value:"non",label:"❌ Non"}]}/>}</div>);
const rEnveloppes=()=>(<div><h2 className="text-xl font-bold mb-4">📦 Placements ({C.l})</h2><Sel id="pea" label={`${C.inv.n} ?`} value={aPEA} onChange={setAPEA} tooltip={C.inv.tip} options={[{value:"",label:"Choisir"},{value:"oui",label:"✅ Oui"},{value:"non",label:"❌ Non"},{value:"sais_pas",label:"🤷 C'est quoi ?"}]}/>{(aPEA==="non"||aPEA==="sais_pas")&&<div className="mb-4"><div className="bg-blue-50 border border-blue-200 rounded-xl p-4 mb-3 text-sm text-blue-800">💡 {C.inv.tip}</div><BCards items={[{e:"🏦",n:C.inv.bk}]}/></div>}<Sel id="av" label={`${C.ass.n} ?`} value={aAV} onChange={setAAV} tooltip={C.ass.tip} options={[{value:"",label:"Choisir"},{value:"oui",label:"✅ Oui"},{value:"non",label:"❌ Non"}]}/>{aAV==="oui"&&<Inp id="avm" label={`Montant ${C.ass.n}`} value={avMontant} onChange={setAvMontant} placeholder="10 000" suffix={cur}/>}<Sel id="per" label={`${C.ret.n} ?`} value={aPER} onChange={setAPER} tooltip={C.ret.tip} options={[{value:"",label:"Choisir"},{value:"oui",label:"✅ Oui"},{value:"non",label:"❌ Non"}]}/>{aPER==="oui"&&<Inp id="perm" label={`Montant ${C.ret.n}`} value={perMontant} onChange={setPerMontant} placeholder="5 000" suffix={cur}/>}{aPER==="non"&&tmi>=30&&<div className="bg-violet-50 border border-violet-200 rounded-xl p-4 mb-4 text-sm text-violet-800">💡 TMI {tmi} % : {C.ret.n} recommandé.</div>}</div>);
const rActifs=()=>(<div><h2 className="text-xl font-bold mb-4">💎 Autres actifs</h2><Sel id="cr" label="Avez-vous de la crypto ?" value={aCrypto} onChange={setACrypto} options={[{value:"",label:"Choisir"},{value:"oui",label:"✅ Oui"},{value:"non",label:"❌ Non"}]}/>{aCrypto==="oui"&&<Inp id="crm" label="Valeur totale crypto" value={cryptoMontant} onChange={setCryptoMontant} placeholder="2 000" suffix={cur}/>}{(logement==="proprietaire"||logement==="proprio_fini")&&<Inp id="imm" label="🏡 Valeur de votre bien immobilier" value={immoValeur} onChange={setImmoValeur} placeholder="250 000" suffix={cur}/>}<Inp id="aa" label="📦 Autres actifs (or, objets de valeur…)" value={autresActifs} onChange={setAutresActifs} placeholder="0" suffix={cur}/><div className="bg-blue-50 border border-blue-200 rounded-xl p-3 text-sm text-blue-800">💡 Vous pourrez détailler chaque ETF/action dans l'onglet « Portefeuille » du dashboard.</div></div>);
const rDPEA=()=>(<div><h2 className="text-xl font-bold mb-4">📊 {C.inv.n}</h2><Inp id="pm" label="Montant" value={peaMontant} onChange={setPeaMontant} placeholder="3 000" suffix={cur}/><Sel id="pd" label="Ouvert depuis ?" value={peaDepuis} onChange={setPeaDepuis} options={[{value:"",label:"Choisir"},{value:"moins1",label:"< 1 an"},{value:"1a3",label:"1 à 3 ans"},{value:"3a5",label:"3 à 5 ans"},{value:"plus5",label:"> 5 ans ✅"}]}/></div>);
const rRisque=()=>(<div><h2 className="text-xl font-bold mb-4">🎯 Risque</h2><Sel id="tol" label="Attitude ?" value={toleranceRisque} onChange={setToleranceRisque} options={[{value:"",label:"Choisir"},{value:"prudent",label:"🛡️ Prudent"},{value:"modere",label:"⚖️ Modéré"},{value:"agressif",label:"🚀 Dynamique"}]}/><Sel id="hor" label="Horizon ?" value={horizon} onChange={setHorizon} options={[{value:"",label:"Choisir"},{value:"court",label:"< 5 ans"},{value:"moyen",label:"5 à 10 ans"},{value:"long",label:"> 10 ans"}]}/><Sel id="rea" label="Si -20 % en 1 mois ?" value={reaction} onChange={setReaction} options={[{value:"",label:"Choisir"},{value:"vendre",label:"😰 Je vends"},{value:"rien",label:"😐 J'attends"},{value:"acheter",label:"🤑 J'achète !"}]}/></div>);
const rObjectifs=()=>(<div><h2 className="text-xl font-bold mb-2">🎯 Objectifs</h2><div className="grid grid-cols-2 gap-2 mb-4">{GOAL_T.map(t=>{const sel=userGoals.find(g=>g.id===t.id);return(<button key={t.id} onClick={()=>toggleGoal(t)} className={`p-3 rounded-xl border-2 text-left ${sel?"border-blue-500 bg-blue-50":"border-slate-200"}`}><span className="text-2xl">{t.emoji}</span><p className="font-semibold text-xs mt-1">{t.nom}</p>{!sel&&pays&&<p className="text-xs text-slate-400">~{fc(smartDef(t.id,pays,villeType,nbEnfants))}</p>}</button>);})}</div>{userGoals.map(g=>(<div key={g.id} className="bg-slate-50 rounded-xl p-4 mb-3 border"><p className="font-semibold mb-2">{g.emoji} {g.nom}</p><div className="grid grid-cols-2 gap-3"><Inp id={g.id+"c"} label="Montant" value={g.cible} onChange={v=>updGoal(g.id,"cible",v)} suffix={cur}/><Inp id={g.id+"a"} label="Année" value={g.annee} onChange={v=>updGoal(g.id,"annee",v)}/></div>{(()=>{const an=analyzeGoal(g);return(<div className={`mt-2 rounded-lg p-3 text-sm ${an.status==="on_track"||an.status==="atteint"?"bg-emerald-100 text-emerald-800":an.status==="tight"?"bg-amber-100 text-amber-800":"bg-red-100 text-red-800"}`}>{an.status==="atteint"?"🎉 Atteint !":an.status==="on_track"?`✅ ${fc(an.mn)}/mois (budget ${fc(mi)})`:an.status==="tight"?`⚠️ ${fc(an.mn)}/mois requis`:`❌ ${fc(an.mn)}/mois. Irréalisable.`}</div>);})()}</div>))}</div>);
const rResultats=()=>(<div><div className="text-center mb-5"><div className="text-5xl mb-2">🎉</div><h2 className="text-2xl font-bold">Votre plan</h2></div><Card className="mb-4"><div className="grid grid-cols-2 gap-2 text-sm"><div className="bg-slate-50 rounded-lg p-3"><p className="text-slate-500">Patrimoine net</p><p className="font-bold text-lg">{fc(netWorth)}</p></div><div className="bg-slate-50 rounded-lg p-3"><p className="text-slate-500">Profil</p><p className={`font-bold text-lg ${profil.cl}`}>{profil.label}</p></div><div className="bg-slate-50 rounded-lg p-3"><p className="text-slate-500">À investir</p><p className="font-bold text-lg text-emerald-600">{fc(mi)}/m</p></div><div className="bg-slate-50 rounded-lg p-3"><p className="text-slate-500">TMI ({C.l})</p><p className="font-bold text-lg">{tmi} %</p></div></div></Card><div className="text-center mt-6"><Btn onClick={goToDash}>📊 Ouvrir mon patrimoine →</Btn></div></div>);
const renderStep=()=>({intro:rIntro,profil:rProfil,revenus:rRevenus,charges:rCharges,epargne:rEpargne,enveloppes:rEnveloppes,actifs:rActifs,d_pea:rDPEA,risque:rRisque,objectifs:rObjectifs,resultats:rResultats}[cs]?.()||null);

const axis={fontSize:11,fill:DK.sub};
const KPI=({label,val,sub,col})=>(<DCard><p className="text-xs" style={{color:DK.sub}}>{label}</p><p className="text-lg font-bold mt-0.5" style={{color:col||DK.txt}}>{val}</p>{sub&&<p className="text-xs mt-0.5" style={{color:DK.sub}}>{sub}</p>}</DCard>);
const dPatrimoine=()=>(<div>
<DCard className="mb-4" style={{background:"linear-gradient(135deg,#141419,#1C1C24)"}}><p className="text-sm" style={{color:DK.sub}}>Patrimoine net</p><p className="text-4xl font-black mt-1" style={{color:DK.txt}}>{fc(netWorth)}</p>{perf&&<div className="flex items-center gap-2 mt-2 flex-wrap"><span className="text-sm font-bold px-2 py-0.5 rounded-lg" style={{background:perf.diff>=0?"rgba(34,197,94,0.15)":"rgba(239,68,68,0.15)",color:perf.diff>=0?DK.grn:DK.red}}>{perf.diff>=0?"▲":"▼"} {fc(Math.abs(perf.diff))} ({perf.pct>=0?"+":""}{perf.pct.toFixed(1)} %)</span>{totalVersements>0&&<span className="text-xs" style={{color:DK.sub}}>dont {fc(perf.gains)} de plus-value</span>}</div>}</DCard>
<div className="grid grid-cols-2 gap-3 mb-4"><KPI label="Taux d'épargne" val={savingsRate+" %"} sub={savingsRate>=20?"Excellent 🔥":savingsRate>=10?"Correct":"À améliorer"} col={savingsRate>=20?DK.grn:savingsRate>=10?DK.blue:"#f59e0b"}/><KPI label="Revenus passifs" val={fc(passiveIncome)+"/m"} sub="dividendes, intérêts, loyers"/></div>
{catData.length>0&&<DCard className="mb-4"><h3 className="font-bold mb-3" style={{color:DK.txt}}>Répartition</h3><div className="flex items-center gap-4 flex-wrap"><ResponsiveContainer width={150} height={150}><PieChart><Pie data={catData} dataKey="v" nameKey="name" cx="50%" cy="50%" outerRadius={62} innerRadius={40} paddingAngle={2} stroke="none">{catData.map((d,i)=><Cell key={i} fill={CATC[d.name]||CL[i]}/>)}</Pie></PieChart></ResponsiveContainer><div className="flex-1 space-y-2 min-w-[140px]">{catData.map((d,i)=>(<div key={i}><div className="flex justify-between text-sm"><span className="flex items-center gap-2" style={{color:DK.txt}}><span className="w-2.5 h-2.5 rounded-full" style={{background:CATC[d.name]||CL[i]}}/>{d.name}</span><span style={{color:DK.sub}}>{Math.round(d.v/netWorth*100)} %</span></div><p className="text-xs ml-4" style={{color:DK.sub}}>{fc(d.v)}</p></div>))}</div></div></DCard>}
{chartData.length>1&&<DCard className="mb-4"><h3 className="font-bold mb-3" style={{color:DK.txt}}>Évolution</h3><ResponsiveContainer width="100%" height={200}><AreaChart data={chartData}><defs><linearGradient id="g1" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={DK.grn} stopOpacity={0.4}/><stop offset="100%" stopColor={DK.grn} stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke={DK.bd}/><XAxis dataKey="m" tick={axis}/><YAxis tick={axis} tickFormatter={v=>v>=1000?`${(v/1000).toFixed(0)}k`:v}/><RTooltip contentStyle={{background:DK.card2,border:`1px solid ${DK.bd}`,borderRadius:8,color:DK.txt}} formatter={v=>fc(v)}/><Area type="monotone" dataKey="Total" stroke={DK.grn} strokeWidth={2} fill="url(#g1)"/></AreaChart></ResponsiveContainer></DCard>}
<DCard><div className="flex justify-between items-center mb-3"><h3 className="font-bold" style={{color:DK.txt}}>Mes comptes</h3><button onClick={()=>setShowEF(!showEF)} className="text-xs font-semibold px-3 py-1.5 rounded-lg" style={{background:DK.grn,color:"#08080B"}}>{showEF?"✕ Fermer":"+ Mise à jour"}</button></div>{showEF&&<div className="rounded-xl p-3 mb-3" style={{background:DK.card2,border:`1px solid ${DK.bd}`}}><div className="grid grid-cols-2 gap-2"><DInp id="ed" label="Mois" value={newE.date} onChange={v=>setNewE({...newE,date:v})} type="month"/><DInp id="ecc" label="💳 Compte courant" value={newE.soldeCc} onChange={v=>setNewE({...newE,soldeCc:v})} suffix={cur}/><DInp id="ep2" label={`📊 ${C.inv.n}`} value={newE.pea} onChange={v=>setNewE({...newE,pea:v})} suffix={cur}/><DInp id="ea" label={`🛡️ ${C.ass.n}`} value={newE.av} onChange={v=>setNewE({...newE,av:v})} suffix={cur}/><DInp id="epr" label={`🏛️ ${C.ret.n}`} value={newE.per} onChange={v=>setNewE({...newE,per:v})} suffix={cur}/><DInp id="el" label="🏦 Livrets" value={newE.livrets} onChange={v=>setNewE({...newE,livrets:v})} suffix={cur}/><DInp id="ecr" label="₿ Crypto" value={newE.crypto} onChange={v=>setNewE({...newE,crypto:v})} suffix={cur}/><DInp id="eim" label="🏡 Immobilier" value={newE.immo} onChange={v=>setNewE({...newE,immo:v})} suffix={cur}/><DInp id="eau" label="📦 Autres" value={newE.autres} onChange={v=>setNewE({...newE,autres:v})} suffix={cur}/><DInp id="ev2" label="💰 Versé ce mois" value={newE.versement} onChange={v=>setNewE({...newE,versement:v})} suffix={cur}/></div><DInp id="en" label="📝 Notes" value={newE.notes} onChange={v=>setNewE({...newE,notes:v})} type="text" placeholder="Prime, dépense…"/><div className="text-right"><button onClick={addEntry} className="text-sm font-semibold px-4 py-2 rounded-lg" style={{background:DK.grn,color:"#08080B"}}>💾 Enregistrer</button></div></div>}<div className="space-y-2">{[{n:"💳 Compte courant",v:snap.cash},{n:"🏦 Livrets",v:snap.livrets},{n:`📊 ${C.inv.n}`,v:snap.pea},{n:`🛡️ ${C.ass.n}`,v:snap.av},{n:`🏛️ ${C.ret.n}`,v:snap.per},{n:"₿ Crypto",v:snap.crypto},{n:"🏡 Immobilier",v:snap.immo},{n:"📦 Autres",v:snap.autres}].filter(x=>x.v>0).map((x,i)=>(<div key={i} className="flex justify-between items-center py-2" style={{borderBottom:`1px solid ${DK.bd}`}}><span className="text-sm" style={{color:DK.txt}}>{x.n}</span><span className="text-sm font-bold" style={{color:DK.txt}}>{fc(x.v)}</span></div>))}</div></DCard>
</div>);

const dPortefeuille=()=>(<div>
<DCard className="mb-4" style={{background:"linear-gradient(135deg,#141419,#1C1C24)"}}>
<p className="text-sm" style={{color:DK.sub}}>Valeur du portefeuille titres</p>
<p className="text-3xl font-black mt-1" style={{color:DK.txt}}>{fc(posTotal)}</p>
{posInvest>0&&<div className="flex items-center gap-2 mt-2 flex-wrap"><span className="text-sm font-bold px-2 py-0.5 rounded-lg" style={{background:posPV>=0?"rgba(34,197,94,0.15)":"rgba(239,68,68,0.15)",color:posPV>=0?DK.grn:DK.red}}>{posPV>=0?"▲":"▼"} {fc(Math.abs(posPV))} ({posPerf>=0?"+":""}{posPerf.toFixed(1)} %)</span><span className="text-xs" style={{color:DK.sub}}>investi : {fc(posInvest)}</span></div>}
</DCard>
{posByType.length>0&&<DCard className="mb-4"><h3 className="font-bold mb-3" style={{color:DK.txt}}>Répartition par type</h3><div className="flex items-center gap-4 flex-wrap"><ResponsiveContainer width={130} height={130}><PieChart><Pie data={posByType} dataKey="v" nameKey="name" cx="50%" cy="50%" outerRadius={55} innerRadius={35} paddingAngle={2} stroke="none">{posByType.map((d,i)=><Cell key={i} fill={CL[i%CL.length]}/>)}</Pie></PieChart></ResponsiveContainer><div className="flex-1 space-y-1 min-w-[120px]">{posByType.map((d,i)=>(<div key={i} className="flex justify-between text-sm"><span className="flex items-center gap-2" style={{color:DK.txt}}><span className="w-2.5 h-2.5 rounded-full" style={{background:CL[i%CL.length]}}/>{d.name}</span><span style={{color:DK.sub}}>{fc(d.v)}</span></div>))}</div></div></DCard>}
<DCard><div className="flex justify-between items-center mb-3"><h3 className="font-bold" style={{color:DK.txt}}>Mes positions</h3><button onClick={()=>setShowPF(!showPF)} className="text-xs font-semibold px-3 py-1.5 rounded-lg" style={{background:DK.grn,color:"#08080B"}}>{showPF?"✕ Fermer":"+ Ajouter une ligne"}</button></div>
{showPF&&<div className="rounded-xl p-3 mb-3" style={{background:DK.card2,border:`1px solid ${DK.bd}`}}>
<DInp id="pn" label="Nom / Ticker (ex : Amundi MSCI World, Apple, BTC)" value={newP.nom} onChange={v=>setNewP({...newP,nom:v})} type="text" placeholder="Amundi MSCI World"/>
<div className="grid grid-cols-2 gap-2"><DSel id="pt" label="Type" value={newP.type} onChange={v=>setNewP({...newP,type:v})} options={[{value:"ETF",label:"ETF"},{value:"Action",label:"Action"},{value:"Crypto",label:"Crypto"},{value:"Obligation",label:"Obligation"},{value:"Autre",label:"Autre"}]}/><DSel id="pe" label="Enveloppe" value={newP.enveloppe} onChange={v=>setNewP({...newP,enveloppe:v})} options={[{value:"PEA",label:C.inv.n},{value:"AV",label:C.ass.n},{value:"CTO",label:"Compte-titres"},{value:"Crypto",label:"Wallet crypto"}]}/></div>
<div className="grid grid-cols-3 gap-2"><DInp id="pq" label="Quantité" value={newP.qte} onChange={v=>setNewP({...newP,qte:v})} placeholder="10"/><DInp id="ppru" label="Prix de revient (PRU)" value={newP.pru} onChange={v=>setNewP({...newP,pru:v})} placeholder="85" suffix={cur}/><DInp id="ppx" label="Prix actuel" value={newP.prix} onChange={v=>setNewP({...newP,prix:v})} placeholder="95" suffix={cur}/></div>
<div className="text-right"><button onClick={addPos} className="text-sm font-semibold px-4 py-2 rounded-lg" style={{background:DK.grn,color:"#08080B"}}>💾 Ajouter</button></div>
</div>}
{posCalc.length===0?<p className="text-sm" style={{color:DK.sub}}>Aucune position. Ajoutez vos ETF, actions ou cryptos pour suivre leur performance en détail.</p>:
<div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr style={{color:DK.sub}}><th className="text-left py-2">Actif</th><th>Qté</th><th>PRU</th><th>Prix</th><th>Valeur</th><th>+/- value</th><th></th></tr></thead><tbody>{posCalc.map((p,i)=>(<tr key={i} style={{borderTop:`1px solid ${DK.bd}`,color:DK.txt}}><td className="py-2"><p className="font-bold">{p.nom}</p><p style={{color:DK.sub}} className="text-xs">{p.type} · {p.enveloppe}</p></td><td className="text-center">{p.qte}</td><td className="text-center">{fmt2(parseFloat(p.pru)||0)}</td><td className="text-center">{fmt2(parseFloat(p.prix)||0)}</td><td className="text-center font-bold">{fc(p.valeur)}</td><td className="text-center" style={{color:p.pv>=0?DK.grn:DK.red}}>{p.pv>=0?"+":""}{fmt(p.pv)}<br/><span className="text-xs">{p.perf>=0?"+":""}{p.perf.toFixed(1)} %</span></td><td className="text-center"><button onClick={()=>setPositions(ps=>ps.filter((_,j)=>j!==i))} style={{color:DK.sub}}>✕</button></td></tr>))}</tbody></table></div>}
{posCalc.length>0&&<div className="mt-3 rounded-xl p-3" style={{background:"rgba(59,130,246,0.1)"}}><p className="text-xs" style={{color:DK.blue}}>💡 Mettez à jour la colonne « Prix actuel » régulièrement (via Google Finance, Boursorama…) pour suivre votre performance réelle. Les prix ne sont pas récupérés automatiquement.</p></div>}
</DCard>
</div>);

const dObj=()=>{const actions=getActions();const alerts=getAlerts();return(<div>
<DCard className="mb-4" style={{background:"linear-gradient(135deg,#141419,#1C1C24)"}}><p className="text-sm" style={{color:DK.sub}}>🔥 Nombre FIRE (indépendance financière)</p><p className="text-2xl font-black" style={{color:DK.txt}}>{fc(fireNumber)}</p><p className="text-xs mb-2" style={{color:DK.sub}}>= 25 × charges annuelles (règle des 4 %)</p><div className="w-full h-2.5 rounded-full overflow-hidden" style={{background:DK.card2}}><div className="h-full rounded-full" style={{width:`${fireProgress}%`,background:DK.grn}}/></div><p className="text-xs mt-1" style={{color:DK.grn}}>{fireProgress} % atteint · patrimoine {fc(patFin)}</p></DCard>
<DCard className="mb-4"><h3 className="font-bold mb-3" style={{color:DK.txt}}>🎯 Objectifs</h3>{userGoals.length===0?<p className="text-sm" style={{color:DK.sub}}>Aucun objectif.</p>:userGoals.map(g=>{const an=analyzeGoal(g);const col=an.status==="on_track"||an.status==="atteint"?DK.grn:an.status==="tight"?"#f59e0b":DK.red;return(<div key={g.id} className="mb-4"><div className="flex justify-between text-sm mb-1"><span style={{color:DK.txt}}>{g.emoji} {g.nom}</span><span style={{color:DK.sub}}>{fc(patFin)}/{fc(parseFloat(g.cible)||0)}</span></div><div className="w-full h-2.5 rounded-full overflow-hidden" style={{background:DK.card2}}><div className="h-full rounded-full" style={{width:`${Math.min(100,an.prog)}%`,background:col}}/></div><p className="text-xs mt-1" style={{color:col}}>{an.status==="atteint"?"🎉 Atteint !":an.status==="on_track"?`✅ ${fc(an.mn)}/mois (${an.yl}a)`:an.status==="tight"?`⚠️ ${fc(an.mn)}/mois`:`❌ ${fc(an.mn)}/mois`}</p></div>);})}</DCard>
<DCard className="mb-4"><h3 className="font-bold mb-3" style={{color:DK.txt}}>✅ Actions</h3>{actions.length===0?<p className="text-sm" style={{color:DK.grn}}>🎉 Tout bon !</p>:actions.map(a=>(<div key={a.id} className="flex items-start gap-3 mb-3"><button onClick={()=>setActionsDone(p=>({...p,[a.id]:!p[a.id]}))} className="mt-0.5 w-5 h-5 rounded border-2 flex-shrink-0 flex items-center justify-center" style={{borderColor:actionsDone[a.id]?DK.grn:DK.bd,background:actionsDone[a.id]?DK.grn:"transparent",color:"#08080B"}}>{actionsDone[a.id]&&"✓"}</button><div style={actionsDone[a.id]?{textDecoration:"line-through",color:DK.sub}:{color:DK.txt}}><p className="text-sm font-medium">{a.txt}</p><span className="text-xs px-2 py-0.5 rounded-full" style={{background:a.p==="critique"?"rgba(239,68,68,0.15)":"rgba(245,158,11,0.15)",color:a.p==="critique"?DK.red:"#f59e0b"}}>{a.p}</span></div></div>))}</DCard>
{alerts.length>0&&<DCard>{alerts.map((a,i)=>{const c=a.t==="success"?DK.grn:a.t==="warning"?"#f59e0b":a.t==="danger"?DK.red:DK.blue;return(<div key={i} className="rounded-xl p-3 mb-2" style={{background:DK.card2,borderLeft:`3px solid ${c}`}}><p className="font-bold text-sm" style={{color:DK.txt}}>{a.icon} {a.titre}</p><p className="text-sm" style={{color:DK.sub}}>{a.txt}</p></div>);})}</DCard>}
</div>);};
const dInvest=()=>{const recos=getRecos();const{score,details}=getDiversScore();const dca=getDCASplit();const tax=getTaxComparison();const reb=getRebalance();const dormant=Math.max(0,snap.cash-ch*1.1);return(<div>
{dormant>500&&<DCard className="mb-4" style={{borderColor:"#f59e0b"}}><h3 className="font-bold" style={{color:"#f59e0b"}}>💤 {fc(dormant)} dormants</h3><p className="text-sm" style={{color:DK.sub}}>Placez-les sur votre {moisEp<6?C.liv.n:C.inv.n}.</p></DCard>}
<DCard className="mb-4"><h3 className="font-bold mb-3" style={{color:DK.txt}}>📊 Score de diversification</h3><div className="flex items-start gap-4"><Gauge score={score} size={90}/><div className="flex-1"><p className="font-bold" style={{color:DK.txt}}>{score>=70?"Bien diversifié ✅":score>=40?"Peut mieux faire 🔶":"À améliorer ❌"}</p><div className="grid grid-cols-2 gap-1 mt-2">{details.map((d,i)=>(<div key={i} className="text-xs px-2 py-1 rounded" style={{background:d.ok?"rgba(34,197,94,0.12)":"rgba(239,68,68,0.1)",color:d.ok?DK.grn:DK.red}}>{d.ok?"✅":"❌"} {d.n}</div>))}</div></div></div></DCard>
{mi>0&&<DCard className="mb-4"><div className="flex items-center gap-2 mb-2"><h3 className="font-bold" style={{color:DK.txt}}>🔄 Répartiteur DCA</h3><button onClick={()=>setShowDCA(!showDCA)} className="text-xs px-2 py-1 rounded-lg" style={{background:DK.card2,color:DK.sub}}>{showDCA?"Masquer":"C'est quoi ?"}</button></div>{showDCA&&<div className="rounded-xl p-3 mb-3 text-sm" style={{background:"rgba(59,130,246,0.1)",color:DK.blue}}><strong>DCA</strong> = investir le même montant chaque mois. 📉 Baisse → soldes. 📈 Hausse → gains. Bat 95 % des investisseurs.</div>}<p className="text-sm mb-3" style={{color:DK.sub}}>Répartition de vos <strong style={{color:DK.txt}}>{fc(mi)}/mois</strong> ({C.inv.bk}) :</p>{dca.map((e,i)=>(<div key={i} className="flex justify-between items-start rounded-xl p-3 mb-2" style={{background:DK.card2}}><div><p className="font-bold text-sm" style={{color:DK.txt}}>{e.n}</p><p className="text-xs font-mono" style={{color:DK.sub}}>{e.isin}</p><p className="text-xs mt-1" style={{color:DK.sub}}>📝 {e.why}</p></div><div className="text-right ml-3"><p className="text-lg font-bold" style={{color:DK.grn}}>{fc(e.montant)}</p><p className="text-xs" style={{color:DK.sub}}>{e.p} %</p></div></div>))}</DCard>}
{mi>0&&<DCard className="mb-4"><h3 className="font-bold mb-1" style={{color:DK.txt}}>💰 Économie fiscale</h3><p className="text-xs mb-3" style={{color:DK.sub}}>{C.tax.optim.n} ({C.tax.optim.r} %) vs {C.tax.std.n} ({C.tax.std.r} %)</p><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr style={{color:DK.sub}}><th className="text-left py-2">Horizon</th><th>Gains</th><th style={{color:DK.grn}}>Optim.</th><th style={{color:DK.red}}>Std</th><th style={{color:DK.blue}}>Économie</th></tr></thead><tbody>{tax.map((r,i)=>(<tr key={i} style={{borderTop:`1px solid ${DK.bd}`,color:DK.txt}}><td className="py-2">{r.y} ans</td><td className="text-center">{fmt(r.gains)}</td><td className="text-center" style={{color:DK.grn}}>{fmt(r.taxOptim)}</td><td className="text-center" style={{color:DK.red}}>{fmt(r.taxStd)}</td><td className="text-center font-bold" style={{color:DK.blue}}>{fmt(r.saved)}</td></tr>))}</tbody></table></div><p className="text-xs mt-2" style={{color:DK.sub}}>En 20 ans, l'enveloppe optimisée économise <strong style={{color:DK.blue}}>{fc(tax[3]?.saved)}</strong> d'impôts.</p></DCard>}
<DCard className="mb-4"><h3 className="font-bold mb-3" style={{color:DK.txt}}>⚖️ Signaux de rééquilibrage</h3>{reb.map((s,i)=>{const c=s.sev==="success"?DK.grn:s.sev==="warning"?"#f59e0b":DK.blue;return(<div key={i} className="rounded-xl p-3 mb-2" style={{background:DK.card2,borderLeft:`3px solid ${c}`}}><p className="font-bold text-sm" style={{color:DK.txt}}>{s.icon} {s.msg}</p><p className="text-sm mt-1" style={{color:DK.txt}}>👉 {s.action}</p><p className="text-xs mt-1" style={{color:DK.sub}}>{s.det}</p></div>);})}</DCard>
{recos.map((tier,ti)=>(<DCard key={ti} className="mb-4"><h3 className="font-bold mb-2" style={{color:DK.txt}}>{tier.tier}</h3>{tier.items.map((item,ii)=>(<div key={ii} className="rounded-xl p-3 mb-2" style={{background:DK.card2,border:`1px solid ${item.has?DK.grn:DK.bd}`}}><div className="flex items-center gap-2"><span className="font-bold text-sm" style={{color:DK.txt}}>{item.nom}</span><span className="text-xs ml-auto" style={{color:item.has?DK.grn:DK.sub}}>{item.has?"✅ Actif":"À ouvrir"}</span></div><p className="text-sm" style={{color:DK.sub}}>{item.desc}</p><p className="text-xs mt-1" style={{color:DK.sub}}>📈 {item.rdt} · ⚡ {item.risque}</p></div>))}</DCard>))}
</div>);};
const dBP=()=>{const data=genBP();const bpA=getBPAlerts(data);return(<div>
<DCard className="mb-4"><h3 className="font-bold mb-3" style={{color:DK.txt}}>⚙️ Hypothèses</h3><div className="grid grid-cols-3 gap-2 mb-3">{Object.entries(SCEN).map(([k,s])=>(<button key={k} onClick={()=>applyScenario(k)} className="p-2.5 rounded-xl text-center text-sm font-bold" style={{background:bpRetAct===s.rA?"rgba(59,130,246,0.15)":DK.card2,border:`1px solid ${bpRetAct===s.rA?DK.blue:DK.bd}`,color:DK.txt}}>{s.l}</button>))}</div><div className="grid grid-cols-3 gap-2"><DInp id="sg" label="Salaire/an" value={bpSalG} onChange={setBpSalG} suffix="%"/><DInp id="inf" label="Inflation" value={bpInfl} onChange={setBpInfl} suffix="%"/><DInp id="ra" label="Actions" value={bpRetAct} onChange={setBpRetAct} suffix="%"/></div></DCard>
{bpA.length>0&&<DCard className="mb-4"><h3 className="font-bold mb-3" style={{color:DK.txt}}>⚠️ Faisabilité</h3>{bpA.map((a,i)=>{const c=a.type==="danger"?DK.red:DK.grn;return(<div key={i} className="rounded-xl p-3 mb-2" style={{background:DK.card2,borderLeft:`3px solid ${c}`}}><p className="font-bold text-sm" style={{color:DK.txt}}>{a.emoji} {a.nom}</p><p className="text-sm" style={{color:DK.sub}}>{a.msg}</p>{a.conseil&&<p className="text-sm italic" style={{color:DK.sub}}>💡 {a.conseil}</p>}</div>);})}</DCard>}
<DCard className="mb-4"><div className="flex justify-between mb-3"><h3 className="font-bold" style={{color:DK.txt}}>📅 Événements</h3><button onClick={()=>setShowEvF(!showEvF)} className="text-xs px-3 py-1 rounded-lg" style={{background:DK.card2,color:DK.sub}}>{showEvF?"✕":"+ Ajouter"}</button></div>{showEvF&&<div className="rounded-xl p-3 mb-3" style={{background:DK.card2}}><div className="grid grid-cols-3 gap-2"><DInp id="evn" label="Nom" value={newEv.nom} onChange={v=>setNewEv({...newEv,nom:v})} type="text"/><DInp id="evy" label="Année" value={newEv.annee} onChange={v=>setNewEv({...newEv,annee:v})}/><DInp id="evc" label="Coût" value={newEv.cout} onChange={v=>setNewEv({...newEv,cout:v})} suffix={cur}/></div><div className="text-right"><button onClick={()=>{if(newEv.nom){setBpEvents(p=>[...p,newEv]);setNewEv({nom:"",annee:"",cout:""});setShowEvF(false);}}} className="text-sm font-semibold px-4 py-2 rounded-lg" style={{background:DK.blue,color:"#fff"}}>OK</button></div></div>}{bpEvents.map((e,i)=>(<div key={i} className="flex justify-between text-sm py-2" style={{borderBottom:`1px solid ${DK.bd}`,color:DK.txt}}><span>An {e.annee} : {e.nom}</span><span style={{color:DK.red}}>{fc(parseFloat(e.cout)||0)} <button onClick={()=>setBpEvents(p=>p.filter((_,j)=>j!==i))} style={{color:DK.sub}}>✕</button></span></div>))}</DCard>
<DCard className="mb-4"><h3 className="font-bold mb-3" style={{color:DK.txt}}>📊 Trajectoire (20 ans)</h3><ResponsiveContainer width="100%" height={230}><AreaChart data={data}><CartesianGrid strokeDasharray="3 3" stroke={DK.bd}/><XAxis dataKey="age" tick={axis}/><YAxis tick={axis} tickFormatter={v=>v>=1e6?`${(v/1e6).toFixed(1)}M`:v>=1000?`${(v/1000).toFixed(0)}k`:v}/><RTooltip contentStyle={{background:DK.card2,border:`1px solid ${DK.bd}`,borderRadius:8,color:DK.txt}} formatter={v=>fc(v)}/><Legend wrapperStyle={{fontSize:11,color:DK.sub}}/><Area type="monotone" dataKey="pea" stackId="1" fill="#3b82f6" stroke="#3b82f6" name={C.inv.n}/><Area type="monotone" dataKey="av" stackId="1" fill="#22c55e" stroke="#22c55e" name="Assurance"/><Area type="monotone" dataKey="liv" stackId="1" fill="#f59e0b" stroke="#f59e0b" name="Livrets"/></AreaChart></ResponsiveContainer><p className="text-xs mt-2" style={{color:DK.sub}}>💡 « Valeur réelle » = pouvoir d'achat corrigé de l'inflation.</p></DCard>
<DCard><h3 className="font-bold mb-3" style={{color:DK.txt}}>📋 Détail</h3><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr style={{color:DK.sub}}><th className="text-left py-2">An</th><th>Âge</th><th>Total</th><th>Réel (infl.)</th></tr></thead><tbody>{data.map((r,i)=>(<tr key={i} style={{borderTop:`1px solid ${DK.bd}`,color:DK.txt,background:r.ev?"rgba(245,158,11,0.08)":"transparent"}}><td className="py-1.5">{r.y}</td><td className="text-center">{r.age}</td><td className="text-center font-bold">{fmt(r.total)}</td><td className="text-center" style={{color:DK.sub}}>{fmt(r.reel)}</td></tr>))}</tbody></table></div></DCard>
</div>);};
const dTools=()=>(<div><div className="flex gap-1 mb-4 rounded-xl p-1" style={{background:DK.card2}}>{[["acheter","🏠 Acheter/Louer"],["credits","💳 Crédits"],["couple","👫 Couple"]].map(([k,l])=>(<button key={k} onClick={()=>setToolTab(k)} className="flex-1 py-2 text-xs font-semibold rounded-lg" style={{background:toolTab===k?DK.card:"transparent",color:toolTab===k?DK.txt:DK.sub}}>{l}</button>))}</div>
{toolTab==="acheter"&&<div><DCard className="mb-4"><h3 className="font-bold mb-3" style={{color:DK.txt}}>🏠 Acheter vs Louer</h3><div className="grid grid-cols-2 gap-2"><DInp id="bp" label="Prix bien" value={bienPrix} onChange={setBienPrix} placeholder="250 000" suffix={cur}/><DInp id="app" label="Apport" value={apport} onChange={setApport} placeholder="50 000" suffix={cur}/><DInp id="tc" label="Taux" value={tauxCr} onChange={setTauxCr} suffix="%"/><DInp id="dc" label="Durée" value={dureeCr} onChange={setDureeCr} suffix="ans"/><DInp id="loa" label="Loyer actuel" value={loyerAct} onChange={setLoyerAct} placeholder="800" suffix={cur+"/m"}/><DInp id="cop" label="Charges copro" value={chargesCo} onChange={setChargesCo} placeholder="150" suffix={cur+"/m"}/><DInp id="tf" label="Taxe foncière" value={taxeF} onChange={setTaxeF} placeholder="1200" suffix={cur+"/an"}/></div></DCard>{(()=>{const p=parseFloat(bienPrix)||0,a=parseFloat(apport)||0,tx=(parseFloat(tauxCr)||0)/100/12,dur=(parseFloat(dureeCr)||25)*12,lo=parseFloat(loyerAct)||0,co=parseFloat(chargesCo)||0,tf=(parseFloat(taxeF)||0)/12;if(!p||!tx)return null;const empr=p-a;const mens=empr*(tx*Math.pow(1+tx,dur))/(Math.pow(1+tx,dur)-1);const cp=Math.round(mens)+co+Math.round(tf);const diff=cp-lo;const inter=Math.round(mens*dur-empr);const pm=lo>0?Math.round((a+inter)/(lo*12)):0;return<DCard><h3 className="font-bold mb-3" style={{color:DK.txt}}>📊 Résultat</h3><div className="grid grid-cols-2 gap-2 mb-3">{[["Mensualité",fc(mens),DK.blue],["Coût proprio/m",fc(cp),"#f59e0b"],["vs loyer",(diff>0?"+":"")+fc(diff),diff>0?DK.red:DK.grn],["Point mort","~"+pm+" ans",DK.txt]].map((x,i)=>(<div key={i} className="rounded-xl p-3 text-center" style={{background:DK.card2}}><p className="text-xs" style={{color:DK.sub}}>{x[0]}</p><p className="text-base font-bold" style={{color:x[2]}}>{x[1]}</p></div>))}</div><div className="rounded-xl p-3" style={{background:"rgba(59,130,246,0.1)"}}><p className="text-sm" style={{color:DK.blue}}>{pm<=5?"🟢 Achat très rentable !":pm<=10?"🟡 Rentable si vous restez.":"🔴 Long, vérifiez."}</p></div></DCard>;})()}</div>}
{toolTab==="credits"&&<div><DCard className="mb-4"><h3 className="font-bold mb-3" style={{color:DK.txt}}>💳 Optimiseur crédits</h3><button onClick={()=>setShowCF(!showCF)} className="text-xs font-semibold px-4 py-2 rounded-lg mb-3" style={{background:DK.blue,color:"#fff"}}>{showCF?"✕":"+ Ajouter"}</button>{showCF&&<div className="rounded-xl p-3 mb-3" style={{background:DK.card2}}><div className="grid grid-cols-2 gap-2"><DInp id="cn" label="Nom" value={newCr.nom} onChange={v=>setNewCr({...newCr,nom:v})} type="text"/><DInp id="crr" label="Restant" value={newCr.restant} onChange={v=>setNewCr({...newCr,restant:v})} suffix={cur}/><DInp id="ct" label="Taux" value={newCr.taux} onChange={v=>setNewCr({...newCr,taux:v})} suffix="%"/><DInp id="cm" label="Mensualité" value={newCr.mensualite} onChange={v=>setNewCr({...newCr,mensualite:v})} suffix={cur}/></div><div className="text-right"><button onClick={()=>{if(newCr.nom){setCredits(p=>[...p,newCr]);setNewCr({nom:"",restant:"",taux:"",mensualite:""});setShowCF(false);}}} className="text-sm font-semibold px-4 py-2 rounded-lg" style={{background:DK.blue,color:"#fff"}}>OK</button></div></div>}{credits.map((c,i)=>(<div key={i} className="flex justify-between py-2" style={{borderBottom:`1px solid ${DK.bd}`}}><div><p className="font-bold text-sm" style={{color:DK.txt}}>{c.nom}</p><p className="text-xs" style={{color:DK.sub}}>{fc(parseFloat(c.restant)||0)} à {c.taux} %</p></div><button onClick={()=>setCredits(p=>p.filter((_,j)=>j!==i))} style={{color:DK.sub}}>✕</button></div>))}</DCard>{credits.length>0&&(()=>{const avg=credits.reduce((s,c)=>s+(parseFloat(c.taux)||0),0)/credits.length;const sorted=avg>5?[...credits].sort((a,b)=>(parseFloat(b.taux)||0)-(parseFloat(a.taux)||0)):[...credits].sort((a,b)=>(parseFloat(a.restant)||0)-(parseFloat(b.restant)||0));return<DCard><h3 className="font-bold mb-2" style={{color:DK.txt}}>🎯 {avg>5?"🔥 Avalanche":"❄️ Boule de Neige"}</h3><p className="text-sm mb-3" style={{color:DK.sub}}>{avg>5?"Remboursez le taux le plus élevé d'abord.":"Remboursez le plus petit solde d'abord."}</p><ol className="list-decimal ml-5 text-sm" style={{color:DK.txt}}>{sorted.map((c,i)=>(<li key={i} className="mb-1"><strong>{c.nom}</strong> — {fc(parseFloat(c.restant)||0)} à {c.taux} %</li>))}</ol></DCard>;})()}</div>}
{toolTab==="couple"&&<DCard>{!modeCouple?<div className="text-center py-6"><p style={{color:DK.sub}} className="mb-3">Mode couple inactif.</p><button onClick={()=>{setPage("q");setStep(1);}} className="text-sm font-semibold px-4 py-2 rounded-lg" style={{background:DK.blue,color:"#fff"}}>Activer →</button></div>:<div><h3 className="font-bold mb-3" style={{color:DK.txt}}>👫 Finances couple</h3><div className="grid grid-cols-2 gap-2 mb-3">{[["Vous",fc(rev)+"/m"],["Conjoint(e)",fc(parseFloat(p2Rev)||0)+"/m"]].map((x,i)=>(<div key={i} className="rounded-xl p-3" style={{background:DK.card2}}><p className="text-xs" style={{color:DK.sub}}>{x[0]}</p><p className="font-bold" style={{color:DK.txt}}>{x[1]}</p></div>))}<div className="rounded-xl p-3 col-span-2" style={{background:"rgba(34,197,94,0.12)"}}><p className="text-xs" style={{color:DK.sub}}>Couple</p><p className="text-base font-bold" style={{color:DK.grn}}>{fc(coupleRev)}/m → {fc(coupleDispo)} dispo</p></div></div><div className="rounded-xl p-3" style={{background:DK.card2}}><p className="font-bold text-sm mb-2" style={{color:DK.txt}}>💡 Conseils</p><ul className="text-sm space-y-1" style={{color:DK.sub}}><li>📊 DCA couple : {fc(mi)}/mois</li><li>🏦 Chacun son {C.inv.n}</li><li>🛡️ Matelas commun : {fc(coupleCh*6)}</li>{tmi>=30&&<li>🏛️ {C.ret.n} pour le plus imposé (TMI {tmi} %)</li>}</ul></div></div>}</DCard>}
</div>);

const TABS=[["patrimoine","💰","Patrimoine"],["portefeuille","📈","Portefeuille"],["objectifs","🎯","Objectifs"],["invest","💡","Conseils"],["bp","📊","Projection"],["tools","🧰","Outils"]];

if(page==="q")return(<div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-50"><header className="bg-white border-b border-slate-200 sticky top-0 z-40"><div className="max-w-2xl mx-auto flex items-center justify-between px-4 py-2"><h1 className="text-lg font-black">💸 Nheb Barcha Flous</h1>{done&&<button onClick={()=>setPage("d")} className="text-xs px-3 py-1.5 rounded-lg font-semibold bg-blue-600 text-white">📊 Dashboard</button>}</div></header><div className="max-w-2xl mx-auto px-4 py-6">{cs!=="intro"&&cs!=="resultats"&&<Prog c={step} t={steps.length-1}/>}<Card>{renderStep()}</Card>{cs!=="intro"&&cs!=="resultats"&&<div className="flex justify-between mt-6"><Btn onClick={prev} secondary>← Retour</Btn><Btn onClick={next}>Suivant →</Btn></div>}</div></div>);

return(<div className="min-h-screen flex" style={{background:DK.bg}}>
<aside className="flex flex-col shrink-0" style={{width:170,background:DK.card,borderRight:`1px solid ${DK.bd}`,position:"sticky",top:0,height:"100vh"}}>
<div className="px-4 py-4" style={{borderBottom:`1px solid ${DK.bd}`}}><h1 className="text-sm font-black" style={{color:DK.txt}}>💸 Nheb Barcha</h1><p className="text-xs" style={{color:DK.sub}}>{C.l}</p></div>
<nav className="flex-1 p-2 space-y-1">{TABS.map(([k,ic,l])=>(<button key={k} onClick={()=>setDashTab(k)} className="w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-semibold transition" style={{background:dashTab===k?"rgba(34,197,94,0.15)":"transparent",color:dashTab===k?DK.grn:DK.sub}}><span>{ic}</span>{l}</button>))}</nav>
<div className="p-2" style={{borderTop:`1px solid ${DK.bd}`}}><button onClick={()=>{setPage("q");setStep(steps.indexOf("resultats"));}} className="w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-semibold" style={{color:DK.sub}}><span>📋</span>Questionnaire</button></div>
</aside>
<main className="flex-1 overflow-x-hidden"><div className="max-w-3xl mx-auto px-4 py-5">
<h2 className="text-2xl font-black mb-5" style={{color:DK.txt}}>{TABS.find(t=>t[0]===dashTab)?.[2]}</h2>
{dashTab==="patrimoine"&&dPatrimoine()}{dashTab==="portefeuille"&&dPortefeuille()}{dashTab==="objectifs"&&dObj()}{dashTab==="invest"&&dInvest()}{dashTab==="bp"&&dBP()}{dashTab==="tools"&&dTools()}
</div></main>
</div>);
}
